= Using asynchronous frameworks
:page-topic-type: concept

[abstract]
In addition to the simple synchronous API, the Python SDK supports native integration with _gevent_ and _twisted_ asynchronous frameworks for high network performance.

NOTE: See xref:4.1@server:developer-guide:async-clients.adoc[Reactive asynchronous clients] for a general overview on asynchronous/reactive programming and the performance benefits possible when used with Couchbase.

== gevent API

http://www.gevent.org[gevent^] is a high performance asynchronous framework.
It is very powerful in that it allows for a (mostly) traditional synchronous coding style.
It accomplishes this by using coroutines known as [.term]_greenlets_ or [.term]_eventlets_.

The gevent API is almost identical to the simple synchronous API, though it requires that a different module be imported to properly integrate with gevent.

[source,python]
----
from gcouchbase.bucket import Bucket
bucket = Bucket('couchbase://localhost/default')
bucket.upsert('id', {'some':['value']})
print bucket.get('id').value
----

== Twisted API

http://twistedmatrix.com[Twisted^] is a high performance and very mature Python asynchronous framework.

[source,python]
----
from twisted.internet import reactor
from txcouchbase.bucket import Bucket
bucket = Bucket('couchbase://localhost/default')

def on_ok(result):
    print "Operation succeeded"
    if hasattr(result, 'value'):
        print "Value is", result.value

def on_err(err):
    print "Operation failed", err

bucket.upsert('id', {'some':['value']}).addBoth(on_ok, on_err)
bucket.get('id').addBoth(on_ok, on_err)
----
