= Compatibility

:page-aliases: overview,migrating

== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Python SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not supported or recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,25,25,20,20"]
|===
| | SDK 2.1, 2.2 | SDK 2.3 | SDK 2.4 | SDK 2.5

| *Server 4.0-4.5*
| ◎
| *✔*
| *✔*
| *✔*

| *Server 4.6*
| ◎
| *✔*
| *✔*
| *✔*

| *Server 5.0-5.5*
| ◎
| *✔*
| *✔*
| *✔*

| *Server 6.0*
| *✖*
| *✖*
| *✖*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

== Feature Compatibility

To take advantage of all features offered by Couchbase Server, you need to know what version of the client provides compatibility for the features you want to use.
The following matrix shows which versions of the Python client support the major features of each version of Couchbase Server.

Note that some of the features are dependent on the underlying C library (_libcouchbase_).


.Couchbase Server and SDK Supported Version Matrix
[cols="<25,.^23,.^24,.^18,.^19"]
|===
| | Server 4.0, 4.1 | Server 4.5, 4.6 | Server 5.x | Server 6.0

5+| *Basic Features*

| CRUD Operations
4+| All Versions

| View Querying APIs
4+| All Versions

| Geospatial Views
4+| All Versions

5+| *Advanced Features*

| Durability Requirements
4+| All Versions

| Carrier Publication Configuration
4+| All Versions

| SSL Connectivity
4+| All Versions

| Bulk Operations
4+| All Versions

| N1QL Querying
4+| All Versions

| Multi-Dimensional Scaling
4+| All Versions

| Sub-document API
4+| Since 2.1

| Full Text Search
| Since 2.1 (Experimental)
3+| Since 2.2

| Global Secondary Indexes (GSI)
4+| All Versions

| Memory Optimized Indexes (MOI)
| Not Supported
3+| All SDK versions

| Plasma Storage for Indexes
2+| Not Supported
2+| All SDK versions

| FTS Index Management from the SDK
2+| Not Supported
2+| Since 2.1

| Data Structures
| Not Supported
3+| Since 2.1

| Extended Attributes
2+| Not Supported
2+| Since 2.2.5

| RBAC
2+| Not Supported
2+| Since 2.2.6

| Analytics
2+| Not supported
| DP in 5.5 with 2.4
| Since 2.5

5+| *Administrative Features*

| Administrative API
4+| All Versions
|===

IMPORTANT: With xref:sdk-authentication-overview.adoc[RBAC], in Couchbase Server 5.0, authentication will depend upon access privileges, and upgrading to 5.0 with existing buckets, or upgrading Server, will require taking these changes into account.


== Platform Compatibility

We support a number of Python versions on MacOS, Windows and Linux.

[#ul_compat_legend]
* ✖ *Unsupported* : This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible* : This combination has been tested previously, and should be compatible.
This combination is not supported or recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported* :This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.
* U *Supported on Unix systems only* : This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization, but only on Unix-based systems, i.e. MacOS and Linux.

.Couchbase Python SDK and Python Version Compatibility Version Matrix
[#table_python_versions]
|===
| _Python Version/Couchbase SDK version_ | *SDK 2.2.6* | *SDK 2.3.0* | *SDK 2.5.1*

| *2.7*
| *✔*
| *✔*
| *U*

| *3.2*
| *◎*
| *✖*
| *✖*

| *3.3*
| *◎*
| *◎*
| *◎*

| *3.4*
| *◎*
| *◎*
| *◎*

| *3.6*
| *✔*
| *✔*
| *✔*

| *3.7*
| *x*
| *x*
| *✔*

|===

include::6.0@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]
