= Compatibility

== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Python SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not supported or recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Couchbase Server and Python SDK Version Compatibility Matrix
[#table_sdk_versions]
|===
| _Couchbase Server/Couchbase Python SDK_ | *SDK 2.0* | *SDK 2.1* | *SDK 2.2* | *SDK 2.3*

| *CB 3.1*
| *◎*
| *◎*
| *◎*
| *◎*

| *CB 4.0 - 4.6*
| *✔*
| *✔*
| *✔*
| *✔*

| *CB 5.0 - 5.1*
| *◎*
| *✔*
| *✔*
| *✔*
|===

== Feature Compatibility

To take advantage of all features offered by Couchbase Server, you need to know what version of the client provides compatibility for the features you want to use.
The following matrix shows which versions of the Python client support the major features of each version of Couchbase Server.

Note that some of the features are dependent on the underlying C library (_libcouchbase_).

.Couchbase Server and Python SDK Feature Compatibility Matrix
[cols="6,5,5,5,5,5,5,5,5"]
|===
| Feature | Server 1.8 | Server 2.0 | Server 2.5 | Server 3.0 | Server 4.0 | Server 4.5 | Server 4.6 | Server 5.0

9+| *Basic features*

| CRUD operations
8+| Since 1.0

| View Querying APIs
8+| Since 1.0

9+| *Advanced features*

| Durability Requirements
8+| Since 1.1.0/_libcouchbase_ 2.3.0

| Fast (CCCP) Bootstrapping
2+| Not Supported
6+| Since _libcouchbase 2.3.0_

| SSL Connectivity
3+| Not Supported
5+| Since 2.0 / _libcouchbase 2.4.0_

| Bulk Operations
8+| Since 1.0

| Cross-SDK Data types
2+| Not Supported
6+| Since 2.0

| N1QL Querying
4+| Not Supported
4+| Since 2.0.1

| Extended Attributes
7+| Not Supported
| Since 2.2.5

9+| *Administrative Features*

| Administrative API
8+| Not Supported

| RBAC
7+| Not Supported
| Since 2.2.6
|===

== Platform Compatibility

We support a number of Python versions on MacOS, Windows and Linux.

[#ul_compat_legend]
* ✖ *Unsupported* : This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible* : This combination has been tested previously, and should be compatible.
This combination is not supported or recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported* :This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.
* U *Supported on Unix systems only* : This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization, but only on Unix-based systems, i.e. MacOS and Linux.

.Couchbase Python SDK and Python Version Compatibility Version Matrix
[#table_python_versions]
|===
| _Python Version/Couchbase SDK version_ | *SDK 2.2.6* | *SDK 2.3.0* | *SDK 2.5.1*

| *2.7*
| *✔*
| *✔*
| *U*

| *3.2*
| *◎*
| *✖*
| *✖*

| *3.3*
| *◎*
| *◎*
| *◎*

| *3.4*
| *◎*
| *◎*
| *◎*

| *3.6*
| *✔*
| *✔*
| *✔*

| *3.7*
| *x*
| *x*
| *✔*

|===

include::6.0@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]
