= Compatibility of Couchbase Features, Couchbase Versions and the Couchbase Python SDK

== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Python SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not supported or recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*:This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Couchbase Python SDK and Couchbase Server Compatibility Version Matrix
[#table_sdk_versions]
|===
| _CB/SDK_ | *SDK 2.0* | *SDK 2.1*

| *CB 2.5*
| *◎*
| *◎*

| *CB 3.0*
| *◎*
| *◎*

| *CB 3.1*
| *◎*
| *✔*

| *CB 4.0*
| *✔*
| *✔*

| *CB 4.1*
| *✔*
| *✔*

| *CB 4.5*
| *✔*
| *✔*
|===

== Feature Compatibility

To take advantage of all features offered by Couchbase Server, you need to know what version of the client provides compatibility for the features you want to use.
The following matrix shows which versions of the Python client support the major features of each version of Couchbase Server.

Note that some of the features are dependent on the underlying C library (_libcouchbase_).

.Couchbase Server and SDK Supported Version Matrix
[cols="6,5,5,5,5,5,5"]
|===
| Feature | Server 1.8 | Server 2.0 | Server 2.5 | Server 3.0 | Server 4.0 | Server 4.5

7+| *Basic features*

| CRUD operations
6+| Since 1.0

| View Querying APIs
6+| Since 1.0

7+| *Advanced features*

| Durability Requirements
6+| Since 1.1.0/_libcouchbase_ 2.3.0

| Fast (CCCP) Bootstrapping
2+| Not Supported
4+| Since _libcouchbase 2.3.0_

| SSL Connectivity
3+| Not Supported
3+| Since 2.0 / _libcouchbase 2.4.0_

| Bulk Operations
6+| Since 1.0

| Cross-SDK Data types
2+| Not Supported
4+| Since 2.0

| N1QL Querying
4+| Not Supported
2+| Since 2.0.1

7+| *Administrative Features*

| Administrative API
6+| Not Supported
|===

include::4.5@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]
