= Full Text Search (FTS) Using the Python SDK with Couchbase Server
:navtitle: Searching from the SDK

[abstract]
You can use the Full Text Search service (FTS) to create queryable full-text indexes in Couchbase Server.

Couchbase offers Full-text search support, allowing you to search for documents that contain certain words or phrases.
In the Python SDK you can search full-text indexes by using the iterator-based [.api]`Bucket.search()` API.

include::4.5@sdk:shared:partial$experimental-pars.adoc[tag=fts]

Querying a FTS index through the Python client is performed through the [.api]`Bucket.search()`.
This method takes two parameters, the index name to query and the actual search query itself.
Additional search options may be specified as keyword arguments.

[source,python]
----
import couchbase.fulltext as FT
results = cb.search('travel-search', FT.TermQuery('office'), limit=25)
for result in results:
    print(result['id'])
----

The [.api]`Bucket.search()` method returns an object which may be iterated over to retrieve the results.
Each result is a dictionary comprising the layout defined in xref:4.5@server:fts:fts-response-object-schema.adoc[Response Object Schema].

Other search result data may be accessed using the iterator's [.api]`meta` and [.api]`facets` properties:

[source,python]
----
results = cb.search(indexname, query)
for result in results:
    handle_result(result)
print(results.meta)
print(results.facets)
----

== Query Types

Query types may be found inside the `couchbase.fulltext` module.
The module contains query classes corresponding to those enumerated in xref:4.5@server:fts:fts-query-types.adoc[Types of Queries].
Query object should be instantiated by passing the search term (usually a string) as the first argument, followed by some query modifiers.

It is important to distinguish between _query options_ and general _search options_.
Some options affect the search process in general (such as the [.param]`limit`, indicating how many results to return) while others only affect a specific query (such as [.param]`fuzziness` for a given query).
Because multiple queries can be combined in a single search operation, _query specific options_ can be specified only in the query object itself, while _search options_ are specified as keyword arguments to [.api]`search()`.

== Query Facets

Query xref:full-text-search-overview.adoc#facets[facets] may also be added to the _general search parameters_ by using the [.param]`facets={}` keyword argument.
The [.param]`facets` keyword argument accepts a dictionary with facet names as keys and facets themselves as values.
You can create facet queries by instantiating [.api]`Facet` objects found in the [.api]`couchbase.fulltext` module.

[source,python]
----
results = cb.search(
        'travel-search', FT.MatchQuery('wine'),
        facets={'countries': FT.TermFacet('country', limit=5)}, limit=0)

# Exhaust the iterator
for _ in results:
    pass

for info in results.facets['countries']['terms']:
    print('Got {} results from {}'.format(info['count'], info['term']))
----
