= Managing Connections Using the Python SDK with Couchbase Server
:navtitle: Managing Connections
:page-topic-type: concept

[abstract]
This section describes how to connect the Python SDK to a Couchbase cluster and bucket.
It contains best practices as well as information on the connection string,  SSL and other advanced connection options.

include::6.0@sdk:shared:partial$lcb-pars-shared.adoc[tag=connstr-intro]

== Connecting to a Bucket

All Couchbase Server-resources are protected by _Role-Based Access Control_ (RBAC).
Therefore, to connect to a bucket, you must pass appropriate _credentials_: these consist of a _username_ and _password_ that correspond to a user currently defined on Couchbase Server.
This user-definition is associated with one or more _roles_, each of which in turn corresponds to a set of _privileges_.
When authentication occurs, Couchbase Server checks to ensure that the authenticated user's privileges do permit access to the requested resource: if they do not, access is denied.

The following code demonstrates how authentication can be managed:

[source,python]
----
from couchbase.cluster import Cluster
from couchbase.cluster import PasswordAuthenticator
cluster = Cluster('couchbase://localhost')
authenticator = PasswordAuthenticator('username', 'password')
cluster.authenticate(authenticator)
cb = cluster.open_bucket('bucket-name')
----

For more information on authentication and RBAC, see xref:sdk-authentication-overview.adoc[Authentication].

Note that a bucket-connection closes once it falls out of scope and has no other objects referencing it.
It is advised to create only a single bucket object per application (or thread) for each Couchbase bucket your application connects to.

== Disconnecting from a Bucket

A [.api]`Bucket` object will disconnect from the cluster when it falls out of scope; that is, when it is no longer being referenced by anything in your Python application.
You can still close a bucket manually via the synchronous API using the [.api]`Bucket._close()` method.
This method should only be used as a last resort, as it may cause unexpected behavior if there are pending operations on the object.

== Scalability and concurrency

Creating a new [.api]`Bucket` object is relatively expensive, and keeping many idle [.api]`Bucket` objects will negatively impact server performance (if done at a large scale).

If using an asynchronous framework (such as Gevent or Twisted), your application will require only one [.api]`Bucket` instance per Couchbase bucket.
Likewise, if your Python application only contains a single thread then you need establish only a single [.api]`Bucket` object per Couchbase bucket.

If using multiple Python threads, it may be possible to share a single [.api]`Bucket` object across multiple threads (using locking).
The exact number of [.api]`Bucket` objects to be created will depend on the activity pattern of the application.
It is recommended to start off and develop with a single object for all threads.
If you realize that your application is suffering in performance because of threads waiting for the [.api]`Bucket` object's lock, you may implement a form of pooling or sharing so that _n_ number of buckets be available.

If using multiple processes (such as with the `multiprocessing` module), or using a Python module which creates multiple processes, ensure that the [.api]`Bucket` object is not created in the parent process!
Your Python interpreter may crash if the same [.api]`Bucket` object exists in more than a single process.

include::6.0@sdk:pages:partial$max-connections.adoc[tag=limits]

include::2.8@c-sdk::page$managing-connections.adoc[tag=group]

[NOTE]
====

From Couchbase Python Client 2.5.1, [.api]`AlternateAddress` is implemented, for connecting to nodes in a NATed environment, such as Docker containers using portmapping.
It is on by default, if the server provides a topology that includes a multi-network configuration.
Whichever network is selected at bootstrap will be logged.

If using __Docker Swarm__, or otherwise running the SDK inside the NAT, then you will want to disable with `?network=default` in the connection string, or an xref:client-settings.adoc[environmental setting] can be made.

Note that any SSL/TLS certificates must be set up at the point where the connections are being made.
The Couchbase SDKs will honor any valid SSL/TLS certificates.

====
