= Managing Connections Using the Python SDK with Couchbase Server
:navtitle: Managing Connections
:page-topic-type: concept

[abstract]
This section describes how to connect the Python SDK to a Couchbase cluster and bucket.
It contains best practices as well as information on the connection string,  SSL and other advanced connection options.

include::4.5@sdk:shared:partial$lcb-pars-shared.adoc[tag=connstr-intro]

== Connecting to a Bucket

To connect to a bucket using the synchronous API, simply create a new [.api]`Bucket` object by calling its constructor.
You should pass a _connection string_ to the bucket indicating the host(s) and bucket you want to connect to.
If your bucket is protected by a password, pass the [.var]`password` keyword argument to the constructor.

[source,python]
----
from couchbase.bucket import Bucket
bucket = Bucket('couchbase://10.1.1.1/default')
# With a password:
protected_bucket = Bucket('couchbase://10.1.1.1/default', password='s3cr3t')
----

The bucket connection will close once it falls out of scope and has no other objects referencing it.
It is advised to create only a single bucket object per application (or thread) for each Couchbase bucket your application connects to.

== Disconnecting from a Bucket

A [.api]`Bucket` object will disconnect from the cluster when it falls out of scope; that is, when it is no longer being referenced by anything in your Python application.
You can still close a bucket manually via the synchronous API using the [.api]`Bucket._close()` method.
This method should only be used as a last resort, as it may cause unexpected behavior if there are pending operations on the object.

== Scalability and concurrency

Creating a new [.api]`Bucket` object is relatively expensive, and keeping many idle [.api]`Bucket` objects will negatively impact server performance (if done at a large scale).

If using an asynchronous framework (such as Gevent or Twisted), your application will require only one [.api]`Bucket` instance per Couchbase bucket.
Likewise, if your Python application only contains a single thread then you need establish only a single [.api]`Bucket` object per Couchbase bucket.

If using multiple Python threads, it may be possible to share a single [.api]`Bucket` object across multiple threads (using locking).
The exact number of [.api]`Bucket` objects to be created will depend on the activity pattern of the application.
It is recommended to start off and develop with a single object for all threads.
If you realize that your application is suffering in performance because of threads waiting for the [.api]`Bucket` object's lock, you may implement a form of pooling or sharing so that _n_ number of buckets be available.

If using multiple processes (such as with the `multiprocessing` module), or using a Python module which creates multiple processes, ensure that the [.api]`Bucket` object is not created in the parent process!
Your Python interpreter may crash if the same [.api]`Bucket` object exists in more than a single process.

include::2.6@c-sdk::page$managing-connections.adoc[tag=group]
