= N1QL Queries Using the Python SDK with Couchbase Server
:navtitle: N1QL from the SDK
:page-aliases: n1ql-queries
:page-topic-type: concept

NOTE: See xref:n1ql-query.adoc[Couchbase Developer documentation for a quick intro to developing with N1QL]

== Simple Queries

To issue N1QL queries, you should create a [.api]`couchbase.n1ql.N1QLQuery` object, and pass it (as the [.param]`query` keyword argument) to the [.api]`n1ql_query()` method in the [.api]`Bucket` class.
Simple queries (that is, ones that are only strings and do not use placeholders) can be supplied directly to the [.api]`n1ql_query()` function, which will implicitly create the [.api]`N1QLQuery` object internally.

The return value from [.api]`n1ql_query()` is a [.api]`N1QLRequest` object.
Iterating over the object will yield the rows returned by the server for the given query (as a `dict`).
Each row represents a row received for the query.

.Simple N1QL Query
[source,python]
----
for row in bkt.n1ql_query('SELECT * FROM default'):
    print row
----

== Querying with Placeholders

You can use N1QL xref:n1ql-query.adoc#devguide-named-placeholders[placeholders] in the query.
Placeholders allow you to specify variable constraints for an otherwise constant query.
A named or positional parameter is a placeholder for a value in the WHERE, LIMIT or OFFSET clause of a query.
To use placeholders, manually construct an N1QLQuery object with the base query string, and simply use keyword and positional arguments for named or positional placeholders, respectively:

.Named Placeholders
[source,python]
----
from couchbase.n1ql import N1QLQuery
# ...
q = N1QLQuery('SELECT fname, lname, age FROM default WHERE age > $age', age=22)
for row in bkt.n1ql_query(q):
print row  # {'age': .., 'lname': ..., 'fname': ...}
----

.Positional Placeholders
[source,python]
----
q = N1QLQuery('SELECT fname, lname, age FROM default WHERE fname LIKE $1 or lname LIKE $2',
              '%ty%', '%thon%')
----

== Options

You may configure the [.api]`N1QLQuery` object with various options to control query behavior.
You may set the [.param]`query.adhoc` parameter to `False` to make use of xref:n1ql-query.adoc#prepare-stmts[prepared queries]

[source,python]
----
query = N1QLQuery(query_string)
query.adhoc = False
----

and you can also set [.param]`query.consistency` to [.api]`couchbase.n1ql.CONSISTENCY_REQUEST` to employ the xref:n1ql-query.adoc#consistency[_read-your-own-writes_] consistency mechanism.

[source,python]
----
from couchbase.n1ql import CONSISTENCY_REQUEST
query.consistency = CONSISTENCY_REQUEST
----

For queries which are expected to run for a long time, you may set the timeout on a per-query basis using the [.param]`query.timeout` parameter:

[source,python]
----
query.timeout = 300  # 5 minutes
----

== No-result queries

As a convenience for queries which are not intended to yield multiple rows, you may use the returned [.api]`N1QLRequest` object's [.api]`execute()` method.
For queries which are intended to return only a single result, you can use the [.api]`get_single_result()` method.
Both of the aforementioned methods are wrappers that iterate over the object internally and are intended to provide additional clarity inside your application's code.

[source,python]
----
bkt.n1ql_query("CREATE PRIMARY INDEX ON default").execute()
----

== Index Creation

In order to query a bucket, it must have an index defined.
You can create indexes using raw N1QL statements (e.g.
xref:6.0@server:n1ql:n1ql-language-reference/createindex.adoc[CREATE INDEX]) or via the Python SDK's xref:managing-clusters.adoc[cluster management interface]
