= Extended Attributes
:page-aliases: concept-docs:sdk-xattr-overview

[abstract]
Couchbase Server permits the definition of _extended attributes_.
These allow application developers to define application-specific metadata that will only be visible to those applications that request it or attempt to modify it.
This might be, for example, meta-data specific to a programming framework that should be hidden by default from other frameworks, or possibly from other versions of the same framework.

include::6.0@sdk:shared:partial$sdk-xattr-overview.adoc[tag=using_extended_attributes]

== Language-Specific Variations

Each language supported by the Couchbase SDK implements extended-attribute support in a slightly different way.
For Python examples, see xref:sdk-xattr-example.adoc[Sample Code].

For detailed information on the Subdocument API, see xref:subdocument-operations.adoc[Subdocument Operations].

== Virtual Extended Attributes

_Virtual_ extended attributes consist of metadata on an individual document: this can be retrieved by specifying `$document` as a search-path.
For example:

[source,python]
----
import couchbase.subdocument as SD
frag = bucket.lookup_in("test", SD.get("$document", xattr=True))
----

See xref:6.0@server:learn:data/extended-attributes-fundamentals.adoc#virtual-extended-attributes[the Virtual XATTR Section] for more information on the metadata that they expose.

These attributes are generated on-demand to expose storage-level document metadata, such as TTL to expose document expiration.
For TTL using Virtual XATTR, use the following:

[source,go]
----
import couchbase.subdocument as SD
frag = bucket.lookup_in("test",SD.get("$document.exptime", xattr=True))
----

See the xref:sdk-xattr-example.adoc#virtual-extended-attributes-example[example page] for a complete code sample.