= Install and Start Using the Python SDK with Couchbase Server
:navtitle: Start Using the SDK

[abstract]
The Couchbase Python SDK allows Python applications to access a Couchbase cluster.
The Python SDK offers a traditional synchronous API as well as integration with _twisted_, _gevent_, and _asyncio_.
It depends on the C SDK, libcouchbase, which it uses for performance and reliability.

First, install libcouchbase following the instructions here: https://developer.couchbase.com/server/other-products/release-notes-archives/c-sdk.

When libcouchbase is installed, please follow these instructions:

== Installing on Linux


.Debian and Ubuntu
[source,bash]
----
# Only needed during first-time setup:
sudo apt-get install build-essential python-dev python-pip
sudo pip install couchbase
----

.RHEL and CentOS
[source,bash]
----

# Only needed during first-time setup:
sudo yum install gcc gcc-c++ python-devel python-pip
sudo pip install couchbase
----

NOTE: RHEL/CentOS distributions may not provide the `python-pip` package in the base repositories.
It may be found in the https://fedoraproject.org/wiki/EPEL[EPEL^] repository.

== Installation on Mac OS X

To install the library on Mac OS X, first install the de-facto package manager for OS X: http://brew.sh/[homebrew^].
Once _homebrew_ is configured:

[source,bash]
----
brew update # get list of latest packages
brew install python
pip install couchbase
----

NOTE: The above example uses the Python supplied by homebrew and not the vendor-supplied Python which ships with OS X.
The Python SDK will still work with the vendor-supplied Python (though _pip install_ may be a privileged command), but it is recommended to use Homebrew's Python instead.

== Installing on Microsoft Windows

The Couchbase Python SDK is available as an executable installer for Windows.
This contains all the required dependencies, including C SDK development files.

. Check your Windows architecture (32-bit or 64-bit) and make sure the required version of Python is installed.
. Download the Couchbase Python SDK installer for your platform and Python version from https://pypi.python.org/pypi/couchbase#files[^].
. Run the installer and follow any instructions given.

NOTE: Installation by means of pip will _not_ work on Windows.

== Hello Couchbase

The code snippet below shows how the Python SDK may be used for some common operations.

[source,python]
----
include::{examplesdir}/hello_world_t.py[tag=intro]
----

== Connecting

To connect to a Couchbase bucket, you must use Couchbase _Role-Based Access Control_ (RBAC).
This is fully described in the section xref:6.0@server:security:security-authorization.adoc[Authorization].
An _authenticator_, containing username and password, should be defined, and then passed to the cluster.
Following successful authentication, the bucket can be opened.

[source,python]
----
include::{examplesdir}/hello_world_t.py[tag=connecting]
----

Once defined, the authenticator can be passed to other clusters, as appropriate.

See xref:managing-connections.adoc[Managing Connections Using the Python SDK with Couchbase Server] for more connection options and details about the connection string.

== Document Operations

xref:core-operations.adoc[Document operations], such as storing and retrieving documents, can be done using simple methods on the [.api]`Bucket` class such as [.api]`Bucket.get` and [.api]`Bucket.upsert`.
Simply pass the key (and value, if applicable) to the relevant methods.

[source,python]
----
include::{examplesdir}/hello_world_t.py[tag=docopsget]
----

[source,python]
----
include::{examplesdir}/hello_world_t.py[tag=docopsupsert]
----

== N1QL Queries

Couchbase N1QL queries are performed by creating a [.api]`N1QLQuery` object and passing that to the [.api]`Bucket.n1ql_query()` method:

[source,python]
----
include::{examplesdir}/hello_world_t.py[tag=n1l]
----

== API Reference

The API reference is generated for each release and can be found linked from the xref:relnotes-python-sdk.adoc[release notes for your version of the Python SDK].
Most of the API documentation can also be accessed via `pydoc`.

== Release Notes

Information on new features, fixes, known issues as well as information on how to install older release versions is xref:relnotes-python-sdk.adoc[in the release notes].

== PyPy support

Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.

An unofficial module, https://github.com/couchbaselabs/couchbase-python-cffi[couchbase_ffi^] uses ffi rather than the CPython C API to implement the internals of the library, and may be used with pypy.

[#python-contributing]
== Contributing

Couchbase welcomes community contributions to the Python SDK.
The https://github.com/couchbase/couchbase-python-client[Python SDK source code^] is available on GitHub.
