= Wrapping Up

[abstract]
The tutorial presents an easy approach to start a web application with Couchbase Server as the underlying data source.

If you want to dig a little bit deeper, https://github.com/couchbaselabs/beersample-python[the full source code in the couchbaselabs repository on GitHub^] has more code to learn from.
This code might be extended and updated from time to time.

Of course, this is only the starting point for Couchbase, but together with the Getting Started Guide, you should now be well equipped to start exploring Couchbase Server on your own.
Have fun working with Couchbase!

[#food-for-thought]
== Food For Thought

Some things are not implemented in the example.
Here's some ideas for features you might add while learning to use the SDK:

* When deleting a brewery, ensure it has no beers dependent on it.
* Provide a search where one can query beers belonging to a given brewery.
* Handle concurrent updates to a beer and/or brewery.
* Implement a _like_ feature, where one can like a beer or a brewery; likewise, they can unlike one as well!
