= Analytics using the SDK
:navtitle: Analytics using the SDK
:page-topic-type: howto
:page-aliases: analytics-query
:page-edition: Enterprise Edition
:lang: Python
:version: 3.0.0
:example-source: 3.0@python-sdk:howtos:example$analytics.py
:example-source-lang: Python

[abstract]
Parallel data management for complex queries over many records, using a familiar N1QL-like syntax.

For complex and long-running queries, involving large ad hoc join, set, aggregation, and grouping operations, the Couchbase Data Platform offers the xref:6.5@server:analytics:introduction.adoc[Couchbase Analytics Service (CBAS)].
This is the analytic counterpart to our xref:n1ql-queries-with-sdk.adoc[operational data focussed Query Service].
The analytics service is available in Couchbase Data Platform 6.0 and later.

== Getting Started

After familiarizing yourself with our xref:6.5@server:analytics:primer-beer.adoc[introductory primer],
in particular creating a dataset and linking it to a bucket, try Couchbase Analytics using the Python SDK.
Intentionally, the API for analytics is nearly identical to that of the query service.

Before starting, here's all imports used in the following examples:

[source,py]
----
include::example$analytics.py[tag=imports,indent=0]
----

Here's a complete example of doing an analytics query and handling the results:

[source,py]
----
include::example$analytics.py[tag=simple,indent=0]
----

Let's break it down. An analytics query is always performed at the `Cluster` level, using the `analyticsQuery` method. It takes the statement as a required argument and then allows to provide additional options if needed (in the example above, no options are specified).

Once a result returns you can iterate over the returned rows.

////
//// TODO: fix once https://issues.couchbase.com/browse/PYCBC-977 resolved
and/or access the `AnalyticsMetaData` associated with the query.
////

If something goes wrong during the execution of the query, a derivative of the `CouchbaseException` will be thrown that also provides additional context on the operation.

////
TODO: update

[source,py]
----
Exception in thread "main" com.couchbase.client.core.error.ParsingFailureException: Parsing of the input failed {"completed":true,"coreId":1,"errors":[{"code":24000,"message":"Syntax error: In line 1 >>select 1=;<< Encountered \"=\" at column 9. "}], ... }
----
////


[NOTE]
.Open Buckets and Cluster-Level Queries
====
If you are using a cluster older than Couchbase Server 6.5, it is required that there is at least one bucket open before performing a cluster-level query. If you fail to do so, the SDK will return a `FeatureNotAvailableException` with a descriptive error message asking you to open one.
====

== Parameterized Queries
Supplying parameters as individual arguments to the query allows the analytics engine to optimize the parsing and planning of the query. You can either supply these parameters by name or by position.

The first example shows how to provide them by name:

[source,py]
----
include::example$analytics.py[tag=named,indent=0]
----

The second example by position:

[source,py]
----
include::example$analytics.py[tag=positional,indent=0]
----

What style you choose is up to you, for readability in more complex queries we generally recommend using the named parameters.

Note that you cannot use parameters in all positions. If you put it in an unsupported place the server will respond with a `ParsingFailureException`.

== The Analytics Result

When performing an analytics query, the response you receive is an `AnalyticsResult`. If no exception gets raised the request succeeded and provides access to both the rows returned and also associated `AnalyticsMetaData`.

Rows can be consumed directly, or via a serialiser.

[source,py]
----
include::example$analytics.py[tag=rowsasobject,indent=0]
----



////

TODO: fix once https://issues.couchbase.com/browse/PYCBC-977 resolved
The `AnalyticsMetaData` provides insight into some basic profiling/timing information as well as information like the `clientContextId`.

.AnalyticsMetaData
[options="header"]
|====
| Name       | Description
| `request_id() -> str` | Returns the request identifer of this request.
| `client_context_id() -> str` | Returns the context ID either generated by the SDK or supplied by the user.
| `status() -> AnalyticsStatus` | An enum simply representing the state of the result.
| `metrics() -> AnalyticsMetrics` | Returns metrics provided by analytics for the request.
| `signature() -> JSON` | If a signature is present, it will be available to consume in a generic fashion.
| `warnings() -> Iterable[AnalyticsWarning]` | Non-fatal errors are available to consume as warnings on this method.
|====

For example, here is how you can print the `executionTime` of a query:

[source,py]
----
include::example$analytics.py[tag=printmetrics,indent=0]
----
////


== Analytics Options
The analytics service provides an array of options to customize your query. The following table lists them all:

.Available Analytics Options
[options="header"]
|====
| Name       | Description
| `client_context_id: str` | Sets a context ID returned by the service for debugging purposes.
| `positional_parameters: Iterable[str]` | Allows to set positional arguments for a parameterized query.
| `named_parameters: Dict[str,str]` | Allows to set named arguments for a parameterized query.
| `priority: bool` | Assigns a different server-side priority to the query.
| `raw: Dict[str, Any]` | Escape hatch to add arguments that are not covered by these options.
| `read_only: bool` | Tells the client and server that this query is readonly.
|====


////
//// TODO: uncomment pending https://issues.couchbase.com/browse/PYCBC-976
| `scan_consistency: AnalyticsScanConsistency` | Sets a different scan consistency for this query.
|====

TODO: uncomment pending https://issues.couchbase.com/browse/PYCBC-976
=== Scan Consistency

By default, the analytics engine will return whatever is currently in the index at the time of query (this mode is also called `AnalyticsScanConsistency.NOT_BOUNDED`). If you need to include everything that has just been written, a different scan consistency must be chosen. If `AnalyticsScanConsistency.REQUEST_PLUS` is chosen, it will likely take a bit longer to return the results but the analytics engine will make sure that it is as up-to-date as possible.

[source,py]
----
include::example$analytics.py[tag=scanconsistency,indent=0]
----
////



=== Client Context Id

The SDK will always send a client context ID with each query, even if none is provided by the user. By default a UUID will be generated that is mirrored back from the analytics engine and can be used for debugging purposes. A custom string can always be provided if you want to introduce application-specific semantics into it (so that for example in a network dump it shows up with a certain identifier). Whatever is chosen, we recommend making sure it is unique so different queries can be distinguished during debugging or monitoring.

[source,py]
----
include::example$analytics.py[tag=clientcontextid,indent=0]
----


=== Priority

By default, every analytics query has the same priority on the server. By setting this boolean flag to true, you are indicating that you need expedited dispatch in the analytice engine for this request.

[source,py]
----
include::example$analytics.py[tag=priority,indent=0]
----


=== Readonly

If the query is marked as readonly, both the server and the SDK can improve processing of the operation. On the client side, the SDK can be more liberal with retries because it can be sure that there are no state-mutating side-effects happening. The query engine will ensure that actually no data is mutated when parsing and planning the query.

[source,py]
----
include::example$analytics.py[tag=readonly,indent=0]
----

=== Custom JSON Serializer

Like with all JSON apis, it is possible to customize the JSON serializer. It allows to plug in your own library. This in turn makes it possible to serialize rows into PODs or other structures that your application defines and the SDK has no idea about.

Please see the documentation transcoding and serialization for more information.
