= Collecting Information & Logging
:description: Logging with the Python SDK.
:page-topic-type: howto
:navtitle: Collecting Information
:page-aliases: logging
:page-aliases: event-bus-metrics,logging

include::project-docs:partial$attributes.adoc[]

[abstract]

{description}

The Python SDK allows logging via the standard `logging` module.

== Enabling Logging

From version 4.0.2 of the Python SDK onwards, logging is configured with `configure_logging()` -- as in this example, _below_ -- and not through the environmental variable.

.Python Logging Module
[source,python]
----
include::example$logging_example.py[tag=logging,indent=0]
----

<.> In Python SDK versions 4.0.0 and 4.0.1, `configure_logging()` is not implemented and logging must be set with an environmental variable, as follows: 
+
.GNU/Linux and Mac
[source,console]
----
export PYCBC_LOG_LEVEL=<log-level>
----
+
.Windows
[source,console]
----
set PYCBC_LOG_LEVEL=<log-level>
----
+
Where `<log-level>` is either `error`, `warn`, `info`, or `debug`.


== Log Levels

You can increase the log level for greater verbosity (more information) in the logs:

* off -- disables all logging, which is normally set by default.
* critical -- important functionality not working.
* error -- error messages.
* warn -- error notifications.
* info -- useful notices, not often.
* debug -- diagnostic information, required to investigate problems.


== Log Redaction

Redacting logs is a two-stage process.
If you want to redact client logs (for example before handing them off to the Couchbase Support team) you first need to enable log redaction in your application.
This is done through the https://docs.couchbase.com/sdk-api/couchbase-python-client/couchbase_api/options.html#clusteroptions[`ClusterOptions`], setting `log_redaction` to `True`.

Once the SDK writes the logs with the tags to a file, you can then use the
xref:{version-server}@server:cli:cbcli/cblogredaction.adoc[`cblogredaction` tool] to obfuscate the log.

* You may wish to read more on Log Redaction
xref:{version-server}@server:manage:manage-logging/manage-logging.adoc#understanding_redaction[in the Server docs].



// TODO: link to LCB 3 logging docs when available

// -- see guide xref:3.0@c-sdk:howtos:collecting-information-and-logging.adoc[here].
