= Logging
:description: Logging with the Python SDK.
:page-topic-type: howto
:page-aliases: logging
:page-aliases: event-bus-metrics,logging

[abstract]

{description}

The Python SDK allows logging via the standard `logging` module.

== Enabling Logging

.Python Logging Module
[source,python]
----
include::devguide:example$python/logging_example.py[tag=logging,indent=0]
----

=== Environmental Settings

IMPORTANT: Only one logger can be created.  Either use `PYCBC_LOG_LEVEL` to create a console logger or `configure_logging` as mentioned above.

In the command line environment, the `PYCBC_LOG_LEVEL` variable is set as follows:

.GNU/Linux and Mac
[source,console]
----
export PYCBC_LOG_LEVEL=<log-level>
----

.Windows
[source,console]
----
set PYCBC_LOG_LEVEL=<log-level>
----

Version 4.3.3 of the SDK introduces the `PYCBC_LOG_FILE` variable that can be used in conjunction with `PYCBC_LOG_LEVEL`.
Set `PYCBC_LOG_FILE` to a filename in order to have the log output to a file (instead of stdout).

In the command line environment, the `PYCBC_LOG_FILE` variable is set as follows:

.GNU/Linux and Mac
[source,console]
----
export PYCBC_LOG_FILE=<filename>
----

.Windows
[source,console]
----
set PYCBC_LOG_FILE=<filename>
----

== Log Levels

You can increase the log level for greater verbosity (more information) in the logs:

* off -- disables all logging, which is normally set by default.
* critical -- important functionality not working.
* error -- error messages.
* warn -- error notifications.
* info -- useful notices, not often.
* debug -- diagnostic information, minimum level required to investigate problems.
* trace -- detailed diagnostic information, often required to investigate problems.


== Log Redaction

Redacting logs is a two-stage process.
If you want to redact client logs (for example before handing them off to the Couchbase Support team) you first need to enable log redaction in your application.
This is done through the https://docs.couchbase.com/sdk-api/couchbase-python-client/couchbase_api/options.html#clusteroptions[`ClusterOptions`], setting `log_redaction` to `True`.

Once the SDK writes the logs with the tags to a file, you can then use the
xref:{version-server}@server:cli:cbcli/cblogredaction.adoc[`cblogredaction` tool] to obfuscate the log.

* You may wish to read more on Log Redaction
xref:{version-server}@server:manage:manage-logging/manage-logging.adoc#understanding_redaction[in the Server docs].



// TODO: link to LCB 3 logging docs when available
// -- see guide xref:3.0@c-sdk:howtos:collecting-information-and-logging.adoc[here].

// If still relevant, should now be {cpp}




== SDK Telemetry from the Server

In addition to Tracing and other metrics, and client logging, SDK telemetry is also sent to the Server -- available from 8.0, and in new Capella Operational clusters -- for ingestion with other Prometheus metrics.
Capella Operational exposes these metrics through the UI.

For self-managed Server, collection can be disabled and enabled through the REST API:

[source,console]
----
curl --user Administrator:password http://172.17.0.2:8091/settings/appTelemetry -d enabled=true
----

And the Prometheus-format metrics fetched with:

[source,console]
----
curl --user Administrator:password http://172.17.0.2:8091/metrics
----

Further details can be found in the xref:{version-server}@server:rest-api:application-telemetry.adoc[] page.

There may be advantages to collecting information this way,
but note that metrics are collected per node,
and a central Prometheus instance should be set to collect all metrics so that information is not lost in case of a sudden failover.

Also note that if the cluster is behind a load balancer, the collected metrics may not accurately record the actual correct node with which the SDK interacts.
