= Choosing an API
:description: The Couchbase Python SDK offers both asyncio and Twisted APIs for async operation.
:navtitle: Choosing an API
:page-topic-type: howto
:page-aliases: ROOT:async-programming,ROOT:batching-operations,multiple-apis,ROOT:asynchronous-frameworks

[abstract]
{description}


== Asyncio

To use the Python SDK with https://docs.python.org/3/library/asyncio.html[asyncio], use the _acouchbase_ module. 
As opposed to the synchronous SDK methods which wait for completion and return `Result` objects, the _acouchbase_ methods return a `Future`. 
You may `await` the success or failure of the `Future`.  
If a `Future` is awaited, the method awaiting the task must have the `async` keyword in its signature. 
`Result` objects are obtained after `await`ing the `Future` as seen in the examples below.

.Create an _acouchbase_ Cluster
[source,python]
----
include::howtos:example$acouchbase_operations.py[tag=create]
----

=== Asyncio Document (KV) Operations

Key-value and sub-document operations return `Future` objects which can then be used for `await` clauses. 
The `Future`’s result will always be the relevant `Result` object for the operation performed.

.KV - Operations
[source,python]
----
include::howtos:example$acouchbase_operations.py[tag=kv]
----

.Sub-document Operations
[source,python]
----
include::howtos:example$acouchbase_operations.py[tag=sub_doc]
----

=== Asyncio N1QL Operations

The API for issuing N1QL queries is almost identical to the synchronous API. 
The notable difference is the use of `async for` rather than `for` when iterating over the results.

.N1QL Query
[source,python]
----
include::howtos:example$acouchbase_operations.py[tag=n1ql]
----

=== Asyncio Search Operations

The API for issuing full text search queries is almost identical to the synchronous API. 
The notable difference is the use of `async for` rather than `for` when iterating over the results.

.Search Query
[source,python]
----
include::howtos:example$acouchbase_operations.py[tag=search]
----

=== Asyncio Analytics Operations

The API for issuing analytics queries is almost identical to the synchronous API. 
The notable difference is the use of `async for` rather than `for` when iterating over the results.

.Analytics Query
[source,python]
----
include::howtos:example$acouchbase_operations.py[tag=analytics]
----


== Twisted

To use the Python SDK with the https://twistedmatrix.com/trac/["Twisted"] framework, use the _txcouchbase_ module. 
As opposed to the synchronous SDK methods which wait for completion and return `Result` objects, the _txcouchbase_ methods return a Twisted `Deferred`. 
You may configure `Deferred` with callback and errback handlers. 
`Result` objects are propagated to the callback as seen in the examples below.

IMPORTANT: The txcouchbase package _must_ be imported prior to importing the Twisted reactor.

._txcouchbase_ imports
[source,python]
----
include::howtos:example$txcouchbase_operations.py[tag=txcouchbase_imports]
----

.Create a _txcouchbase_ Cluster
[source,python]
----
include::howtos:example$txcouchbase_operations.py[tag=create]
----

=== Twisted Document (KV) Operations

Key-value and sub-document operations return `Deferred` objects which can then be configured with callback and errback handlers. 
The `Deferred`’s result will always be the relevant `Result` object for the operation performed.

.KV - Operations
[source,python]
----
include::howtos:example$txcouchbase_operations.py[tag=kv]
----

.Sub-document Operations
[source,python]
----
include::howtos:example$txcouchbase_operations.py[tag=sub_doc]
----

=== Twisted N1QL Operations

The API for issuing N1QL queries is almost identical to the synchronous API. 
The notable difference is the use of a callback in order to handle iterating over results.

.N1QL Query
[source,python]
----
include::howtos:example$txcouchbase_operations.py[tag=n1ql]
----

=== Twisted Search Operations

The API for issuing full text search queries is almost identical to the synchronous API. 
The notable difference is the use of a callback in order to handle iterating over results.

.Search Query
[source,python]
----
include::howtos:example$txcouchbase_operations.py[tag=search]
----

=== Twisted Analytics Operations

The API for issuing analytics queries is almost identical to the synchronous API. 
The notable difference is the use of a callback in order to handle iterating over results.

.Analytics Query
[source,python]
----
include::howtos:example$txcouchbase_operations.py[tag=analytics]
----
