= Full Text Search using the SDK
:description: You can use the Full Text Search service (FTS) to create queryable full-text indexes in Couchbase Server.
:navtitle: Full Text Search using the SDK
:page-topic-type: howto
:page-aliases: search-query
:lang: Python
:version: 3.2.0
:example-source: 3.2@python-sdk:howtos:example$search_ops.py
:example-source-lang: Python


[abstract]
{description}


Full Text Search or FTS allows you to create, manage and query full text indexes on JSON documents stored in Couchbase buckets.
It uses natural language processing for indexing and querying documents, provides relevance scoring on the results of your queries and has fast indexes for querying a wide range of possible text searches.

Some of the supported query-types include simple queries like Match and Term queries, range queries like Date Range and Numeric Range and compound queries for conjunctions, disjunctions and/or boolean queries.

== Getting Started

After familiarizing yourself with how to create and query a Search index in the UI you can query it from the SDK. 
Intentionally the API itself is very similar to the query and analytics ones, the main difference being that you cannot cast the resulting rows into a domain object directly but rather get a `SearchRow` returned. 
The reason for this is that a search row ("hit") has more metadata associated with it than you potentially want to look at.

[source,python]
----
include::howtos:example$search_ops.py[tag=search_basic_example]
----

NOTE: When using a Couchbase version < 6.5 you must create a valid Bucket connection using `cluster.bucket(name)` before you can use Analytics.

Let's break it down. 
A Search query is always performed at the `Cluster` level, using the `search_query` method. 
It takes the name of the index and the type of query  as required arguments and then allows to provide additional options if needed 
(in the example above, no options are specified).

Once a result returns you can iterate over the returned rows, and/or access the `SearchMetaData` associated with the query. 


== Search Queries

The second mandatory argument in the example above used `QueryStringQuery("query")` to specify the query to run against the search index.
The query string is the simplest form, but there are many more available. 
The table below lists all of them with a short description of each. 
You can combine them with `conjuncts` and `disjuncts` respectively.
`Location` objects are specified as a `Tuple[SupportsFloat,SupportsFloat]` of longitude and latitude respectively.

.Available Search Queries
[options="header"]
|====
| Name       | Description
| `QueryStringQuery(query: str)` | Accept query strings, which express query-requirements in a special syntax.
| `MatchQuery(match: str)` | A match query analyzes input text, and uses the results to query an index.
| `MatchPhraseQuery(match_phrase: str)` | The input text is analyzed, and a phrase query is built with the terms resulting from the analysis.
| `PrefixQuery(prefix: str)` | A prefix query finds documents containing terms that start with the specified prefix.
| `RegexQuery(regexp: str)` | A regexp query finds documents containing terms that match the specified regular expression.
| `TermRangeQuery()` | A term range query finds documents containing a term in the specified field within the specified range.
| `NumericRangeQuery()` | A numeric range query finds documents containing a numeric value in the specified field within the specified range.
| `DateRangeQuery()` | A date range query finds documents containing a date value, in the specified field within the specified range.
| `DisjunctionQuery(*queries: SearchQuery)` | A disjunction query contains multiple child queries. Its result documents must satisfy a configurable min number of child queries.
| `ConjunctionQuery(*queries: SearchQuery)` | A conjunction query contains multiple child queries. Its result documents must satisfy all of the child queries.
| `WildcardQuery(wildcard: str)` | A wildcard query uses a wildcard expression, to search within individual terms for matches.
| `DocIdQuery(*ids: str)` | A doc ID query returns the indexed document or documents among the specified set.
| `BooleanFieldQuery(value: bool)` | A boolean field query searches fields that contain boolean true or false values.
| `TermQuery(term: str)` | Performs an exact match in the index for the provided term.
| `PhraseQuery(*terms: str)` | A phrase query searches for terms occurring in the specified position and offsets.
| `MatchAllQuery()` | Matches all documents in an index, irrespective of terms.
| `MatchNoneQuery()` | Matches no documents in the index.
| `GeoBoundingBoxQuery(top_left: Location, bottom_right: Location)` | Searches inside the given bounding box coordinates.
| `GeoDistanceQuery(distance: str, location: Location )` | Searches inside the distance from the given location coordinate.
|====

== The Search Result

Once the Search query is executed successfully, the server starts sending back the resultant hits.

[source,python]
----
include::howtos:example$search_ops.py[tag=search_result]
----

The `SearchRow` contains the following methods:

.SearchRow
[options="header"]
|====
| `index -> str` | The name of the FTS index that gave this result.
| `id -> str` | The id of the matching document.
| `score ->float` | The score of this hit.
| `explanation -> str` | If enabled provides an explanation in JSON form.
| `locations -> SearchRowLocations` | The individual locations of the hits.
| `fragments -> Optional[Mapping[str, str]]` | The fragments for each field that was requested as highlighted.
| `fields -> Dict[str, Any]` | Access to the returned fields.
|====

Note that the `SearchMetaData` also contains potential `errors`, because the SDK will keep streaming results if the initial response came back successfully. 
This makes sure that even with partial data usually Search results are useable,
so if you absolutely need to check if all partitions are present in the result double check the error 
(and not only catch an exception on the query itself).

== Search Options

The `cluster.search_query` function provides an array of named parameters to customize your query via `**kwargs` or `SearchOptions`. The following table lists them all:

.Available Search Options
[options="header"]
|====
| Name       | Description
| `limit: int` | Allows to limit the number of hits returned.
| `skip: int` | Allows to skip the first N hits of the results returned.
| `explain: bool` | Adds additional explain debug information to the result.
| `scan_consistency: SearchScanConsistency` | Specifies a different consistency level for the result hits.
| `consistent_with: MutationState` | Allows to be consistent with previously performed mutations.
| `highlight_style: HighlightStyle` | Specifies highlighting rules for matched fields.
| `highlight_fields: List[str]` | Specifies fields to highlight.
| `sort: List[str]` | Allows to provide custom sorting rules.
| `facets: Map[str, SearchFacet]` | Allows to fetch facets in addition to the regular hits.
| `fields: List[str]` | Specifies fields to be included.
| `raw: JSON` | Escape hatch to add arguments that are not covered by these options.
| `collections: List[str]` | Limits the search query to a specific list of collection names.
|====

=== Limit and Skip

It is possible to limit the returned results to a maximum amount using the `limit` option. 
If you want to skip the first N records it can be done with the `skip` option.

[source,python]
----
include::howtos:example$search_ops.py[tag=limit_and_skip]
----

=== ScanConsistency and ConsistentWith

By default, all Search queries will return the data from whatever is in the index at the time of query. 
These semantics can be tuned if needed so that the hits returned include the most recently performed mutations, at the cost of slightly higher latency since the index needs to be updated first.

There are two ways to control consistency: either by supplying a custom `SearchScanConsistency` or using `consistentWith`.
At the moment the cluster only supports `consistentWith`, which is why you only see `SearchScanConsistency.NOT_BOUNDED` in the enum which is the default setting. 
The way to make sure that recently written documents show up in the rfc works as follows (commonly referred to "read your own writes" -- RYOW):

.Scan consistency example:
[source,python]
----
include::howtos:example$search_ops.py[tag=scan_consistency]
----

.ConsistentWith consistency example:
[source,python]
----
include::howtos:example$search_ops.py[tag=ryow]
----

=== Highlight

It is possible to enable highlighting for matched fields. 
You can either rely on the default highlighting style or provide a specific one. 
The following snippet uses HTML formatting for two fields:

[source,python]
----
include::howtos:example$search_ops.py[tag=highlight]
----

=== Sort

By default the Search Engine will sort the results in descending order by score. 
This behavior can be modified by providing a different sorting order which can also be nested.

// TODO: When PYCBC-1144 is complete, add another example showing how to use sort w/ provided objects.

[source,python]
----
include::howtos:example$search_ops.py[tag=sort]
----

Facets are aggregate information collected on a result set and are useful when it comes to categorization of result data. 
The SDK allows you to provide many different facet configurations to the Search Engine, the following example shows how to create a facet based on a term. 
Other possible facets include numeric and date ranges.

=== Facets

[source,python]
----
include::howtos:example$search_ops.py[tag=facets]
----

=== Fields

You can tell the Search Engine to include the full content of a certain number of indexed fields in the response.

[source,python]
----
include::howtos:example$search_ops.py[tag=fields]
----

=== Collections

It is now possible to limit the search query to a specific list of collection names.

Note that this feature is only supported with Couchbase Server 7.0 or later.

[source,python]
----
include::howtos:example$search_ops.py[tag=collections]
----

////
TODO:  can provide once transcoders/serializers are available w/in SDK
=== Custom JSON Serializer

As with all JSON APIs, it is possible to customize the JSON serializer. 
You can plug in your own library (like GSON) or custom configure mappings on your own Jackson serializer. 
This in turn makes it possible to serialize rows into POJOs or other structures that your application defines, and which the SDK has no idea about.

Please see the xref:transcoders-nonjson.adoc[documentation on transcoding and serialization] for more information.

////

== Async APIs

In addition to the blocking API on `Cluster`, the SDK provides asyncio and Twisted APIs on `ACluster` or `TxCluster` respectively.
If you are in doubt of which API to use, we recommend looking at the asyncio API first.

Simple queries with both asyncio and Twisted APIs look similar to the blocking one:

.ACouchbase
[source,python]
----
include::howtos:example$acouchbase_search_ops.py[tag=simple_query]
----

.TxCouchbase
[source,python]
----
include::howtos:example$txcouchbase_search_ops.py[tag=simple_query]
----


