= Key Value Operations
:navtitle: KV Operations
:page-topic-type: howto
:page-aliases: ROOT:document-operations,ROOT:crud

[WARNING]
====
These pages cover the Alpha of the Couchbase Python SDK. 
As such they are likely to change without notice. 
This alpha code should not be used in production.

Documentation is incomplete, subject to change, and likely to contain broken links.
====

The complete code sample used on this page can be downloaded from link:https://github.com/couchbase/docs-sdk-python/tree/3.0dp1/modules/hello-world/examples/kv_operations.py[the GitHub repo for the Python docs], from which you can see in context how to authenticate and connect to a Couchbase Cluster, then perform these Bucket operations.

// Type hints!
// Type hints!
// Type hints!
// Type hints!
// Type hints!
//
//    :-)

== Documents

A _document_ refers to an entry in the database (other databases may refer to the same concept as a _row_).
A document has an ID (_primary key_ in other databases), which is unique to the document and by which it can be located.
The document also has a value which contains the actual application data.
See xref::concept-docs:documents.adoc[the concept guide to _Documents_] for a deeper dive into documents in the Couchbase Data Platform.
Or read on, for a hands-on introduction to working with documents from the Python SDK.

== CRUD Operations

The core interface to Couchbase Server is simple KV operations on full documents.
Make sure you're familiar with the basics of authorization and connecting to a Cluster from the xref:hello-world:start-using-sdk.adoc[Start Using the SDK section].
We're going to expand on the short _Upsert_ example we used there, adding options as we move through the various CRUD operations.
Here is the _Insert_ operation at its simplest:

.Insert
[source,python]
----
include::example$kv_operations.py[tag=insert]
----

Options may be added to operations:

.Insert (with options)
[source,python]
----
include::example$kv_operations.py[tag=insert_w_options]
----

Setting a Compare and Swap (CAS) value is a form of optimistic locking -- dealt with in depth in the xref:concurrent-document-mutations.adoc[CAS page].
Here we just note that the CAS is a value representing the current state of an item; each time the item is modified, its CAS changes.
The CAS value is returned as part of a document's metadata whenever a document is accessed.
Without explicitly setting it, a newly-created document would have a CAS value of _0_.

.Replace
[source,python]
----
include::example$kv_operations.py[tag=replace]
----

Expiration sets an explicit time to live (TTL) for a document, for which you can also xref:sdk-xattr-example.adoc[see a more detailed example of TTL discovery] later in the docs.
We'll discuss modifying `Expiration` in more details xref:#net-modifying-expiration[below].
For a discussion of item (Document) _vs_ Bucket expiration, see the
xref:6.5@server:learn:buckets-memory-and-storage/expiration.adoc#expiration-bucket-versus-item[Expiration Overview page].

[source,python]
----
include::example$kv_operations.py[tag=expiration]
----

Here, we have added _Durability_ options, namely `PersistTo` and `ReplicateTo`.
In Couchbase Server releases before 6.5, Durability was set with these two options -- see the xref:2.5@python-sdk::durability.adoc[6.0 Durability documentation] -- covering how many replicas the operation must be propagated to and how many persisted copies of the modified record must exist.
Couchbase Data Platform 6.5 refines these two options, with xref:concept-docs:durability-replication-failure-considerations.adoc[Synchronous Replication].

The following example demonstrates using the newer durability features available in Couchbase server 6.5 onwards.

[source,python]
----
include::example$kv_operations.py[tag=upsert_syncrep]
----

[TIP]
.Sub-Document Operations
====
All of these operations involve fetching the complete document from the Cluster.
Where the number of operations or other circumstances make bandwidth a significant issue, the SDK can work on just a specific _path_ of the document with xref:subdocument-operations.adoc[Sub-Docunent Operations].
====

== Retrieving full documents

Using the `Get()` method with the document key can be done in a similar fashion to the other operations:

[source,python]
----
include::example$kv_operations.py[tag=get]
----


== Removing

When removing a document, you will have the same concern for durability as with any additive modification to the Bucket:

Remove (with options)
[source,python]
----
include::example$kv_operations.py[tag=remove_old_durability]
----

== Expiration / TTL

By default, Couchbase documents do not expire, but transient or temporary data may be needed for user sessions, caches, or other temporary documents.
Using `Touch()`, you can set expiration values on documents to handle transient data:

[source,python]
----
include::example$kv_operations.py[tag=touch]
----

== Atomic document modifications

The value of a document can be increased or decreased atomically using `.increment()` and `.decrement()`.

.Increment
[source,python]
----
include::example$kv_operations.py[tag=increment]
----

.Increment (with options)
[source,python]
----
include::example$kv_operations.py[tag=increment_w_expiration]
----

.Decrement
[source,python]
----
include::example$kv_operations.py[tag=decrement]
----

.Increment (with options)
[source,python]
----
include::example$kv_operations.py[tag=decrement_w_expiration]
----

NOTE: Increment & Decrement are considered part of the ‘binary’ API, and as such may still be subject to change.

== Additional Resources

Working on just a specific path within a JSON document will reduce network bandwidth requirements - see the xref:subdocument-operations.adoc[Sub-Document] pages.
// For working with metadata on a document, reference our xref:sdk-xattr-example.adoc[Extended Attributes] pages.

// Another way of increasing network performance is to _pipeline_ operations with xref:batching-operations.adoc[Batching Operations].

// As well as various xref:concept-docs:data-model.adoc[Formats] of JSON, Couchbase can work directly with xref:non-json.adoc[arbitary bytes, or binary format].

Our xref:n1ql-queries-with-sdk.adoc[Query Engine] enables retrieval of information using the SQL-like syntax of N1QL.
