= Managing Connections using the Python SDK with Couchbase Server
:description: This section describes how to connect the Python SDK to a Couchbase cluster.
:navtitle: Managing Connections
:page-topic-type: concept
:page-aliases: ROOT:managing-connections,howtos:multi-network,ROOT:connecting,ROOT:connection-advanced

include::project-docs:partial$attributes.adoc[]

Please also refer to the xref:{version-server}@server:learn:security/authorization-overview.adoc[Server docs].

[abstract]
{description}
It contains best practices as well as information on TLS/SSL and other advanced connection options.

== Connecting to a Cluster

A connection to a Couchbase Server cluster is represented by a `Cluster` object.
A `Cluster` provides access to Buckets, Scopes, and Collections, as well as various Couchbase services and management interfaces.
The simplest way to create a `Cluster` object is to call `Cluster.connect()` with a <<connection-strings, connection string>>, username, and password:

[source,python]
----
include::example$managing_connections.py[tag=simpleconnect,indent=0]
----

NOTE: If you are connecting to a version of Couchbase Server older than 6.5, it will be more efficient if the addresses are those of data (KV) nodes.
You will in any case, with 6.0 and earlier, need to open a ``Bucket` instance before connecting to any other HTTP services (such as _Query_ or _Search_).

In a production environment, your connection string should include the addresses of multiple server nodes in case some are currently unavailable.
Multiple addresses may be specified in a connection string by delimiting them with commas:

[source,python]
----
include::example$managing_connections.py[tag=multinodeconnect,indent=0]
----

TIP: You don't need to include the address of every node in the cluster.
The client fetches the full address list from the first node it is able to contact.

////
N/A for Python currently
[#cluster-settings]
== Cluster Settings

A `ClusterEnvironment` manages shared resources like thread pools, timers, and schedulers.
It also holds the client settings.
One way to customize the client's behavior is to build your own `ClusterEnvironment` with custom settings:

[source,python]
----
include::example$managing_connections.py[tag=customenv,indent=0]
----
////

[#connection-strings]
== Connection Strings

A Couchbase connection string is a comma-delimited list of IP addresses and/or hostnames, optionally followed by a list of parameters.

The parameter list is just like the query component of a URI; name-value pairs have an equals sign (`=`) separating the name and value, with an ampersand (`&`) between each pair.
Just as in a URI, the first parameter is prefixed by a question mark (`?`).

.Simple connection string with one seed node
----
couchbase://127.0.0.1
----

.Connection string with two seed nodes
----
couchbase://nodeA.example.com,nodeB.example.com
----

.Connection string with two parameters
----
couchbases://127.0.0.1?compression=on&redaction=on
----

The full list of recognized parameters is documented in the client settings reference.
Any client setting with a system property name may also be specified as a connection string parameter.

A connection string may optionally be prefixed by either `"couchbase://"` or `"couchbases://"`.

For more detailed documentation please refer to the xref:c-sdk:howtos:managing-connections.adoc[libcouchbase connection string documentation].
// TODO: update this when the LCB 3.x connstr docs are up



////

== Waiting for Bootstrap Completion

Depending on the environment and network latency, bootstrapping the SDK fully might take a little longer than the default key-value timeout of 2.5 seconds, so you may see timeouts during bootstrap.
To prevent those early timeouts from happening, you can use the `waitUntilReady` method.

If you are working at the _Cluster_ level, then add to the `cluster()` in the xref:#connecting-to-a-cluster[earlier example]:

[source,java]
----
Cluster cluster = Cluster.connect("127.0.0.1", "username", "password");
cluster.waitUntilReady(Duration.ofSeconds(10));
Bucket bucket = cluster.bucket("travel-sample");
Collection collection = bucket.defaultCollection();
----

Or more fully:

[source,java]
----
public class ClusterExample {
  public static void main(String... args) throws Exception {
    Cluster cluster = Cluster.connect("127.0.0.1", "username", "password");
    cluster.waitUntilReady(Duration.ofSeconds(10));
    Bucket bucket = cluster.bucket("travel-sample");
    Collection collection = bucket.defaultCollection();
  }
}
----

If you are working at the _Bucket_ level, then the https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/Bucket.html#waitUntilReady-java.time.Duration-[Bucket-level `waitUntilReady`] does the same as the Cluster-level version,
_plus_ it waits for the K-V (data) sockets to be ready.

// Other timeout issues may occur when using the SDK located geographically separately from the Couchbase Server cluster -- this is xref:project-docs:compatibility#[not recommended].
// See the xref:#working-in-the-cloud[Cloud section] below for some suggestions of settings adjustments.



////


[#connection-lifecycle]
== Connection Lifecycle

Most of the high-level classes in the Python SDK are designed to be safe for concurrent use by multiple threads.
For asynchronous modes, you will get the best performance if you share and reuse instances of `Cluster`, `Bucket`, `Scope`, and `Collection`, all of which are thread-safe. For synchronous mode, it is better to use separate instances in different threads.

We recommend creating a single `Cluster` instance when your application starts up, and sharing this instance throughout your application.
If you know at startup time which buckets, scopes, and collections your application will use, we recommend obtaining them from the `Cluster` at startup time and sharing those instances throughout your application as well.

////
I believe PYCBC does this automatically when the Client object is destroyed, but we are apparently offering this explicitly in future.
Before your application stops, gracefully shut down the client by calling the `disconnect()` method of each `Cluster` you created.
If you created any `ClusterEnvironment` instances, call their `shutdown()` method after disconnecting the associated clusters.
////

// not available from PYCBC/LCB yet AFAIK
////
[#multiple-clusters]
== Connecting to Multiple Clusters

If a single application needs to connect to multiple Couchbase Server clusters, we recommend creating a single `ClusterEnvironment` and sharing it between the `Clusters`:
[source,python]
----
include::example$managing_connections.py[tag=shareclusterenvironment,indent=0]
----

When you manually create a `ClusterEnvironment` like this, the SDK will not shut it down when you call `Cluster.disconnect()`.
Instead you are responsible for shutting it down after disconnecting all clusters that share the environment.

TIP: If you create a `Cluster` without specifying a custom environment, the client creates a default environment used exclusively by that `Cluster`.
This default `ClusterEnvironment` is managed completely by the Python SDK, and is automatically shut down when the associated `Cluster` is disconnected.
////

[#alternate-addresses]
== Alternate Addresses and Custom Ports

If your Couchbase Server cluster is running in a containerized, port mapped, or otherwise NAT'd environment like Docker or Kubernetes, a client running outside that environment may need additional information in order to connect the cluster.
Both the client and server require special configuration in this case.

On the server side, each server node must be configured to advertise its external address as well as any custom port mapping.
This is done with the `setting-alternate-address` CLI command introduced in Couchbase Server 6.5.
A node configured in this way will advertise two addresses: one for connecting from the same network, and another for connecting from an external network.
// todo link to https://docs.couchbase.com/server/6.5/cli/cbcli/couchbase-cli-setting-alternate-address.html
////

On the client side, the externally visible ports must be used when connecting.
If the external ports are not the default, you can specify custom ports using the overloaded `Cluster.connect()` method that takes a set of `SeedNode` objects instead of a connection string.

// todo use the include (and uncomment in ManageingConnections.python) after next client snapshot is published
// include::example$managing_connections.py[tag=seednodes,indent=0]
[source,python]
----
int customKvPort = 1234;
int customManagerPort = 2345;
Set<SeedNode> seedNodes = new HashSet<>(Arrays.asList(
  SeedNode.create("127.0.0.1",
      Optional.of(customKvPort),
      Optional.of(customManagerPort))));

Cluster cluster = Cluster.connect(seedNodes, "username", "password");
----
TIP: In a deployment that uses multi-dimensional scaling, a custom KV port is only applicable for nodes running the KV service.
A custom manager port may be specified regardless of which services are running on the node.

In many cases the client is able to automatically select the correct set of addresses to use when connecting to a cluster that advertises multiple addresses.
If the detection heuristic fails in your environment, you can override it by setting the `io.networkResolution` client setting to `default` if the client and server are on the same network, or `external` if they're on different networks.
////

NOTE: Any TLS certificates must be set up at the point where the connections are being made.
// todo what does that mean in practice? Also, should this be in the TLS docs section instead?


[#ssl]
== Secure Connections

WARNING: If the client cannot load or was not built with OpenSSL, attempting an SSL connection will result in a 'FEATURE_UNAVAILABLE'.

Couchbase Server Enterprise Edition supports full encryption of client-side traffic using Transport Layer Security (TLS).
That includes key-value type operations, queries, and configuration communication.
Make sure you have the Enterprise Edition of Couchbase Server before proceeding with configuring encryption on the client side.

To configure encryption for the Python SDK:

. Get the CA certificate from the cluster and save it in a text file.
. Enable encryption on the client side and point it to the file containing the certificate.

It is important to make sure you are transferring the certificate in an encrypted manner from the server to the client side, so either copy it through SSH or through a similar secure mechanism.

If you are running on `localhost` and just want to enable TLS for a development machine, just copying and pasting it suffices
-- _so long as you use `127.0.0.1` rather than `localhost` in the connection string_.
This is because the certificate will not match the name _localhost_.
Setting `TLSSkipVerify` is a workaround if you need to use ` couchbases://localhost`.

Navigate in the admin UI to menu:Settings[Cluster] and copy the input box of the TLS certificate into a file on your machine (which we will refer to as `cluster.crt`).
It looks similar to this:

----
-----BEGIN CERTIFICATE-----
MIICmDCCAYKgAwIBAgIIE4FSjsc3nyIwCwYJKoZIhvcNAQEFMAwxCjAIBgNVBAMT
ASowHhcNMTMwMTAxMDAwMDAwWhcNNDkxMjMxMjM1OTU5WjAMMQowCAYDVQQDEwEq
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzz2I3Gi1XcOCNRVYwY5R
................................................................
mgDnQI8nw2arBRoseLpF6WNw22CawxHVOlMceQaGOW9gqKNBN948EvJJ55Dhl7qG
BQp8sR0J6BsSc86jItQtK9eQWRg62+/XsgVCmDjrB5owHPz+vZPYhsMWixVhLjPJ
mkzeUUj/kschgQ0BWT+N+pyKAFFafjwFYtD0e5NwFUUBfsOyQtYV9xu3fw+T2N8S
itfGtmmlEfaplVGzGPaG0Eyr53g5g2BgQbi5l5Tt2awqhd22WOVbCalABd9t2IoI
F4+FjEqAEIr1mQepDaNM0gEfVcgd2SzGhC3yhYFBAH//8W4DUot5ciEhoBs=
-----END CERTIFICATE-----
----

The next step is to enable encryption by connecting to a cluster with the 'couchbases://' protocol in the connection string and pass it the path to the certificate file via an Authenticator, or via '?cert_path=...' in the connection string itself.

[source,python]
----
include::example$managing_connections.py[tag=tls,indent=0]
----

Then use this custom `Cluster` when opening the connection to the cluster.

If you want to verify it's actually working, you can use a tool like [.cmd]`tcpdump`.
For example, an unencrypted upsert request looks like this (using `sudo tcpdump -i lo0 -A -s 0 port 11210`):

----
E..e..@.@.............+......q{...#..Y.....
.E...Ey........9........................id{"key":"value"}
----

After enabling encryption, you cannot inspect the traffic in cleartext (same upsert request, but watched on port 11207 which is the default encrypted port):

----
E.....@.@.............+....Z.'yZ..#........
..... ...xuG.O=.#.........?.Q)8..D...S.W.4.-#....@7...^.Gk.4.t..C+......6..)}......N..m..o.3...d.,.	...W.....U..
.%v.....4....m*...A.2I.1.&.*,6+..#..#.5
----

////
TODO: verify
include::{version-server}@sdk:shared:partial$dnssrv-pars.adoc[tag=dnssrv]

DNS SRV bootstrapping is available in the Python SDK from version 2.5.
In order to make the SDK actually use the SRV records, you need to enable DNS SRV on the environment and pass in the host name from your records (here `example.com`):

[source,python]
----
include::example$managing_connections.py[tag=dnssrv,indent=0]
----

If the DNS SRV records could not be loaded properly you'll get the exception logged and the given host name will be used as a A record lookup.

----
WARNING: DNS SRV lookup failed, proceeding with normal bootstrap.
pythonx.naming.NameNotFoundException: DNS name not found [response code 3];
   remaining name '_couchbase._tcp.example.com'
	at com.sun.jndi.dns.DnsClient.checkResponseCode(DnsClient.python:651)
	at com.sun.jndi.dns.DnsClient.isMatchResponse(DnsClient.python:569)
----

Also, if you pass in more than one node, DNS SRV bootstrap will not be initiated:

----
INFO: DNS SRV enabled, but less or more than one seed node given.
Proceeding with normal bootstrap.
----
////

include::{version-server}@sdk:shared:partial$managing-connections.adoc[tag=cloud]


== Async APIs

The Couchbase Python SDK provides first-class support for asynchronous programming. 
The supported asynchronous APIs offer a similar API to the synchronous API.

Methods in the asynchronous API return instances of the relevant Async API:

1. `Future` for asyncio (`acouchbase.cluster.Cluster` supplies the relevant Cluster object)
2. `Deferred` for Twisted

Reference our xref:concurrent-async-apis.adoc[asynchronous programming] page for more details.

////
TODO: write up pending https://issues.couchbase.com/browse/PYCBC-805 etc

So if you are connecting to the bucket synchronously but then want to switch over to asynchronous data operations, you can do it like this:

[source,python]
----
include::example$managing_connections.py[tag=blockingtoasync,indent=0]
----

On the other hand, you can use the Async API right from the beginning:
// todo use tabs here?
[source,python]
----
include::example$managing_connections.py[tag=asynccluster,indent=0]
----

Here's the same example, but using the Reactive API instead of the Async API:

[source,python]
----
include::example$managing_connections.py[tag=reactivecluster,indent=0]
----
////
