= Managing Connections
:description: This section describes how to connect the {name-sdk} to a Couchbase cluster.
:page-toclevels: 2
:page-aliases: ROOT:managing-connections.adoc,howtos:multi-network.adoc,ROOT:connecting.adoc,ROOT:connection-advanced.adoc

// Please also refer to the xref:{version-server}@server:learn:security/authorization-overview.adoc[Server docs].

[abstract]
{description}
It contains best practices as well as information on TLS/SSL and advanced connection options, and a sub-page on troubleshooting Cloud connections.


== Connecting to a Cluster

A connection to a Couchbase Server cluster is represented by a `Cluster` object.
A `Cluster` provides access to Buckets, Scopes, and Collections, as well as various Couchbase services and management interfaces.
The simplest way to create a `Cluster` object is to call `Cluster.connect()` with a <<connection-strings, connection string>>, username, and password:

[tabs,sync-group-id="Couchbase Capella|Self-Managed Couchbase Server"]
==== 
Couchbase Capella::
+
--
[source,python]
----
include::devguide:example$python/cloud.py[tags=connect,indent=0]
----

Note, the client certificate for connecting to a Capella cluster is included in the SDK installation.
--

Self-Managed Couchbase Server::
+ 
-- 
[source,python]
----
include::devguide:example$python/hello_world_t.py[tags="connect",indent=0]
----
--
====

In a production environment, your connection string should include the addresses of multiple server nodes in case some are currently unavailable.
Multiple addresses may be specified in a connection string by delimiting them with commas:

[source,python]
----
include::devguide:example$python/managing_connections.py[tag=multinodeconnect,indent=0]
----

TIP: You don't need to include the address of every node in the cluster.
The client fetches the full address list from the first node it is able to contact.



=== Waiting for Bootstrap Completion

Opening resources is asynchronous.
That is, the call to `cluster.bucket` or `Cluster.connect` will complete instantly, and opening that resource will continue in the background.


include::{version-common}@sdk:shared:partial$managing-connections.adoc[tag=bootstrap-completion]


Other timeout issues may occur when using the SDK located geographically separately from the Couchbase Server cluster -- 
this is xref:project-docs:compatibility.adoc#network-requirements[not recommended in production deployments], but often occurs during development.
See the <<working-in-the-cloud,Cloud section>> below for some suggestions of settings adjustments.



=== Connection Strings

A Couchbase connection string is a comma-delimited list of IP addresses and/or hostnames, optionally followed by a list of parameters.

The parameter list is just like the query component of a URI; name-value pairs have an equals sign (`=`) separating the name and value, with an ampersand (`&`) between each pair.
Just as in a URI, the first parameter is prefixed by a question mark (`?`).

.Simple connection string with one seed node
----
couchbase://127.0.0.1
----

.Connection string with two seed nodes
----
couchbase://nodeA.example.com,nodeB.example.com
----

.Connection string with two parameters
----
couchbases://127.0.0.1?compression=on&redaction=on
----

The full list of recognized parameters is documented in the client settings reference.
Any client setting with a system property name may also be specified as a connection string parameter.

A connection string may optionally be prefixed by either `"couchbase://"` or `"couchbases://"`,
the latter signifying a TLS connection.


=== Connection Options

xref:ref:client-settings.adoc#cluster-options[Configuring client settings with `ClusterOptions()`] is the preferred option for configuring connection parameters.
More details can be found in the https://docs.couchbase.com/sdk-api/couchbase-python-client/couchbase_api/options.html#cluster[API reference].


=== Connection Lifecycle

Most of the high-level classes in the Python SDK are designed to be safe for concurrent use by multiple threads.
For asynchronous modes, you will get the best performance if you share and reuse instances of `Cluster`, `Bucket`, `Scope`, and `Collection`, all of which are thread-safe.
For synchronous mode, it is better to use separate instances in different threads.

We recommend creating a single `Cluster` instance when your application starts up, and sharing this instance throughout your application.
If you know at startup time which buckets, scopes, and collections your application will use, we recommend obtaining them from the `Cluster` at startup time and sharing those instances throughout your application as well.




[#ssl]
== Secure Connections

Both Couchbase Capella, and the
xref:{version-server}@server:introduction:editions.adoc#enterprise-edition[Enterprise Edition] of self-managed Couchbase Server,
 support full encryption of client-side traffic using Transport Layer Security (TLS).
That includes data (key-value type) operations, queries, and configuration communication.
Make sure you have the Enterprise Edition of Couchbase Server, or a Couchbase Capella account, before proceeding with configuring encryption on the client side.


WARNING: If the client cannot load or was not built with OpenSSL, attempting a TLS connection will result in a 'FEATURE_UNAVAILABLE'.


For TLS certificate verification the SDK uses the following CA certificates:

* The certificates in the Mozilla Root CA bundle (bundled with the SDK as of 4.1.5 and obtained from https://curl.se/docs/caextract.html[curl]).
* The certificates in OpenSSL's default CA certificate store.
* The self-signed root certificate that is used to sign the Couchbase Capella certificates.

The OpenSSL defaults can be overridden using the `SSL_CERT_DIR` and `SSL_CERT_FILE` environment variables. 
The `SSL_CERT_DIR` variable is used to set a specific directory in which the client should look for individual certificate files, whereas the `SSL_CERT_FILE` environment variable is used to point to a single file containing one or more certificates. 
More information can be found in the relevant https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_load_verify_locations.html[OpenSSL documentation].

Loading the Mozilla certificates can be disabled by setting the `disable_mozilla_ca_certificates` property of `ClusterOptions`.

Metadata from the Python SDK’s {cpp} core provides information about where OpenSSL’s default certificate store is located, which version of the Mozilla CA certificate store was bundled, and other useful details.
You can get the metadata using the following command:

====
[source,console]
----
$ python3 -c "from couchbase import get_metadata; print(get_metadata(detailed=True))"
----
[source,console]
----
{
 ...
 'mozilla_ca_bundle_date': 'Tue Jan 10 04:12:06 2023 GMT',
 'mozilla_ca_bundle_embedded': True,
 'mozilla_ca_bundle_sha256': 'fb1ecd641d0a02c01bc9036d513cb658bbda62a75e246bedbc01764560a639f0',
 'mozilla_ca_bundle_size': 137,
 ...
 'openssl_default_cert_dir': '/opt/homebrew/etc/openssl@1.1/certs',
 'openssl_default_cert_dir_env': 'SSL_CERT_DIR',
 'openssl_default_cert_file': '/opt/homebrew/etc/openssl@1.1/cert.pem',
 'openssl_default_cert_file_env': 'SSL_CERT_FILE',
 ...
}
----
====

With debug-level logging enabled, if the Mozilla certificates have been loaded, a message with the information about the version of the Mozilla CA certificate store will be outputted. 
For example:

[source,console]
----
loading 137 CA certificates from Mozilla bundle. Update date: "Tue Jan 10 04:12:06 2023 GMT", SHA256: "fb1ecd641d0a02c01bc9036d513cb658bbda62a75e246bedbc01764560a639f0"
----

[{tabs}]
====
Couchbase Capella::
+
--
The Python SDK bundles Capella’s standard root certificate by default.
This means you don’t need any additional configuration to enable TLS -- simply use `couchbases://` in your connection string.

NOTE: Capella's root certificate is *not* signed by a well known CA (Certificate Authority).
However, as the certificate is bundled with the SDK, it is trusted by default.
--

Couchbase Server::
+
--
Certificates from the Mozilla Root CA store are now bundled with the SDK (as of version 4.1.5). 
If the server's certificate is signed by a well-known CA (e.g., GoDaddy, Verisign, etc.), you don't need to configure the `cert_path` property in the `PasswordAuthenticator` -- simply use `couchbases://` in your connection string.

You can still provide a certificate explicitly if necessary:

. Get the CA certificate from the cluster and save it in a text file.
. Enable encryption on the client side and point it to the file containing the certificate.

It is important to make sure you are transferring the certificate in an encrypted manner from the server to the client side, so either copy it through SSH or through a similar secure mechanism.

If you are running on `localhost` and just want to enable TLS for a development machine, just copying and pasting it suffices
-- _so long as you use `127.0.0.1` rather than `localhost` in the connection string_.
This is because the certificate will not match the name _localhost_.

// TODO: Not entirely sure this is correct, needs to be verified.
//Setting `TLSSkipVerify` is a workaround if you need to use `couchbases://localhost`.

Navigate in the admin UI to menu:Settings[Cluster] and copy the input box of the TLS certificate into a file on your machine (which we will refer to as `cluster.crt`).
It looks similar to this:

----
-----BEGIN CERTIFICATE-----
MIICmDCCAYKgAwIBAgIIE4FSjsc3nyIwCwYJKoZIhvcNAQEFMAwxCjAIBgNVBAMT
ASowHhcNMTMwMTAxMDAwMDAwWhcNNDkxMjMxMjM1OTU5WjAMMQowCAYDVQQDEwEq
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzz2I3Gi1XcOCNRVYwY5R
................................................................
mgDnQI8nw2arBRoseLpF6WNw22CawxHVOlMceQaGOW9gqKNBN948EvJJ55Dhl7qG
BQp8sR0J6BsSc86jItQtK9eQWRg62+/XsgVCmDjrB5owHPz+vZPYhsMWixVhLjPJ
mkzeUUj/kschgQ0BWT+N+pyKAFFafjwFYtD0e5NwFUUBfsOyQtYV9xu3fw+T2N8S
itfGtmmlEfaplVGzGPaG0Eyr53g5g2BgQbi5l5Tt2awqhd22WOVbCalABd9t2IoI
F4+FjEqAEIr1mQepDaNM0gEfVcgd2SzGhC3yhYFBAH//8W4DUot5ciEhoBs=
-----END CERTIFICATE-----
----

The next step is to enable encryption by connecting to a cluster with the 'couchbases://' protocol in the connection string and pass it the path to the certificate file via an Authenticator, or via '?cert_path=...' in the connection string itself.

[source,python]
----
include::devguide:example$python/managing_connections.py[tag=tls,indent=0]
----

Then use this custom `Cluster` when opening the connection to the cluster.

If you want to verify it's actually working, you can use a tool like [.cmd]`tcpdump`.
For example, an unencrypted upsert request looks like this (using `sudo tcpdump -i lo0 -A -s 0 port 11210`):

----
E..e..@.@.............+......q{...#..Y.....
.E...Ey........9........................id{"key":"value"}
----

After enabling encryption, you cannot inspect the traffic in cleartext (same upsert request, but watched on port 11207 which is the default encrypted port):

----
E.....@.@.............+....Z.'yZ..#........
..... ...xuG.O=.#.........?.Q)8..D...S.W.4.-#....@7...^.Gk.4.t..C+......6..)}......N..m..o.3...d.,.	...W.....U..
.%v.....4....m*...A.2I.1.&.*,6+..#..#.5
----
--
====






[#alternate-addresses]
== Alternate Addresses and Custom Ports

If your Couchbase Server cluster is running in a containerized, port mapped, or otherwise NAT'd environment like Docker or Kubernetes, a client running outside that environment may need additional information in order to connect the cluster.
Both the client and server require special configuration in this case.

On the server side, each server node must be configured to advertise its external address as well as any custom port mapping.
This is done with the `setting-alternate-address` CLI command --
see the xref:cli:cbcli/couchbase-cli-setting-alternate-address.adoc[command line docs].
A node configured in this way will advertise two addresses: one for connecting from the same network, and another for connecting from an external network.


On the client side, the externally visible ports must be used when connecting.
If the external ports are not the default, you can specify custom ports through the connection string.

[source,python]
----
int customKvPort = 1234;
int customManagerPort = 2345;
Set<SeedNode> seedNodes = new HashSet<>(Arrays.asList(
  SeedNode.create("127.0.0.1",
      Optional.of(customKvPort),
      Optional.of(customManagerPort))));

Cluster cluster = Cluster.connect(seedNodes, "username", "password");
----

////
For nodes that do not have the KV service, you can connect using a custom manager port instead.
Notice how `=manager` appears after the port number, identifying it as a manager port:

[source,java]
----
include::devguide:example$java/managing_connections.java[tag=managing_connections_6,indent=0]
----
////


TIP: In a deployment that uses multi-dimensional scaling, a custom KV port is only applicable for nodes running the KV service.
A custom manager port may be specified regardless of which services are running on the node.

In many cases the client is able to automatically select the correct set of addresses to use when connecting to a cluster that advertises multiple addresses.
If the detection heuristic fails in your environment, you can override it by setting the `io.networkResolution` client setting to `default` if the client and server are on the same network, or `external` if they're on different networks.

NOTE: Any TLS certificates must be set up at the point where the connections are being made.
// todo what does that mean in practice? Also, should this be in the TLS docs section instead?





// DNS-SRV
// == Using DNS SRV records

include::{version-common}@sdk:shared:partial$dnssrv-pars.adoc[tag=dnssrv-rev]

DNS SRV bootstrapping is enabled by default in the {name-sdk}.
In order to make the SDK use the SRV records, you need to pass in the hostname from your records (here `example.com`):

////
TODO: verify
include::{version-common}@sdk:shared:partial$dnssrv-pars.adoc[tag=dnssrv]

DNS SRV bootstrapping is available in the Python SDK from version 2.5.
In order to make the SDK actually use the SRV records, you need to enable DNS SRV on the environment and pass in the host name from your records (here `example.com`):

[source,python]
----
include::devguide:example$python/managing_connections.py[tag=dnssrv,indent=0]
----

If the DNS SRV records could not be loaded properly you'll get the exception logged and the given host name will be used as a A record lookup.

----
WARNING: DNS SRV lookup failed, proceeding with normal bootstrap.
pythonx.naming.NameNotFoundException: DNS name not found [response code 3];
   remaining name '_couchbase._tcp.example.com'
	at com.sun.jndi.dns.DnsClient.checkResponseCode(DnsClient.python:651)
	at com.sun.jndi.dns.DnsClient.isMatchResponse(DnsClient.python:569)
----

Also, if you pass in more than one node, DNS SRV bootstrap will not be initiated:

----
INFO: DNS SRV enabled, but less or more than one seed node given.
Proceeding with normal bootstrap.
----
////








////

== Cloud Native Gateway


Couchbase's next generation connection protocol, introduced in Scala SDK 1.5 and Couchbase Autonomous Operator 2.6.1, can be enabled simply by changing the connection string to `couchbase2://` but there are a few differences to be aware of, described <<#limitations,below>>.
// Couchbase's next generation connection protocol, introduced in Scala SDK 1.5 and Couchbase Autonomous Operator 2.6.1, can be enabled simply by changing the connection string to `couchbase2://` but there are a few differences to be aware of, described <<#limitations,below>>.

The protocol implements a gRPC-style interface between the SDK and Couchbase Server.
(Only available with Couchbase Server running on Kubernetes or OpenShift, with a recent release of xref:operator::overview.adoc[Couchbase Autonomous Operator]: 2.6.1 onwards).


=== Limitations

The underlying protocol will not work with certain legacy features: MapReduce Views (a deprecated Service -- 
use xref:howtos:sqlpp-queries-with-sdk.adoc[Query] instead) and 
Memcached buckets (superseded by the improved xref:{server_version}@server:learn:buckets-memory-and-storage/buckets.adoc#bucket-types[Ephemeral Buckets]).

The following are not currently implemented over the `couchbase2://` protocol:

* Authentication by client certificate.
* Multi-document ACID transactions.
* Analytics service.
* Health Check.

There are some different behaviors seen with this protocol:

* Some config options are unsupported -- see the xref:ref:client-settings.adoc#cloud-native-gateway[Settings page].
* The SDK will poll the gRPC channels until they are in a good state, or return an error, or timeout while waiting -- in our standard protocol there is an option of setting `waitUntilReady()` for just certain services to become available.
* Some error codes are more generic -- in cases where the client would not be expected to need to take specific action -- but should cause no problem, unless you have written code looking at individual strings within the error messages.
* Although documents continue to be stored compressed by Couchbase Server, they will not be transmitted in compressed form (to and from the client) over the wire, using `couchbase2://`.


////





// Working in the Cloud

include::{version-common}@sdk:shared:partial$managing-connections.adoc[tag=cloud]







== Async APIs

The Couchbase Python SDK provides first-class support for asynchronous programming. 
The supported asynchronous APIs offer a similar API to the synchronous API.

Methods in the asynchronous API return instances of the relevant Async API:

1. `Future` for asyncio (`acouchbase.cluster.Cluster` supplies the relevant Cluster object)
2. `Deferred` for Twisted

Reference our xref:concurrent-async-apis.adoc[asynchronous programming] page for more details.



== Next Steps

* xref:secure-connections.adoc[Certificate Authentication] 
