= Request Tracing
:description: Collecting information about an individual request and its response is an essential feature of every observability stack.
:page-toclevels: 2
:page-aliases: ROOT:tracing-from-the-sdk.adoc

[abstract]
{description}

To give insight into a request/response flow, the SDK provides a `RequestTracer` interface and ships with both a default implementation as well as modules that can be plugged into feed the traces to external systems (including OpenTelemetry).


== The Default ThresholdLoggingTracer

NOTE: As of v4.6.0 the Threshold Logger is native to the Python SDK.
In previous versions the underlying {cpp} core was responsible for all tracing related behaviour.

By default, the SDK will emit information about requests that are over a configurable threshold every 10 seconds. 
Note that if no requests are over the threshold no event / log will be emitted.

It is possible to customize this behavior by modifying the configuration:

[source,python]
----
include::devguide:example$python/threshold_logging.py[tag=threshold_logging_config]
----

In this case the emit interval is 5 seconds and Key/Value requests will only be considered if their latency is greater or equal than 500 milliseconds.

The JSON blob emitted looks similar to the following (prettified here for readability):

[source,json]
----
[
   {
      "top":[
         {
            "operation_name":"get",
            "server_us":2,
            "last_local_id":"E64FED2600000001/00000000EA6B514E",
            "last_local_address":"127.0.0.1:51807",
            "last_remote_address":"127.0.0.1:11210",
            "last_dispatch_us":2748,
            "last_operation_id":"0x9",
            "total_us":324653
         },
         {
            "operation_name":"get",
            "server_us":0,
            "last_local_id":"E64FED2600000001/00000000EA6B514E",
            "last_local_address":"127.0.0.1:51807",
            "last_remote_address":"127.0.0.1:11210",
            "last_dispatch_us":1916,
            "last_operation_id":"0x1b692",
            "total_us":2007
         }
      ],
      "service":"kv",
      "count":2
   }
]
----

For each service (e.g. Key/Value or Query) an entry exists in the outer JSON array. 
The top N (10 by default) slowest operations are collected and displayed, sorted by the total duration. 
This promotes quick visibility of the "worst offenders" and more efficient troubleshooting.

Please note that in future releases this format is planned to change for easier readability, 
so we do not provide any stability guarantees on the logging output format and it might change between minor versions.


== OpenTelemetry Integration

The built-in tracer is great if you do not have a centralized monitoring system, but if you already plug into the OpenTelemetry ecosystem we want to make sure to provide first-class support.

=== Exporting to OpenTelemetry

This method exports tracing telemetry in OpenTelemetry's standard format (OTLP), which can be sent to any OTLP-compatible receiver such as Jaeger, Zipkin, or `opentelemetry-collector`.

To do this, install the required Python libraries for OpenTelemetry:

NOTE: The Python SDK allows for the OpenTelemetry API and SDK packages to be installed along with the SDK via `python3 -m pip install couchbase[otel]`.

[source,console]
----
$ python3 -m pip install opentelemetry-api~=1.22, opentelemetry-sdk~=1.22
----

And now:

[source,python]
----
include::devguide:example$python/otel_otlp_tracing.py[tag=tracing-otel-jaeger,indent=0]
----

At this point the SDK will automatically be exporting spans, and you should see them in your receiver of choice.

Create file `docker-compose.yml`:
[source,yaml]
----
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "16686:16686" # Jaeger UI
----

Now start up Jaeger with OTLP support:
[source,console]
----
$ docker-compose up -d
----

Now run the application.
All being well, spans should display in Jaeger (the UI is available on http://localhost:16686) under the service that matches what was used for the `service.name` attribute in the application.

=== OpenTelemetry Troubleshooting

* There are many ways to export spans.  
The example is exporting OpenTelemetry Protocol (OTLP) spans over GRPC to port 4317, which we believe is the _de facto_ standard for OpenTelemetry.  
Make sure that your receiver is compatible with this, e.g. has these ports open and is ready to receive OTLP traffic over GRPC.  
With https://www.jaegertracing.io/docs/1.41/getting-started/[Jaeger in Docker] this is achieved with the options `-e COLLECTOR_OTLP_ENABLED=true` and `-p 4317:4317`.
* The exporter used in this example is `BatchSpanProcessor`, which may not have a chance to export spans if the application exits very quickly (e.g. a test application).  
`SimpleSpanProcessor` can be used instead, though is not likely suitable for production.
* The example above uses `sampler=ALWAYS_ON`, which exports every span.  
This may need to be reduced to avoid overwhelming the receiver, with e.g. `sampler=TraceIdRatioBased(0.01)` to sample 1% of all traces.
* It can be worth sending traces into https://opentelemetry.io/docs/collector/[OpenTelemetry Collector], and forwarding them on from there to your receiver of choice.  
Among other capabilities the collector can log traces it receives, making for easier debugging.

=== Parent spans

If you want to set a parent for a SDK request, you can do it in the respective `*Options`:

[source,python]
----
with app_tracer.start_as_current_span("operations") as parent_span:
    result = collection.get("my-doc", GetOptions(parent_span=parent_span))
----

