= Provisioning Cluster Resources
:description: Provisioning cluster resources is managed at the collection or bucket level, depending upon the service affected.
:navtitle: Provisioning Cluster Resources
:page-aliases: ROOT:managing-clusters

[abstract]
{description}
Common use cases are outlined here, more recherché use cases are covered in the https://docs.couchbase.com/sdk-api/couchbase-python-client/[API docs].

include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The Python SDK also comes with some convenience functionality for common Couchbase management requests.

Management operations in the SDK may be performed through several interfaces depending on the object:

* BucketManager -- `Cluster.Buckets()`
* UserManager -- `Cluster.Users()`
* QueryIndexManager -- `Cluster.QueryIndexes()`
* AnalyticsIndexManager -- `Cluster.AnalyticsIndexes()`
* SearchIndexManager -- `Cluster.SearchIndexes()`
* CollectionManager -- `Bucket.Collections()`
* ViewIndexManager -- `Bucket.ViewIndexes()`

NOTE: When using a Couchbase version earlier than 6.5, you must create a valid Bucket connection using `cluster.Bucket(name)` before you can use cluster level managers.


== Creating and Removing Buckets

The `BucketManager` interface may be used to create and delete buckets from the Couchbase cluster.
It is instantiated through the `Cluster.buckets()` method.

[source,python]
----
include::howtos:example$provisioning_resources_buckets.py[tag=create_bucket_mgr]
----

The `CreateBucketSettings` and `BucketSettings` classes are used for creating and updating buckets, `BucketSettings` is also used for exposing information about existing buckets.

include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

Here is the list of parameters available:

|====
| Name | Type | Description | Can be updated
| name | str | The name of the bucket, required for creation. | false
| flush_enabled | bool | Enables flushing to be performed on this bucket (see the <<python-flushing>> section below). | true
| replica_index | bool | Whether or not to replicate indexes. | false
| ram_quota_mb | int | How much memory should each node use for the bucket, required for creation. | true
| num_replicas | int | The number of replicas to use for the bucket. | true
| bucket_type | BucketType | The type of the bucket, required for creation. | false
| eviction_policy | EvictionPolicyType | The type of the eviction to use for the bucket, defaults to `valueOnly`. | true (note: changing will cause the bucket to restart causing temporary inaccessibility)
| max_ttl | timedelta | The default maximum time-to-live to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| compression_mode | CompressionMode | The compression mode to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| conflict_resolution_type | ConflictResolutionType | The conflict resolution type to apply to conflicts on the bucket, defaults to `seqno` | false
|====


The following example creates a "hello" bucket:

[source,python]
----
include::howtos:example$provisioning_resources_buckets.py[tag=create_bucket]
----

We can now get this bucket and update it to enable Flush:

[source,python]
----
include::howtos:example$provisioning_resources_buckets.py[tag=get_and_update_bucket]
----

Once you no longer need to use the bucket, you can remove it:

[source,python]
----
include::howtos:example$provisioning_resources_buckets.py[tag=drop_bucket]
----

[#python-flushing]
== Flushing Buckets

include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You can flush a bucket in the SDK by using the https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html#flushing-clearing-the-bucket[`flush_bucket()` method].

[source,python]
----
include::howtos:example$provisioning_resources_buckets.py[tag=flush_bucket]
----

The `flush_bucket()` operation may fail if the bucket does not have flush enabled, in that case it will return an `BucketNotFlushableException`.


== Collection Management

[.status]#Developer Preview#

The CollectionManager interface may be used to create and delete scopes and collections from the Couchbase cluster.
It is instantiated through the `Bucket.collections()` method.
Refer to the https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html[API documentation]
for further details.

[source,python]
----
include::howtos:example$provisioning_resources_collections.py[tag=create_collections_mgr]
----

You can create a scope:

[source,python]
----
include::howtos:example$provisioning_resources_collections.py[tag=create_scope]
----

You can then create a collection within that scope:

[source,python]
----
include::howtos:example$provisioning_resources_collections.py[tag=create_collection]
----

Finally, you can drop unneeded collections and scopes:

[source,python]
----
include::howtos:example$provisioning_resources_collections.py[tag=drop_collection]

include::howtos:example$provisioning_resources_collections.py[tag=drop_scope]
----

Note that the most minimal permissions to create and drop a Scope or Collections is
https://docs.couchbase.com/server/7.0/learn/security/roles.html#manage-collections-in-scope[Scope Admin]
along with
https://docs.couchbase.com/server/7.0/learn/security/roles.html#data-reader[Data Reader].

You can create users with the appropriate RBAC programmatically:

[source,python]
----
include::howtos:example$provisioning_resources_collections.py[tag=scopeAdmin]
----

== Index Management

In general,you will rarely need to work with Index Managers from the SDK.
For those occasions when you do, please see the relevant API docs:

* QueryIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html#n1ql-index-management[`Cluster.QueryIndexes()`];
* AnalyticsIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html[`Cluster.AnalyticsIndexes()`];
* SearchIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html[`Cluster.SearchIndexes()`];
* ViewIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html[`Bucket.ViewIndexes()`].


// * Query

// * Search - note & link to FTS page & API?

== View Management

include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

In the SDK, design documents are represented by the `DesignDocument` and `View` classes.
All operations on design documents are performed on the `ViewIndexManager` instance:


[source,python]
----
include::howtos:example$provisioning_resources_views.py[tag=create_view_mgr]
----

The following example upserts a design document with two views:

[source,python]
----
include::howtos:example$provisioning_resources_views.py[tag=create_view]
----

include::6.5@sdk:shared:partial$flush-info-pars.adoc[tag=one-view-update-warning]

Note the use of `DesignDocumentNamespace.DEVELOPMENT`, the other option is `DesignDocumentNamespace.PRODUCTION`.
This parameter specifies whether the design document should be created as development, or as production -- with the former running over only a small fraction of the documents.

Now that we've created a design document we can fetch it:

[source,python]
----
include::howtos:example$provisioning_resources_views.py[tag=get_view]
----

We've created the design document using `DesignDocumentNamespace.DEVELOPMENT` and now want to push it to production, we can do this with:

[source,python]
----
include::howtos:example$provisioning_resources_views.py[tag=publish_view]
----

To remove this design document:

[source,python]
----
include::howtos:example$provisioning_resources_views.py[tag=drop_view]
----
