= Provisioning Cluster Resources
:description: Provisioning cluster resources is managed at the collection or bucket level, depending upon the service affected.
:page-aliases: ROOT:managing-clusters
:page-toclevels: 2

// API refs
:bucket-api-reference: pass:q[BucketManager -- https://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.0/couchbase_api/couchbase_core.html#couchbase.cluster.Cluster.buckets[`Cluster.buckets()`]]
:user-api-reference: pass:q[UserManager -- https://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.0/couchbase_api/couchbase_core.html#couchbase.cluster.Cluster.users[`Cluster.users()`]]
:query-api-reference: pass:q[QueryIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.0/couchbase_api/couchbase_core.html#couchbase.cluster.Cluster.query_indexes[`Cluster.query_indexes()`]]
:analytics-api-reference: pass:q[AnalyticsIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.0/couchbase_api/couchbase_core.html#couchbase.cluster.Cluster.query_indexes[`Cluster.analytics_ndexes()`]]
:search-api-reference: pass:q[SearchIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.0/couchbase_api/couchbase_core.html#couchbase.cluster.Cluster.query_indexes[`Cluster.search_indexes()`]]
:collection-api-reference: pass:q[CollectionManager -- https://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.0/couchbase_api/couchbase_core.html#couchbase.bucket.Bucket.collections[`Bucket.collections()`]]
:view-api-reference: pass:q[ ViewIndexManager -- https://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.0/couchbase_api/couchbase_core.html#couchbase.bucket.Bucket.collections[`Bucket.view_indexes()`]]

// one-view-update-warning common partial
:upsertDesignDocument: pass:q[`upsert_design_document` method]
:getDesignDocument: pass:q[`get_design_document`]

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}
Common use cases are outlined here, less common use cases are covered in the https://docs.couchbase.com/sdk-api/couchbase-python-client/[API docs].

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=management-intro]

The Python SDK also comes with some convenience functionality for common Couchbase management requests.

Management operations in the SDK may be performed through several interfaces depending on the object:

* {bucket-api-reference}
* {user-api-reference}
* {query-api-reference} 
* {analytics-api-reference}
* {search-api-reference}
* {collection-api-reference}
* {view-api-reference}

NOTE: When using a Couchbase version earlier than 6.5, you must create a valid Bucket connection using `Cluster.bucket(name)` before you can use cluster level managers.


== Bucket Management

The `BucketManager` interface may be used to create and delete buckets from the Couchbase cluster.
It is instantiated through the `Cluster.buckets()` method.

[source,python]
----
include::howtos:example$provisioning_resources_buckets.py[tag=create_bucket_mgr]
----

The `CreateBucketSettings` and `BucketSettings` classes are used for creating and updating buckets, `BucketSettings` is also used for exposing information about existing buckets.

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=update-bucket-warning]

Here is the list of parameters available:

|====
| Name | Type | Description | Can be updated
| name | str | The name of the bucket, required for creation. | false
| flush_enabled | bool | Enables flushing to be performed on this bucket (see the <<Flushing Buckets>> section below). | true
| replica_index | bool | Whether or not to replicate indexes. | false
| ram_quota_mb | int | How much memory should each node use for the bucket, required for creation. | true
| num_replicas | int | The number of replicas to use for the bucket. | true
| bucket_type | BucketType | The type of the bucket, required for creation. | false
| eviction_policy | EvictionPolicyType | The type of the eviction to use for the bucket, defaults to `valueOnly`. | true (note: changing will cause the bucket to restart causing temporary inaccessibility)
| max_ttl | timedelta | The default maximum time-to-live to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| compression_mode | CompressionMode | The compression mode to apply to documents in the bucket. (note: This option is only available for Couchbase and Ephemeral buckets in Couchbase Enterprise Edition.) | true
| conflict_resolution_type | ConflictResolutionType | The conflict resolution type to apply to conflicts on the bucket, defaults to `seqno` | false
|====


The following example creates a "hello" bucket:

[source,python]
----
include::howtos:example$provisioning_resources_buckets.py[tag=create_bucket]
----

We can now get this bucket and update it to enable Flush:

[source,python]
----
include::howtos:example$provisioning_resources_buckets.py[tag=get_and_update_bucket]
----

Once you no longer need to use the bucket, you can remove it:

[source,python]
----
include::howtos:example$provisioning_resources_buckets.py[tag=drop_bucket]
----

=== Flushing Buckets

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=flush-intro]

You can flush a bucket in the SDK by using the https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html#flushing-clearing-the-bucket[`flush_bucket()` method].

[source,python]
----
include::howtos:example$provisioning_resources_buckets.py[tag=flush_bucket]
----

The `flush_bucket()` operation may fail if the bucket does not have flush enabled, in that case it will return an `BucketNotFlushableException`.


== Collection Management

The CollectionManager interface may be used to create and delete scopes and collections from the Couchbase cluster.
It is instantiated through the `Bucket.collections()` method.
Refer to the https://docs.couchbase.com/sdk-api/couchbase-python-client/api/couchbase.html[API documentation]
for further details.

[source,python]
----
include::howtos:example$provisioning_resources_collections.py[tag=create_collections_mgr]
----

You can create a scope:

[source,python]
----
include::howtos:example$provisioning_resources_collections.py[tag=create_scope]
----

You can then create a collection within that scope:

[source,python]
----
include::howtos:example$provisioning_resources_collections.py[tag=create_collection]
----

Finally, you can drop unneeded collections and scopes:

[source,python]
----
include::howtos:example$provisioning_resources_collections.py[tag=drop_collection]

include::howtos:example$provisioning_resources_collections.py[tag=drop_scope]
----

Note that the most minimal permissions to create and drop a Scope or Collection is
xref:server:learn:security/roles.adoc#manage-scopes[Manage Scopes]
along with xref:server:learn:security/roles.adoc#data-reader[Data Reader].

You can create users with the appropriate RBAC programmatically:

[source,python]
----
include::howtos:example$provisioning_resources_collections.py[tag=scopeAdmin]
----

You can enumerate Scopes and Collections using
the `CollectionManager.get_all_scopes()` method and
the `Scope.collections` property.

[source,python]
----
include::howtos:example$provisioning_resources_collections.py[tag=listing-scope-collection]
----

== Index Management

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=index-management-intro]

=== QueryIndexManager

The `QueryIndexManager` interface contains the means for managing indexes used for queries.
It can be instantiated through the `Cluster.query_indexes()` method.

[source,python]
----
include::howtos:example$query_index_manager.py[tag=creating-index-mgr,indent=0]
----

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=query-index-manager-intro]

The example below shows how to create a simple primary index, restricted to a named scope and collection, by calling the `create_primary_index()` method.
Note that you cannot provide a named scope or collection separately, both must be set for the `QueryIndexManager` to create an index on the relevant keyspace path. 

.Creating a primary index

[source,python]
----
include::howtos:example$query_index_manager.py[tag=primary,indent=0]
----

When a primary index name is not specified, the SDK will create the index as `#primary` by default.
However, if you wish to provide a custom name, you can simply set a `index_name` property in the `CreatePrimaryQueryIndexOptions` class.

You may have noticed that the example also sets the `ignore_if_exists` boolean flag. 
When set to `True`, this optional argument ensures that an error is not thrown if an index under the same name already exists.

Creating a _secondary_ index follows a similar approach, with some minor differences:

.Creating a secondary index

[source,python]
----
include::howtos:example$query_index_manager.py[tag=secondary,indent=0]
----

The `create_index()` method requires an index name to be provided, along with the fields to create the index on.
Like the _primary_ index, you can restrict a _secondary_ index to a named scope and collection by passing some options.

Indexes can easily take a long time to build if they contain a lot of documents.
In these situations, it is more ideal to build indexes in the background.
To achieve this we can use the `deferred` boolean option, and set it to `True`.

.Deferring index creation

[source,python]
----
include::howtos:example$query_index_manager.py[tag=defer-indexes,indent=0]
----

To delete a query index you can use the `drop_index()` or `drop_primary_index()` methods. 
Which one you use depends on the type of query index you wish to drop from the database.

.Deleting an index

[source,python]
----
include::howtos:example$query_index_manager.py[tag=drop-primary-or-secondary-index,indent=0]
----

// * Search - note & link to FTS page & API?

== Views Management

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=view-management]

In the SDK, design documents are represented by the `DesignDocument` and `View` classes.
All operations on design documents are performed on the `ViewIndexManager` instance:


[source,python]
----
include::howtos:example$provisioning_resources_views.py[tag=create_view_mgr]
----

The following example upserts a design document with two views:

[source,python]
----
include::howtos:example$provisioning_resources_views.py[tag=create_view]
----

include::{version-server}@sdk:shared:partial$flush-info-pars.adoc[tag=one-view-update-warning]

Note the use of `DesignDocumentNamespace.DEVELOPMENT`, the other option is `DesignDocumentNamespace.PRODUCTION`.
This parameter specifies whether the design document should be created as development, or as production -- with the former running over only a small fraction of the documents.

Now that we've created a design document we can fetch it:

[source,python]
----
include::howtos:example$provisioning_resources_views.py[tag=get_view]
----

We've created the design document using `DesignDocumentNamespace.DEVELOPMENT` and now want to push it to production, we can do this with:

[source,python]
----
include::howtos:example$provisioning_resources_views.py[tag=publish_view]
----

To remove this design document:

[source,python]
----
include::howtos:example$provisioning_resources_views.py[tag=drop_view]
----
