= Authenticating against Couchbase Server
:description: As well as Role-Based Access Control (RBAC), Couchbase offers connection with Certificate Authentication, and works transparently with LDAP.
:page-topic-type: howto
:page-edition: Enterprise Edition
:page-aliases: ROOT:sdk-authentication-overview

[abstract]
{description}


Our xref:hello-world:start-using-sdk.adoc[Getting Started] guide covered the basics for authorizing against a Couchbase cluster, but you may need to use alternative authentication methods such as Certification.


== RBAC

Our xref:hello-world:start-using-sdk.adoc[Getting Started] guide introduced basic authentication against a Couchbase cluster:

[source,python]
----
from couchbase.cluster import Cluster, ClusterOptions
from couchbase_core.cluster import PasswordAuthenticator

cluster = Cluster('couchbase://localhost', ClusterOptions(PasswordAuthenticator('username', 'password')))
----

include::7.0@sdk:shared:partial$auth-overview.adoc[tag=rbac]

include::7.0@sdk:shared:partial$auth-overview.adoc[tag=cert-auth]


== Authenticating a Python Client by Certificate

[NOTE]
====
Certificate authentication in the Python SDK is currently under development.
====

For sample procedures whereby certificates can be generated and deployed, see xref:6.5@server:manage:manage-security/manage-certificates.adoc[Manage Certificates].
The rest of this document assumes that the processes there, or something similar, have been followed.
That is, a cluster certificate has been created and installed on the server, a client certificate has been created, and it is stored somewhere accessible to the SDK.
The `CertAuthenticator` expects to be given the path to the client certificate and key as well as the path to the certificate trust store.

[source,python]
----
include::example$cert-auth.py[tag=auth,indent=0]
----


include::7.0@sdk:shared:partial$auth-overview.adoc[tag=ldap]

[source,python]
----
# Use over TLS for production
cluster = Cluster("couchbases://10.143.205.101?sasl_mech_force=PLAIN&certpath=cert.ca",ClusterOptions(PasswordAuthenticator("einstein","password")))
----
