= MapReduce Views
:description: You can use MapReduce views to create queryable indexes in Couchbase Data Platform.
:navtitle: MapReduce Views
:page-topic-type: howto
:page-aliases: ROOT:view-queries-with-sdk,ROOT:view-queries

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

include::{version-common}@sdk:shared:partial$views.adoc[tag=deprecate]


include::{version-common}@sdk:shared:partial$views.adoc[tag=views-intro]


== Querying Views

Once you have a view defined, it can be queried from the Python SDK by using the `view_query` method on a `Bucket` instance.

The following example is the definition of a `by_country` view in a _landmarks-by-country_ design document. This view checks whether a document is a landmark and has a country. If it does, it emits the landmark’s country into the index. This view allows landmarks to be queried for by country. For example, it’s now possible to ask the question "What countries start with U?"


[source,python]
----
include::howtos:example$view_ops.py[tag=landmarks_by_country]
----

The following example is the definition of a `by_name` view in a _landmarks-by-name_ design document in the _travel-sample_ sample dataset. This view checks whether a document is a landmark and has a name. If it does, it emits the landmark’s name into the index. This view allows landmarks to be queried for by its _name_ field.

[source,python]
----
include::howtos:example$view_ops.py[tag=landmarks_by_name]
----

Once a view result is obtained then it can be iterated over and the ID, keys and values extracted.

[source,python]
----
include::howtos:example$view_ops.py[tag=iterating]
----
