= Pre-release Archive Release Notes
:navtitle: α & β Release Notes
:page-topic-type: project-doc
:page-aliases: 3.0αλφα-sdk-release-notes

[abstract] 
Release notes for the 3.0 Alpha & Beta Releases

In the run-up to the SDK 3.0 API releases, several αλφα and βετα releases were made.
Their release notes are maintained here for archive purposes.
The 3.0 series release notes proper can be found xref:sdk-release-notes.adoc[here], along with install instructions for all supported platforms.
Please note that none of the pre-releases listed below are supported; all _supported_ (GA) releases can be found xref:sdk-release-notes.adoc[here].

WARNING: These are the pre-release α & β Release Notes maintained purely for archive and information purposes.
These releases are unsupported.
Supported (GA) releases can be found xref:sdk-release-notes.adoc[on the general 3.0 Release Notes page].


== Python SDK 3.0.0 Beta 3 Release Notes (January 20 2020)

[source,bash]
----
pip install couchbase==3.0.0b3
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.0-beta3/

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-766[PYCBC-766]:
Bumped LCB requirement to 3.0.0.

* https://issues.couchbase.com/browse/PYCBC-757[PYCBC-757]:
Refactored for FTS/N1QL/durability LCB changes.

* https://issues.couchbase.com/browse/PYCBC-758[PYCBC-758]:
Reflected renaming of `lcb_wait3` to `lcb_wait` in LCB.

* https://issues.couchbase.com/browse/PYCBC-765[PYCBC-765]:
Expose Collection properties and Datastructures in Sphinx docs.

* https://issues.couchbase.com/browse/PYCBC-610[PYCBC-610]:
FTS Index Management for SDK3.

* https://issues.couchbase.com/browse/PYCBC-750[PYCBC-750]:
Add Search Index manager for SDK3.

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-760[PYCBC-760]
Fixed Collection.exists implementation.

* https://issues.couchbase.com/browse/PYCBC-640[PYCBC-640]
Implemented replica reads according to RFC.

* https://issues.couchbase.com/browse/PYCBC-768[PYCBC-768]:
Refactored durability params to prevent impossible combinations.

* https://issues.couchbase.com/browse/PYCBC-639[PYCBC-639]:
Example N1QL statements do seem to work in "Hello Couchbase" example.

* https://issues.couchbase.com/browse/PYCBC-667[PYCBC-667]:
Fixed Upsert Group fails with 'roles: value must be supplied'.

* https://issues.couchbase.com/browse/PYCBC-674[PYCBC-674]:
Fixed deprecation warnings from sdk2 when running sdk3.

* https://issues.couchbase.com/browse/PYCBC-675[PYCBC-675]:
Brough Result objects in line with RFC, removed unidiomatic interfaces.

* https://issues.couchbase.com/browse/PYCBC-694[PYCBC-694]:
Completed query implementation.

* https://issues.couchbase.com/browse/PYCBC-753[PYCBC-753]:
Collection APIs marked volatile.

* https://issues.couchbase.com/browse/PYCBC-763[PYCBC-763]:
Corrected MutateInResult.content_as implementation.

* https://issues.couchbase.com/browse/PYCBC-764[PYCBC-764]:
Delete or renamed remaining SDK2 references in main API:
Renamed SDK2/sdk2 to Core/core where applicable. 
Removed classes & methods inapplicable to SDK3.

* https://issues.couchbase.com/browse/PYCBC-704[PYCBC-704]:
Implemented `*CollectionOptions` for Collection management API.

* https://issues.couchbase.com/browse/PYCBC-716[PYCBC-716]:
Tests should no longer try to do 6.5-specific tests against a 6.0 server.

* https://issues.couchbase.com/browse/PYCBC-686[PYCBC-686]:
Applyed new naming convention for interfaces/protocols.

* https://issues.couchbase.com/browse/PYCBC-687[PYCBC-687]:
Support added for Python 3.8.

* https://issues.couchbase.com/browse/PYCBC-761[PYCBC-761]:
Added timeout to `lookup_in` operation.


== Python SDK 3.0.0 Beta 2 Release Notes (December 30 2019)

[source,bash]
----
pip install couchbase==3.0.0b2
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.0-beta2/

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-680[PYCBC-680]:
UpsertOptions should use 'expiry' rather than 'expiration'.

* https://issues.couchbase.com/browse/PYCBC-692[PYCBC-692]:
Implement Collection.exists

* https://issues.couchbase.com/browse/PYCBC-693[PYCBC-693]:
Fix UpsertOptions constructor

* https://issues.couchbase.com/browse/PYCBC-697[PYCBC-697]:
Migrate to timedelta/datetime from FiniteDuration/Seconds etc

* https://issues.couchbase.com/browse/PYCBC-709[PYCBC-709]:
Convert from lcb_strerror to lcb_strerror_short

* https://issues.couchbase.com/browse/PYCBC-717[PYCBC-717]:
Tighten up lookup test with nonexistent path

* https://issues.couchbase.com/browse/PYCBC-721[PYCBC-721]:
Implement collection.drop_collection and drop_scope

* https://issues.couchbase.com/browse/PYCBC-647[PYCBC-647]:
Support View design documents for SDK3

* https://issues.couchbase.com/browse/PYCBC-725[PYCBC-725]:
Adjust to latest error name refactorings in LCB3

* https://issues.couchbase.com/browse/PYCBC-631[PYCBC-631]:
Add query service fast prepare support

* https://issues.couchbase.com/browse/PYCBC-646[PYCBC-646]:
View management

* https://issues.couchbase.com/browse/PYCBC-666[PYCBC-666]:
Add timeouts to management/get/store calls

* https://issues.couchbase.com/browse/PYCBC-678[PYCBC-678]:
Update sphinx-autodoc-typehints to attempt to use type comments

* https://issues.couchbase.com/browse/PYCBC-679[PYCBC-679]:
Get rid of obsolete coll/scope injection calls

* https://issues.couchbase.com/browse/PYCBC-683[PYCBC-683]:
N1QL Query Index Management

* https://issues.couchbase.com/browse/PYCBC-718[PYCBC-718]:
Refactor error handling for libcouchbase 3.0.0 Beta 2

* https://issues.couchbase.com/browse/PYCBC-720[PYCBC-720]:
Parameterise patch type for libcouchbase

* https://issues.couchbase.com/browse/PYCBC-728[PYCBC-728]:
Make CouchbaseError.Params constructor type-safe

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-699[PYCBC-699]:
Operate on non-default collection again

* https://issues.couchbase.com/browse/PYCBC-705[PYCBC-705]:
Fix segfault in test_importworks

* https://issues.couchbase.com/browse/PYCBC-708[PYCBC-708]:
Several similar admin test failures

* https://issues.couchbase.com/browse/PYCBC-712[PYCBC-712]:
Don't test collections on older servers

* https://issues.couchbase.com/browse/PYCBC-715[PYCBC-715]:
Fix cluster arguments for analytics operations

* https://issues.couchbase.com/browse/PYCBC-727[PYCBC-727]:
Analytics test fixes

* https://issues.couchbase.com/browse/PYCBC-690[PYCBC-690]:
Set up Combination Testing for SDK 3 - Python 3.x Win and Linux

* https://issues.couchbase.com/browse/PYCBC-700[PYCBC-700]:
Fix Python 2/3 compatibility issues

* https://issues.couchbase.com/browse/PYCBC-724[PYCBC-724]:
Fix PYCBC git tag detection code for x.y.z where z>9

== Python SDK 3.0.0 Beta 1 Release Notes (October 11 2019)

[source,bash]
----
pip install couchbase==3.0.0b1
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.0-beta1/

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-637[PYCBC-637]:
Added static `Cluster.connect` factory method.

* https://issues.couchbase.com/browse/PYCBC-630[PYCBC-630]:
Added Datastructures v2 for SDK3.

* https://issues.couchbase.com/browse/PYCBC-660[PYCBC-660]:
Renamed `lcb_cmdfts_query` to `lcb_cmdfts_payload`.

* https://issues.couchbase.com/browse/PYCBC-661[PYCBC-661]:
Safeguards added for property access when debugging partially constructed `Client` instances.

* https://issues.couchbase.com/browse/PYCBC-664[PYCBC-664]:
Added create bucket management API

* https://issues.couchbase.com/browse/PYCBC-665[PYCBC-665]:
Added create user management API

== Python SDK 3.0.0 Alpha 6 Release Notes (September 27 2019)

[source,bash]
----
pip install couchbase==3.0.0a6
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.0-alpha6/

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-638[PYCBC-638]:
`scope` and `collection` methods now marked as "uncommitted".

* https://issues.couchbase.com/browse/PYCBC-584[PYCBC-584]:
fulldoc insert with subdoc upsert now supported with LCB V4 API.

* https://issues.couchbase.com/browse/PYCBC-644[PYCBC-644]:
Updates to reflect C code changes for logging, subdocs, `LCB_STORE_**`, `lcb_*3`, and `enable_mutation_tokens` refactorings.

* https://issues.couchbase.com/browse/PYCBC-645[PYCBC-645]:
Changes made to handle new safety checks in LCB for bad hostname.

* https://issues.couchbase.com/browse/PYCBC-652[PYCBC-652]:
Refactored for new `lcb_createopts_**` API.

* https://issues.couchbase.com/browse/PYCBC-654[PYCBC-654]:
Refactored for temporary removal of `observe`/`endure`/`mctx` code from LCB3 for client-side durability changes.

* https://issues.couchbase.com/browse/PYCBC-657[PYCBC-657]:
Refactored for libcouchbase 3.0.0 Beta 1.

== Python SDK 3.0.0 Alpha 5 Release Notes (August 23 2019)

[source,bash]
----
pip install couchbase==3.0.0a5
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.0-alpha5/

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-616[PYCBC-616]:
Migrate [.api]`acouchbase` module to SDK3

* https://issues.couchbase.com/browse/PYCBC-621[PYCBC-621]:
Update Cluster constructor docs to indicate mandatory authenticator

* https://issues.couchbase.com/browse/PYCBC-623[PYCBC-623]:
Document Git dependency

* https://issues.couchbase.com/browse/PYCBC-624[PYCBC-624]:
Update Hello World example to indicate mandatory authenticator argument

* https://issues.couchbase.com/browse/PYCBC-625[PYCBC-625]:
Make multi-ops explicitly visible in Collection class

* https://issues.couchbase.com/browse/PYCBC-627[PYCBC-627]:
Fix eager_resources setting, fix 2.7 numpydoc incompatibility

* https://issues.couchbase.com/browse/PYCBC-570[PYCBC-570]:
Python: Author docs for SubDocument LookupIn

* https://issues.couchbase.com/browse/PYCBC-603[PYCBC-603]:
Python: SubDoc mutateIn Docs authoring

* https://issues.couchbase.com/browse/PYCBC-626[PYCBC-626]:
Add durability to subdoc, touch and counter operations

* https://issues.couchbase.com/browse/PYCBC-606[PYCBC-606]:
Synchronous Replication snippets

* https://issues.couchbase.com/browse/PYCBC-633[PYCBC-633]:
Rename KV-style Bucket classes to `Client` for SDK3 code

== Python SDK 3.0.0 Alpha 4 Release Notes (July 12 2019)

[source,bash]
----
pip install couchbase==3.0.0a4
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.0-alpha4/

=== Enhancements


* https://issues.couchbase.com/browse/PYCBC-611[PYCBC-611]:
Diagnostics for SDK3.

* https://issues.couchbase.com/browse/PYCBC-612[PYCBC-612]:
FTS for SDK3.

* https://issues.couchbase.com/browse/PYCBC-613[PYCBC-613]:
Analytics for SDK3.

* https://issues.couchbase.com/browse/PYCBC-614[PYCBC-614]:
Run service commands directly from bootstrapped cluster.

* https://issues.couchbase.com/browse/PYCBC-571[PYCBC-571]:
Services for SDK3.

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-607[PYCBC-607]:
Ensure `couchbase_core` is bootstrapped.

* https://issues.couchbase.com/browse/PYCBC-609[PYCBC-609]:
Fix RPATH install for distutils.

== Python SDK 3.0.0 Alpha 3 Release Notes (July 5 2019)

[source,bash]
----
pip install couchbase==3.0.0a3
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.0-alpha3/

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-585[PYCBC-585]:
Refined collections support for SDK3.

* https://issues.couchbase.com/browse/PYCBC-589[PYCBC-589]:
Migrated datastructures to SDK3.

* https://issues.couchbase.com/browse/PYCBC-595[PYCBC-595]:
Implemented multi-ops in Collection class.

* https://issues.couchbase.com/browse/PYCBC-596[PYCBC-596]:
Centralised Collections/Bucket functionality, giving 'legacy style' behavior within the context of a Collection.

* https://issues.couchbase.com/browse/PYCBC-597[PYCBC-597]:
Added buckets_list function to documentation index.

* https://issues.couchbase.com/browse/PYCBC-601[PYCBC-601]:
Use correct RPATH when using legacy build option (distutils).


== Python SDK 3.0.0 Alpha 2 Release Notes (June 18 2019)

[source,bash]
----
pip install couchbase==3.0.0a2
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.0-alpha2/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-592[PYCBC-592]: 
Fixed manifest to include extra files for distribution.

* https://issues.couchbase.com/browse/PYCBC-593[PYCBC-593]: 
Restrict LCB versions to tagged &gt;=2.10.3, &gt;=3.0.0-alpha.3.

== Python SDK 3.0.0 Alpha 1 Release Notes (June 14 2019)

[source,bash]
----
pip install couchbase==3.0.0a1
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.0-alpha1/

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-540[PYCBC-540]:
Added Basic CRUD for SDK 3.0.

* https://issues.couchbase.com/browse/PYCBC-541[PYCBC-541]:
Added Basic Query for SDK 3.0.

* https://issues.couchbase.com/browse/PYCBC-564[PYCBC-564]:
Added Synchronous Durability Operations.

* https://issues.couchbase.com/browse/PYCBC-566[PYCBC-566]:
KV Operations Doc at draft level.

* https://issues.couchbase.com/browse/PYCBC-583[PYCBC-583]:
Python Doc on Error Handling for SDK 3 (v1).

* https://issues.couchbase.com/browse/PYCBC-546[PYCBC-546]:
Update CMakeLists.txt to pull in libcouchbase and other deps.

* https://issues.couchbase.com/browse/PYCBC-561[PYCBC-561]:
Update Error Handling for SDK3 Python.

* https://issues.couchbase.com/browse/PYCBC-562[PYCBC-562]:
Move to libcouchbase 3.0.0 and LCB API v4.

* https://issues.couchbase.com/browse/PYCBC-582[PYCBC-582]:
Made touch tests more reliable.

* https://issues.couchbase.com/browse/PYCBC-588[PYCBC-588]:
Fixed Centos compilation.

== Upgrading 2.x

Versions of the Python SDK prior to 3.0.0 do not bundle libcouchbase.
Be sure to xref:c-sdk:project-docs:sdk-release-notes.adoc[upgrade your LCB installation] before making a major upgrade to the Couchbase Python client.

