= Compatibility of Couchbase Features, Couchbase Server Versions, and the Couchbase Python SDK
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:navtitle: Compatibility
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 2

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

The Couchbase Python SDK aims to run on any https://devguide.python.org/versions/#supported-versions[supported Python version] in security or maintenance status -- see the table below for <<python-version-compat,supported versions>>.


== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Python SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="30,20,25,20"]
|===
| | SDK 2.5  | SDK 3.0, 3.1 | 3.2

| *Server 5.0-5.5*
| *✔*
| ◎
| ◎

| *Server 6.0*
| *✔*
| *✔*
| *✔*

| *Server 6.-6.6*
| *✔*
| *✔*
| *✔*

| *Server 7.0*
| ◎
| ◎
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.


=== Capella Compatibility

At time of release, the Couchbase 3.2 Python SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service. 

include::{version-server}@sdk:shared:partial$capella.adoc[tag=cloud]



[#python-version-compat]
== Python Version Compatibility

The Couchbase Python SDK aims to support https://devguide.python.org/versions/#supported-versions[Python versions] in security or bug-fix (a.k.a. maintenance) status.
The table below indicates the Python SDK version where support of a version of Python was added.
Python versions that have reached their https://endoflife.date/python[End-of-Life date] are not supported.

Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.

Other Python versions and implementations might work but are _not tested and are not supported_.
Please make sure you run on one of the latest patch releases, since they provide stability improvements and security fixes in general.

.Supported Python Versions
[cols="5,8,8"]
|===
| Python Version | Support EOL | Couchbase SDK Versions Supported

| https://www.python.org/dev/peps/pep-0537/#lifespan[3.7]
| until 2023-06-27
| from 3.0.0

| https://www.python.org/dev/peps/pep-0569/#lifespan[3.8]
| until 2024-10
| from 3.0.0

| https://www.python.org/dev/peps/pep-0596/#lifespan[3.9]
| until 2025-10
| from 3.0.0

| https://peps.python.org/pep-0619/#lifespan[3.10]
| until 2026-10
| from 4.0.0

| https://peps.python.org/pep-0664/#lifespan[3.11]
| until 2027-10
| from 4.1.6

|===


== Platform Compatibility

The Python SDK is built on top of libcouchbase (the C SDK), which is tested and supported on the following platforms:

****
[discrete]
=== GNU/Linux

* Amazon Linux 2.
* Red Hat Enterprise Linux 7 & 8;
+
& CentOS 7 & 8.
* Ubuntu (LTS) 16.04 (_Xenial_), 18.04 (_Bionic_), & 20.04 (_Focal_).
* Debian 9 (_Stretch_) & 10 (_Buster_).
* Alpine Linux (since Python SDK 3.2.7).

[discrete]
=== Microsoft Windows

Microsoft Windows 7 / Windows Server 2012 and onwards.

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (July 2021): 10.14 (_Mojave_), 10.15 (_Catalina_), and 11 (_Big Sur_).
****

Although installable or compilable on many other platforms, we cannot provide support for untested combinations.


== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,7,5,6,5"]
|===
| | Server 5.0, 5.1, & 5.5 | Server 6.0 | Server 6.5 & 6.6 | Server 7.0

| Enhanced Durability
4+| All SDK versions

| Durable Writes
2+| Not Supported
2+| Since 3.0

| Analytics
| DP in 5.5 with 2.4
3+| Since 2.5

| Collections
2+| Not Supported
| Developer Preview in 6.5-6.6, SDK 3.0
| Since 3.0.10

| Scope-Level N1QL Queries & all Collections features
3+| Not Supported
| Since SDK 3.2.0

| Field Level Encryption v2
2+| Not Supported
2+| Since SDK 3.2.0footnote:[Field Level Encryption distributed as separate library.]

| Request Tracing
2+| Not Supported
2+| Since SDK 3.2.0
|===

include::{version-server}@sdk:shared:partial$network-requirements.adoc[]


include::{version-server}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]

include::7.0@sdk:shared:partial$api-version.adoc[tag=api-version]
