= Compatibility
:description: Platform compatibility, and features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 3
:table-caption!:

[abstract]
{description}

The Couchbase Python SDK aims to run on any https://devguide.python.org/versions/#supported-versions[supported Python version] in security or maintenance status -- see the table below for <<python-version-compat,supported versions>>.


== Platform Compatibility


=== Python Version Compatibility

The Couchbase Python SDK aims to support https://devguide.python.org/versions/#supported-versions[Python versions] in security or bug-fix (a.k.a. maintenance) status.
The table below indicates the Python SDK version where support of a version of Python was added.
Python versions that have reached their https://endoflife.date/python[End-of-Life date] are not supported.

Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.

Other Python versions and implementations might work but are _not tested and are not supported_.
Please make sure you run on one of the latest patch releases, since they provide stability improvements and security fixes in general.

.Supported Python Versions
[cols="5,8,8"]
|===
| Python Version | Support EOL | Couchbase SDK Versions Supported

| https://peps.python.org/pep-0619/#lifespan[3.10]
| until 2026-10
| from 4.0.0

| https://peps.python.org/pep-0664/#lifespan[3.11]
| until 2027-10
| from 4.1.6

| https://peps.python.org/pep-0693/#lifespan[3.12]
| until 2028-10
| from 4.3.2

| https://peps.python.org/pep-0719/#lifespan[3.13]
| until 2029-10
| from 4.3.4

| https://peps.python.org/pep-0745/#lifespan[3.14]
| until 2030-10
| from 4.6.0
|===



////
| https://peps.python.org/pep-0745/#lifespan[3.15]
| until 2031-10
| from 4.
////



=== OS Compatibility

The {name-sdk} will run on, and is supported on, the following OSs and platforms.
The SDK has been tested on a representative subset of the platforms listed below.

****
[discrete]
=== GNU/Linux

* Amazon Linux 2 & AL2023.* Red Hat Enterprise Linux 8, 9, & 10.
* Oracle Linux 8, 9, & 10.

* Ubuntu (LTS) 22.04 (_Jammy_) & 24.04 (_Noble_).
* Debian 11 (_Bullseye_), Debian 12 (_Bookworm_), & Debian 13 (_Trixie_).
* SUSE Enterprise Linux 12 & 15.
* Alpine Linux 3.21 - 3.23.


[discrete]
=== Microsoft Windows

* Microsoft Windows 10 & 11;
* Windows Server 2019, 2022, & 2025.

[discrete]
=== Mac OS X

* The current and previous two releases of OS X.
At time of writing (March 2026): 26 (Tahoe), 15 (Sequoia), and 14 (Sonoma).
****




// Platforms, Chipsets, and Virtual Environments.
include::{version-common}@sdk:shared:partial$platform.adoc[tag=virtual]







// Network Requirements
include::{version-common}@sdk:shared:partial$network-requirements.adoc[]





=== SSL Library

The Python SDK binaries are statically link against `BoringSSL`,
and there is no need to separately install any SSL library.


== Couchbase Server Compatibility

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.

=== Couchbase Version/SDK Version Matrix

The matrix below denotes the version of Couchbase Server, the version of the {name-sdk} and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
Nevertheless, this combination is not recommended by our technical support organization, as not all of the latest features are supported by it.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
|===
| | 4.2 - 4.3 | 4.4 | 4.5-4.6

| *Server 8.0*
| *◎*
| *✔*
| *✔*

| *Server 7.6*
| *✔*
| *✔*
| *✔*

| *Server 7.2*
| *✔*
| *✔*
| *✔*
|===

Note the https://www.couchbase.com/support-policy/EOL/[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

The Python SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the Python SDK includes the Capella client certificate ready installed.

include::{version-common}@sdk:shared:partial$capella.adoc[tag=cloud]


=== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,6,6,6"]
|===
| | Server 7.2 | Server 7.6.x  | Server 8.0

| KV Range Scan
| N/A
2+| From SDK 4.2.0

| Vector Search
| N/A
2+| From SDK 4.2.0 (base64 encoded vectors from 4.3.0)

| Zone aware replica reads
| N/A
2+| From SDK 4.3.0

| Vector Query using GSI
2+| N/A
| From SDK 4.5.0 ①
|===

① As part of the standard SDK {sqlpp} API, it should be compatible with all earlier versions of the SDK -- but it has not been tested.

This table is not an exhaustive list -- just a few highlights -- provided to help assess compatibility of older versions in particular.
For a slightly fuller table, see the xref:deployment.adoc#couchbase-operational-cluster-feature-compatibility[Deployment page].
For alignment of SDKs and new Server features, scroll down to the information below the <<api-version,API Version table>>.




=== API Version

include::{version-common}@sdk:shared:partial$api-version.adoc[tag=api-version]



== SDK API Stability

// === Interface Stability

include::{version-common}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]


=== Older SDK Versions

include::{version-common}@sdk:shared:partial$archive.adoc[tag=link]
