= Compatibility of Couchbase Features, Couchbase Server Versions, and the Couchbase Python SDK
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:navtitle: Compatibility
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 2

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}


== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Python SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="30,20,25,20"]
|===
| | SDK 3.0, 3.1 | 3.2 | 4.0

| *Server 6.0*
| *✔*
| *✔*
| *✔*

| *Server 6.5-6.6*
| *✔*
| *✔*
| *✔*

| *Server 7.0-7.1*
| ◎
| *✔*
| *✔*
|===

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

At time of release, the Couchbase 4.0 Python SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the 4.0 SDK includes the Capella client certificate ready installed.


[#python-version-compat]
== Python Version Compatibility

The Python SDK is tested with Python versions 3.7 - 3.10.
Other Python versions and implementations might work but are _not tested and are not supported_.
We recommend using a Python version, with the highest patch version available, that is not close to reaching end of life according to the Python Software Foundation.

Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.

The following Python versions are supported:

* https://www.python.org/dev/peps/pep-0537/#lifespan[Python 3.7]
* https://www.python.org/dev/peps/pep-0569/#lifespan[Python 3.8]
* https://www.python.org/dev/peps/pep-0596/#lifespan[Python 3.9]
* https://peps.python.org/pep-0619/#lifespan[Python 3.10]

Please make sure you run on one of the latest patch releases, since they provide stability improvements and security fixes in general.

== Platform Compatibility

The Python SDK is built on top of the C++ SDK (not currently available separately), which is tested and supported on the following platforms:

****
[discrete]
=== GNU/Linux

* Amazon Linux 2.
* Red Hat Enterprise Linux 7 & 8 -- but see note below;
* CentOS 7 & 8 -- but see note below.
* Ubuntu (LTS) 16.04 (_Xenial_), 18.04 (_Bionic_), & 20.04 (_Focal_).
* Debian 9 (_Stretch_) & 10 (_Buster_).
* Alpine Linux

Note, for stability reasons, CentOS and Red Hat ship with far older versions of Python and GCC than the ones needed to run the latest Python SDK.
See the xref:project-docs:sdk-full-installation.adoc[full installation page] for details of using the EPEL repo, and other workarounds.

[discrete]
=== Microsoft Windows

Microsoft Windows 10 / All LTS releases from Windows Server 2016.

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (April 2022): 10.15 (_Catalina_), 11 (_Big Sur_), and 12 (_Monterey_).
M1 ARM  architecture is fully supported in the 4.0 Python SDK.
****

Wheels are available for macOS and Windows -- see the xref:sdk-release-notes.adoc[releases page] for details.

Although installable or compilable on many other platforms, we cannot provide support for untested combinations.

=== ARM Processor Support

Python 4.0 SDK supports AWS Amazon Graviton2 and Apple M1 ARM processors.


== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="7,7,5,6,5"]
|===
| | Server 6.0 | Server 6.5 & 6.6 | Server 7.0 | Server 7.1

| Enhanced Durability
4+| All SDK versions

| Durable Writes
| Not Supported
3+| Since 3.0

| Default Collections
| Not Supported
| Developer Preview in 6.5-6.6, SDK 3.0
2+| Since 3.0.10

| Scope-Level N1QL Queries & all Collections features
2+| Not Supported
2+| Since SDK 3.2.0

| Field Level Encryption v2
| Not Supported
3+| Since SDK 3.2.0footnote:[Field Level Encryption distributed as separate library.]

| Request Tracing
| Not Supported
3+| Since SDK 3.2.0

| Distributed ACID Transactions
|
3+| Since Couchbase Server 6.6.1 and SDK 4.0
|===

include::{version-server}@sdk:shared:partial$network-requirements.adoc[]


include::{version-server}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]

include::{version-server}@sdk:shared:partial$api-version.adoc[tag=api-version]

include::7.1@sdk:shared:partial$archive.adoc[tag=link]
