= SDK Release Notes
:description: Release notes, installation instructions, and download archive for the Couchbase Python Client.
:navtitle: Release Notes
:page-partial:
:page-toclevels: 2
:page-aliases: ROOT:relnotes-python-sdk,adoc,ROOT:download-links.adoc,ROOT:release-notes.adoc,ROOT:sdk-release-notes.adoc


// tag::all[]
[abstract]
{description}

Couchbase Python SDK 4.x is built upon the Couchbase {cpp} SDK, and SDK 3.x is built upon LCB (libcouchbase), but both conform to the xref:project-docs:compatibility.adoc#api-version[SDK API 3.x].
The move to the Couchbase {cpp} SDK facilitates the introduction of xref:howtos:distributed-acid-transactions-from-the-sdk.adoc[distributed ACID transactions].

NOTE: Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.


== Installation

The full installation instructions that were previously on this page can now be found xref:sdk-full-installation.adoc[here].


[#latest-release]
== Python SDK 4.6 Releases

We always recommend using the latest version of the SDK -- it contains all of the latest security patches and support for new and upcoming features.
All patch releases for each dot minor release should be API compatible, and safe to upgrade;
any changes to expected behavior are noted in the release notes that follow.


=== Version 4.6.0 (31 March 2026)

Version 4.6.0 is a minor release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the 4.6.0 release adds observability support (with the ability to integrate with OpenTelemetry) and adds support for Python 3.14 --
see xref:compatibility.adoc#python-version-compat[Python Version Compatibility] for details of supported Python versions.

[source,bash]
----
$ python3 -m pip install couchbase==4.6.0
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.6.0/

==== Behavioral Changes

The Couchbase Python SDK no longer provides Python 3.9 wheels as Python 3.9 reached https://peps.python.org/pep-0596/#lifespan[end-of-life] in October 2025.
See xref:project-docs:compatibility.adoc#python-version-compat[Python Version Compatibility] for details on supported Python versions.

Multi operations that allow for durability no longer allow client and server durability to be mixed across operations.
If durability is specified for a multi operation, any per-key-options must use the same durability type (either client or server durability).

All APIs (`acouchbase`, `couchbase`, and `txcouchbase`) no longer allow a cluster that has been closed to be reconnected.
Any attempt to use a closed cluster will raise an exception.
In order to establish a new connection after closing a cluster, a new cluster instance must be created.

The `QueryIndexManagement` `create_index()` API no longer allows `fields` to be used to specify index keys.
The `keys` field must be used to indicate the keys to use in the index.


==== Enhancements

* https://jira.issues.couchbase.com/browse/PYCBC-1700[PYCBC-1700],
https://jira.issues.couchbase.com/browse/PYCBC-1724[PYCBC-1724]:
Added support for Python 3.14.

* https://jira.issues.couchbase.com/browse/PYCBC-1701[PYCBC-1701]:
Dropped support for Python 3.9.

* https://jira.issues.couchbase.com/browse/PYCBC-1714[PYCBC-1714]:
Added support mTLS Certs Refresh (without restart).

* https://jira.issues.couchbase.com/browse/PYCBC-1715[PYCBC-1715]:
Added support for JWT based authentication in Operational SDKs.

* https://jira.issues.couchbase.com/browse/PYCBC-1718[PYCBC-1718],
https://jira.issues.couchbase.com/browse/PYCBC-1722[PYCBC-1723],
https://jira.issues.couchbase.com/browse/PYCBC-1722[PYCBC-1721],
https://jira.issues.couchbase.com/browse/PYCBC-1722[PYCBC-1722],
https://jira.issues.couchbase.com/browse/PYCBC-1722[PYCBC-1728],
https://jira.issues.couchbase.com/browse/PYCBC-1750[PYCBC-1750]:
Added Observability Support.
The SDK now natively supports Tracing, Metrics, and `OTel` Integration.

* https://jira.issues.couchbase.com/browse/PYCBC-1727[PYCBC-1727]:
Deprecated support for MapReduce Views (which is also now deprecated in Couchbase Server).

* https://jira.issues.couchbase.com/browse/PYCBC-1730[PYCBC-1730],
https://jira.issues.couchbase.com/browse/PYCBC-1731[PYCBC-1731],
https://jira.issues.couchbase.com/browse/PYCBC-1733[PYCBC-1733],
https://jira.issues.couchbase.com/browse/PYCBC-1734[PYCBC-1734],
https://jira.issues.couchbase.com/browse/PYCBC-1735[PYCBC-1735],
https://jira.issues.couchbase.com/browse/PYCBC-1736[PYCBC-1736],
https://jira.issues.couchbase.com/browse/PYCBC-1737[PYCBC-1737],
https://jira.issues.couchbase.com/browse/PYCBC-1738[PYCBC-1738],
https://jira.issues.couchbase.com/browse/PYCBC-1739[PYCBC-1739],
https://jira.issues.couchbase.com/browse/PYCBC-1740[PYCBC-1740],
https://jira.issues.couchbase.com/browse/PYCBC-1742[PYCBC-1742],
https://jira.issues.couchbase.com/browse/PYCBC-1743[PYCBC-1743],
https://jira.issues.couchbase.com/browse/PYCBC-1756[PYCBC-1756]:
Migrated internal SDK APIs away from Wrapper decorators.

* https://jira.issues.couchbase.com/browse/PYCBC-1745[PYCBC-1745],
https://jira.issues.couchbase.com/browse/PYCBC-1747[PYCBC-1747]:
Use {cpp} Templating System for SDK C-Extension.

* https://jira.issues.couchbase.com/browse/PYCBC-1754[PYCBC-1754]:
Added Logging Improvements.

* https://jira.issues.couchbase.com/browse/PYCBC-1755[PYCBC-1755]:
Updated `JSONType` type hint to adhere to static typing standards.


==== Fixes

* https://jira.issues.couchbase.com/browse/PYCBC-1725[PYCBC-1725]:
Fixed decoding to be deferred until result is accessed by `*Result` object.

* https://jira.issues.couchbase.com/browse/PYCBC-1744[PYCBC-1744]:
Fixed cluster instances across all APIs to not allow reconnect after close.


==== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1758[PYCBC-1758]:
This version of the SDK does not propagate a small number of `ClusterOptions` to the {cpp} core. 
This will be fixed in the next patch release (4.6.1).

* https://issues.couchbase.com/browse/PYCBC-1753[PYCBC-1753]:
In 4.6.0, the Python Client is not passing `scope_name` or `bucket_name` when using scoped search indexes.
This will be fixed in the next patch release (4.6.1).


==== Underlying {cpp} SDK Core Changes


* https://jira.issues.couchbase.com/browse/CXXCBC-732[CXXCBC-732]:
Fixed memory leaks in concurrent fixed queue reporting.

* https://jira.issues.couchbase.com/browse/CXXCBC-739[CXXCBC-739]:
**mTLS Certificate Refresh** -- Added support for refreshing TLS certificates without restarting the application.
Certificates can now be updated via `cluster::update_credentials()` and new TLS sessions will use the updated certificates.

* https://jira.issues.couchbase.com/browse/CXXCBC-740[CXXCBC-740]:
**JWT Authentication** -- Added JWT-based authentication support via `jwt_authenticator`.
The authenticator can refresh tokens automatically and supports reauthentication when tokens become stale.

* https://jira.issues.couchbase.com/browse/CXXCBC-745[CXXCBC-745]:
**Lazy Connections Mode** -- Added new `enable_lazy_connections` option that delays opening KV connections until the first operation is executed, reducing initial connection overhead.

* https://jira.issues.couchbase.com/browse/CXXCBC-750[CXXCBC-750]:
**Internal Tracer for Wrapper SDKs** -- Added internal tracer interface (`tracer_wrapper::wrapped()`) for use by wrapper SDKs that want to integrate with the SDK's tracing.

* https://jira.issues.couchbase.com/browse/CXXCBC-752[CXXCBC-752]:
MapReduce Views are now deprecated.
Use Query with {sqlpp} instead.

* https://jira.issues.couchbase.com/browse/CXXCBC-763[CXXCBC-763]:
Fixed `set_authenticator` not applying updated cert/key pairs to new TLS sessions.

* https://jira.issues.couchbase.com/browse/CXXCBC-766[CXXCBC-766]:
Fixed `OpenSSL` headers priority in `BoringSSL` builds.

* https://jira.issues.couchbase.com/browse/CXXCBC-767[CXXCBC-767]:
Implemented `AuthStale` handling and JWT reauthentication support.

* https://jira.issues.couchbase.com/browse/CXXCBC-768[CXXCBC-768]:
**DNS-SRV Refresh Fix** -- Fixed an issue where `bucket_not_found` errors during bootstrap would trigger unnecessary DNS-SRV record refresh loops.

* https://jira.issues.couchbase.com/browse/CXXCBC-771[CXXCBC-771]:
**Credentials Update Restrictions** -- `cluster::update_credentials()` now prevents switching between authenticator types (e.g., password to certificate) to avoid unexpected behavior.

* **Mozilla Certificate Parsing** -- Updated the regex for parsing the header date of Mozilla certificates from curl.se to ensure correct certificate handling and added a warning if the header date is not found.



== Python SDK 4.5 Releases


=== Version 4.5.0 (29 September 2025)

Version 4.5.0 is a minor release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.5.0
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.5.0/

==== Behavioral Changes

The Couchbase Python SDK will stop providing Python 3.9 wheels in a future release as Python 3.9 will reach https://peps.python.org/pep-0596/#lifespan[end-of-life] in October 2025.
See xref:project-docs:compatibility.adoc#python-version-compat[Python Version Compatibility] for details on supported Python versions.

The "auto" network selection heuristic in the underyling {cpp} core has been changed to fall back to the "external" network if the "external" network is present.
Previously, if there was no exact match between an address in the connection string and an address in the cluster topology reported by the server, the SDK would select the "default" network.
Now, if there is no match and an "external" network is present, the SDK selects the "external" network.

==== Enhancements

* https://jira.issues.couchbase.com/browse/PYCBC-1641[PYCBC-1641]:
Updated development dependencies.

* https://jira.issues.couchbase.com/browse/PYCBC-1666[PYCBC-1666]:
Added support "access_deleted" for replica reads.

* https://jira.issues.couchbase.com/browse/PYCBC-1667[PYCBC-1667]:
Updated supported bucket & storage types.

* https://jira.issues.couchbase.com/browse/PYCBC-1668[PYCBC-1668]:
Improved error messages for account lock/unlock feature.

* https://jira.issues.couchbase.com/browse/PYCBC-1689[PYCBC-1689]:
Updated operational SDK prevent connection to Analytics 2.0 Cluster

* https://jira.issues.couchbase.com/browse/PYCBC-1690[PYCBC-1690]:
Added `__repr__()` and `__str__()` methods for search queries.

* https://jira.issues.couchbase.com/browse/PYCBC-1691[PYCBC-1691]:
Updated `ConjunctionQuery` and `DisjunctionQuery` to allow list of queries as input.

* https://jira.issues.couchbase.com/browse/PYCBC-1693[PYCBC-1693]:
Added `CollectionQueryIndexManager` to API reference.

* https://jira.issues.couchbase.com/browse/PYCBC-1699[PYCBC-1699]:
Updated SDK build setup to include {cpp} core changes.

* https://jira.issues.couchbase.com/browse/PYCBC-1703[PYCBC-1703]:
Added Graviton 3 and 4 executors to test pipeline matrices.

* https://jira.issues.couchbase.com/browse/PYCBC-1698[PYCBC-1698],
https://jira.issues.couchbase.com/browse/PYCBC-1704[PYCBC-1704]:
Improved Jenkins Integration Tests.

* https://jira.issues.couchbase.com/browse/PYCBC-1711[PYCBC-1711]:
Updated bucket creation to not set `bucketType`, `replicaIndex`, `flushEnabled` unless set by the user.

==== Fixes

* https://jira.issues.couchbase.com/browse/PYCBC-1694[PYCBC-1694]:
Fixed boolean search queries to allow `should.min=0`.

* https://jira.issues.couchbase.com/browse/PYCBC-1705[PYCBC-1705]:
Fixed encryption import order and exceptions.


==== Underlying {cpp} SDK Core Changes

===== New Features

* https://jira.issues.couchbase.com/browse/CXXCBC-653[CXXCBC-653]:
Added support "access_deleted" for Replica Reads (https://github.com/couchbase/couchbase-cxx-client/pull/821[#821]).

* https://jira.issues.couchbase.com/browse/CXXCBC-639[CXXCBC-639]:
Added support of building both static and shared libraries (https://github.com/couchbase/couchbase-cxx-client/pull/707[#707], https://github.com/couchbase/couchbase-cxx-client/pull/825[#825]).

* https://jira.issues.couchbase.com/browse/CXXCBC-692[CXXCBC-692]:
The SDK now prevents connection to Enterprise Analytics cluster (https://github.com/couchbase/couchbase-cxx-client/pull/792[#792], https://github.com/couchbase/couchbase-cxx-client/pull/807[#807], https://github.com/couchbase/couchbase-cxx-client/pull/810[#810]).

* https://jira.issues.couchbase.com/browse/CXXCBC-693[CXXCBC-693]:
Do not return an error if/when `indexDefs` are empty/null. Instead return w/ an empty list of index definitions (https://github.com/couchbase/couchbase-cxx-client/pull/800[#800]).

* https://jira.issues.couchbase.com/browse/CXXCBC-698[CXXCBC-698]:
Added `flex_index` to `transaction_query_options` (https://github.com/couchbase/couchbase-cxx-client/pull/773[#773]).

* https://jira.issues.couchbase.com/browse/CXXCBC-699[CXXCBC-699]:
Added support of randomization of bootstrap nodes (https://github.com/couchbase/couchbase-cxx-client/pull/777[#777]).

* https://jira.issues.couchbase.com/browse/CXXCBC-707[CXXCBC-707]:
Updated network selection heuristic. The logic is improved in certain cloud-specific cases (https://github.com/couchbase/couchbase-cxx-client/pull/809[#809]).

===== Fixes and Enhancements

* https://jira.issues.couchbase.com/browse/CXXCBC-651[CXXCBC-651]:
Added preserving cached node labels after generating report in app telemetry meter (https://github.com/couchbase/couchbase-cxx-client/pull/802[#802]).

* https://jira.issues.couchbase.com/browse/CXXCBC-695[CXXCBC-695]:
Always return unwrapped `doc_exists` from transactions insert (https://github.com/couchbase/couchbase-cxx-client/pull/771.[#771.]).

* https://jira.issues.couchbase.com/browse/CXXCBC-704[CXXCBC-704]:
Added handling `document_unretrievable` from `get_multi` individual fetch (https://github.com/couchbase/couchbase-cxx-client/pull/782[#782], https://github.com/couchbase/couchbase-cxx-client/pull/785[#785]).

* https://jira.issues.couchbase.com/browse/CXXCBC-706[CXXCBC-706]:
Added closing of half-baked cluster object if connection fails (https://github.com/couchbase/couchbase-cxx-client/pull/783[#783]).

* https://jira.issues.couchbase.com/browse/CXXCBC-709[CXXCBC-709]:
Fix `exists()` in transactions `get_multi` result (https://github.com/couchbase/couchbase-cxx-client/pull/786[#786]).

* https://jira.issues.couchbase.com/browse/CXXCBC-715[CXXCBC-715]:
Fixed Hard Failover Intermittent Crash in HTTP connection manager (https://github.com/couchbase/couchbase-cxx-client/pull/818[#818]).

* https://jira.issues.couchbase.com/browse/CXXCBC-721[CXXCBC-721]:
Added caching of `FeatureNotAvailable` transactions operation failure for `get_replica*` operations (https://github.com/couchbase/couchbase-cxx-client/pull/823[#823]).

* https://jira.issues.couchbase.com/browse/CXXCBC-726[CXXCBC-726]:
Added KV scan timeout to cluster options (https://github.com/couchbase/couchbase-cxx-client/pull/830[#830]).

* https://jira.issues.couchbase.com/browse/CXXCBC-733[CXXCBC-733]:
Fixed build with BoringSSL (https://github.com/couchbase/couchbase-cxx-client/pull/839[#839]).


== Python SDK 4.4 Releases

=== Version 4.4.1 (29 September 2025)

Version 4.4.1 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.4.1
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.4.1/


==== Enhancements

* https://jira.issues.couchbase.com/browse/PYCBC-1699[PYCBC-1699]:
Updated SDK build setup to include {cpp} core changes.

* https://jira.issues.couchbase.com/browse/PYCBC-1703[PYCBC-1703]:
Added Graviton 3 and 4 executors to test pipeline matrices.

==== Fixes

* https://jira.issues.couchbase.com/browse/PYCBC-1705[PYCBC-1705]:
Fixed encryption import order and exceptions.


==== Underlying {cpp} SDK Core Changes

===== New Features

* https://jira.issues.couchbase.com/browse/CXXCBC-699[CXXCBC-699]:
Added support of randomization of bootstrap nodes (https://github.com/couchbase/couchbase-cxx-client/pull/778[#778]).

===== Fixes and Enhancements

* https://jira.issues.couchbase.com/browse/CXXCBC-651[CXXCBC-651]:
Preserve cached node labels after generating report in app telemetry meter (https://github.com/couchbase/couchbase-cxx-client/pull/804[#804]).

* https://jira.issues.couchbase.com/browse/CXXCBC-693[CXXCBC-693]:
Do not return an error if/when `indexDefs` are empty/null.
Instead return w/ an empty list of index definitions (https://github.com/couchbase/couchbase-cxx-client/pull/801[#801]).

* https://jira.issues.couchbase.com/browse/CXXCBC-709[CXXCBC-709]:
Fix `exists()` in transactions `get_multi` result (https://github.com/couchbase/couchbase-cxx-client/pull/787[#787]).

* https://jira.issues.couchbase.com/browse/CXXCBC-715[CXXCBC-715]:
Fixed intermittent crash during hard failover in HTTP connection manager (https://github.com/couchbase/couchbase-cxx-client/pull/817[[#817]).


=== Version 4.4.0 (02 June 2025)

Version 4.4.0 is the minor release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the 4.4.0 release adds support for Vector Search pre-filters, transactional Zone Aware Replica Reads and transactional GetMulti.

[source,bash]
----
$ python3 -m pip install couchbase==4.4.0
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.4.0/


==== Enhancements

* https://jira.issues.couchbase.com/browse/PYCBC-1594[PYCBC-1594],
https://jira.issues.couchbase.com/browse/PYCBC-1647[PYCBC-1647]:
Added support for Zone Aware Read from Replica.

* https://jira.issues.couchbase.com/browse/PYCBC-1634[PYCBC-1634]:
Added support for SDK Telemetry Collection in Server.

* https://jira.issues.couchbase.com/browse/PYCBC-1657[PYCBC-1657],
https://jira.issues.couchbase.com/browse/PYCBC-1685[PYCBC-1685]:
Added support for transactions `ExtGetMulti` (aka Enhanced Read Committed Isolation).

* https://jira.issues.couchbase.com/browse/PYCBC-1668[PYCBC-1668]:
Improved SDK error messages for account lock/unlock feature.

* https://jira.issues.couchbase.com/browse/PYCBC-1676[PYCBC-1676]:
Fixed async query examples to use async (`acouchbase`) API instead of blocking API.

* https://jira.issues.couchbase.com/browse/PYCBC-1678[PYCBC-1678]:
Pinned `setup_requires` cmake version.

* https://jira.issues.couchbase.com/browse/PYCBC-1680[PYCBC-1680]:
Added support for Vector Search pre-filters.

* https://jira.issues.couchbase.com/browse/PYCBC-1681[PYCBC-1681]:
Updated `VectorQuery` validation to raise `InvalidArgumentException` when base64 vector string is empty.

* https://jira.issues.couchbase.com/browse/PYCBC-1682[PYCBC-1682]:
Updated storage backend to be the server default when creating buckets.

==== Fixes

* https://jira.issues.couchbase.com/browse/PYCBC-1674[PYCBC-1674]:
`get_replica_from_preferred_server_group` was trying to access a _ctx attribute on AttemptContextLogic that no longer exists.
This has been fixed, and it no longer raises an `AttributeError`.

* https://jira.issues.couchbase.com/browse/PYCBC-1675[PYCBC-1675]:
CAS is no longer ignored for append/prepend operations.

* https://jira.issues.couchbase.com/browse/PYCBC-1679[PYCBC-1679]:
Console logger is now disabled when the file logger specified.

* https://jira.issues.couchbase.com/browse/PYCBC-1683[PYCBC-1683]:
Fixed search range queries to follow RFC.

* https://jira.issues.couchbase.com/browse/PYCBC-1685[PYCBC-1685]:
Removed timeout logic when waiting for {cpp} core HTTP response.


==== Underlying {cpp} SDK Core Changes

===== New Features

* https://jira.issues.couchbase.com/browse/CXXCBC-605[CXXCBC-605]:
Added custom log callback functionality (https://github.com/couchbase/couchbase-cxx-client/pull/743[#743]).

* https://jira.issues.couchbase.com/browse/CXXCBC-626[CXXCBC-626]:
Application Service Telemetry, for future Server releases
(https://github.com/couchbase/couchbase-cxx-client/pull/712[#712], https://github.com/couchbase/couchbase-cxx-client/pull/719[#719], https://github.com/couchbase/couchbase-cxx-client/pull/739[#739], https://github.com/couchbase/couchbase-cxx-client/pull/750[#750]).

* https://jira.issues.couchbase.com/browse/CXXCBC-654[CXXCBC-654]:
Added `num_vbuckets` to `bucket_settings` (https://github.com/couchbase/couchbase-cxx-client/pull/746[#746]).

* https://jira.issues.couchbase.com/browse/CXXCBC-665[CXXCBC-665]:
The SDK will now always return partial results for `*_all_replica` operations if some `get_replica` requests succeeded (https://github.com/couchbase/couchbase-cxx-client/pull/742[#742]).

* https://jira.issues.couchbase.com/browse/CXXCBC-672[CXXCBC-672]:
Added `add_named_parameter` and `add_positional_parameter` to query/analytics options (https://github.com/couchbase/couchbase-cxx-client/pull/762[#762]).

* https://jira.issues.couchbase.com/browse/CXXCBC-684[CXXCBC-684]:
The SDK now allows the setting of both named and positional parameters for queries --
previously named parameters would be cleared if positional parameters were set (https://github.com/couchbase/couchbase-cxx-client/pull/759[#759]).

===== Fixes and Enhancements

* https://jira.issues.couchbase.com/browse/CXXCBC-646[CXXCBC-646]:
For performance reasons, the bucket configuration is now stored as shared pointer, and this is copied into the handler instead of the entire configuration 
(https://github.com/couchbase/couchbase-cxx-client/pull/715[#715], https://github.com/couchbase/couchbase-cxx-client/pull/720[#720]).

* https://jira.issues.couchbase.com/browse/CXXCBC-657[CXXCBC-657]:
For subdoc operations, if no specs are provided then an `invalid_argument` error is raised instead of crashing on an assert
(https://github.com/couchbase/couchbase-cxx-client/pull/727[#727]).

* https://jira.issues.couchbase.com/browse/CXXCBC-660[CXXCBC-660]:
Fixed potential race condition in the logger (https://github.com/couchbase/couchbase-cxx-client/pull/722[#722]).

* https://jira.issues.couchbase.com/browse/CXXCBC-661[CXXCBC-661]:
Reconnect cluster object on fork (https://github.com/couchbase/couchbase-cxx-client/pull/724[#724]).

* https://jira.issues.couchbase.com/browse/CXXCBC-694[CXXCBC-694]:
Handle case where requestID is missing from query response payload (https://github.com/couchbase/couchbase-cxx-client/pull/768[#768]).

===== Transactions

* https://jira.issues.couchbase.com/browse/CXXCBC-645[CXXCBC-645],
https://jira.issues.couchbase.com/browse/CXXCBC-687[CXXCBC-687],
https://jira.issues.couchbase.com/browse/CXXCBC-689[CXXCBC-689]:
Implemented `get_multi_*` APIs for transactions
(https://github.com/couchbase/couchbase-cxx-client/pull/761[#761], https://github.com/couchbase/couchbase-cxx-client/pull/764[#764], https://github.com/couchbase/couchbase-cxx-client/pull/766[#766]).

* https://jira.issues.couchbase.com/browse/CXXCBC-649[CXXCBC-649]:
Implemented `ExtReplaceBodyWithXattr` (https://github.com/couchbase/couchbase-cxx-client/pull/752[#752]).

* https://jira.issues.couchbase.com/browse/CXXCBC-681[CXXCBC-681]:
No longer storing entire `transaction_get_result` in staged mutations, reducing memory use (https://github.com/couchbase/couchbase-cxx-client/pull/757[#757]).

* https://jira.issues.couchbase.com/browse/CXXCBC-682[CXXCBC-682]:
Transaction replace/insert result now includes post-op content (https://github.com/couchbase/couchbase-cxx-client/pull/756[#756]).

* https://jira.issues.couchbase.com/browse/CXXCBC-683[CXXCBC-683]:
Transactions replace now uses CAS from given `TransactionsGetResult` when the document is a staged insert (https://github.com/couchbase/couchbase-cxx-client/pull/763[#763]).

* https://jira.issues.couchbase.com/browse/CXXCBC-688[CXXCBC-688]:
Don't convert Public API TOF from lambda to Core API's TOF, rely on internal state (https://github.com/couchbase/couchbase-cxx-client/pull/765[#765]).

* https://jira.issues.couchbase.com/browse/CXXCBC-690[CXXCBC-690]:
Don't move `staged_mutation` item when capturing it in `commit_doc` lambdas (https://github.com/couchbase/couchbase-cxx-client/pull/767[#767]).




== Python SDK 4.3 Releases

=== Version 4.3.6 (15 May 2025)

Version 4.3.6 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,console]
----
$ python3 -m pip install couchbase==4.3.6
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.3.6/


==== Enhancements

* https://jira.issues.couchbase.com/browse/PYCBC-1676[PYCBC-1676]:
Fixed async query examples to use async (`acouchbase`) API instead of blocking API.

* https://jira.issues.couchbase.com/browse/PYCBC-1678[PYCBC-1678]:
Pinned `setup_requires` cmake version.

* https://jira.issues.couchbase.com/browse/PYCBC-1681[PYCBC-1681]:
Updated `VectorQuery` validation to raise `InvalidArgumentException` when base64 vector string is empty.

==== Fixes

* https://jira.issues.couchbase.com/browse/PYCBC-1674[PYCBC-1674]:
Fixed transactional `get_replica_from_preferred_server_group` from raising `AttributeError`.

* https://jira.issues.couchbase.com/browse/PYCBC-1675[PYCBC-1675]:
CAS is no longer ignored for append/prepend operations.

* https://jira.issues.couchbase.com/browse/PYCBC-1679[PYCBC-1679]:
Console logger is now disabled when the file logger is specified.

* https://jira.issues.couchbase.com/browse/PYCBC-1683[PYCBC-1683]:
Fixed search range queries to follow RFC.

* https://jira.issues.couchbase.com/browse/PYCBC-1685[PYCBC-1685]:
Removed timeout logic when waiting for {cpp} core HTTP response.


==== Underlying {cpp} SDK Core Changes

===== Fixes

* https://jira.issues.couchbase.com/browse/CXXCBC-666[CXXCBC-666]:
The `pkg-config` file now returns the full path for the lib dir, instead of the relative path (https://github.com/couchbase/couchbase-cxx-client/pull/736[#736]).

* https://jira.issues.couchbase.com/browse/CXXCBC-667[CXXCBC-667]:
Core implementation of prepend/append now encodes the CAS value (https://github.com/couchbase/couchbase-cxx-client/pull/738[#738]).

* https://jira.issues.couchbase.com/browse/CXXCBC-671[CXXCBC-671]:
Updated snappy to support `CMake` `4.0` (https://github.com/couchbase/couchbase-cxx-client/pull/745[#745]).



=== Version 4.3.5 (28 January 2025)

Version 4.3.5 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,console]
----
$ python3 -m pip install couchbase==4.3.5
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.3.5/


==== Enhancements

* https://jira.issues.couchbase.com/browse/PYCBC-1643[PYCBC-1643]:
Updated build system logic when finding Python 3 version.

* https://jira.issues.couchbase.com/browse/PYCBC-1644[PYCBC-1644]:
Updateed GoCAVES download URL to use arm64 version when appropriate (CI improvement).

* https://jira.issues.couchbase.com/browse/PYCBC-1646[PYCBC-1646]:
Migrated transactions to use `transaction_context`.

* https://jira.issues.couchbase.com/browse/PYCBC-1648[PYCBC-1648]:
Added `update_collection` & settings classes to Collection Management API reference.

==== Fixes

* https://jira.issues.couchbase.com/browse/PYCBC-1649[PYCBC-1649]:
Fixed a memory leak when creating `TransactionGetResult`.


==== Underlying {cpp} SDK Core Changes

===== Enhancements

* https://jira.issues.couchbase.com/browse/CXXCBC-638[CXXCBC-638]:
Switched SDK to use bundled `fmtlib` for `spdlog` (https://github.com/couchbase/couchbase-cxx-client/pull/705[#705]).
* https://jira.issues.couchbase.com/browse/CXXCBC-640[CXXCBC-640]:
Debug symbols are no longer forced for release builds (https://github.com/couchbase/couchbase-cxx-client/pull/708[#708]).

===== Fixes

* https://jira.issues.couchbase.com/browse/CXXCBC-633[CXXCBC-633]:
In a case of timeout, when the total deadline of the DNS-SRV request has been reached, the library will now report a timeout error code, and not the latest abort as it was doing.



=== Version 4.3.4 (25 November 2024)

Version 4.3.4 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the 4.3.4 release adds support for Python 3.13 --
see xref:compatibility.adoc#python-version-compat[Python Version Compatibility] for details of supported Python versions.

[source,console]
----
$ python3 -m pip install couchbase==4.3.4
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.3.4/

==== Behavioral Change

The Couchbase Python SDK no longer provides Python 3.8 wheels as Python 3.8 has reached https://peps.python.org/pep-0569/#lifespann[end-of-life].
See xref:project-docs:compatibility.adoc#python-version-compat[Python Version Compatibility] for details on supported Python versions.

==== Enhancements

* https://jira.issues.couchbase.com/browse/PYCBC-1595[PYCBC-1595]:
Added support for Binary Objects in Transactions.

* https://jira.issues.couchbase.com/browse/PYCBC-1613[PYCBC-1613]:
Added Python 3.13 Support.

* https://jira.issues.couchbase.com/browse/PYCBC-1635[PYCBC-1635]:
Removed support for publishing Python 3.8 wheels.

* https://jira.issues.couchbase.com/browse/PYCBC-1639[PYCBC-1639]:
Updated user agent extra passed to {cpp} core.

* https://jira.issues.couchbase.com/browse/PYCBC-1640[PYCBC-1640]:
Added acouchbase utility tests.

==== Fixes

* https://jira.issues.couchbase.com/browse/PYCBC-1631[PYCBC-1631]:
Fixed transaction hangs when logging is set to `DEBUG`.

* https://jira.issues.couchbase.com/browse/PYCBC-1636[PYCBC-1636]:
Fixed acouchbase API to properly handle `BaseException`.


==== Underlying {cpp} SDK Core Changes

===== Fixes

* https://jira.issues.couchbase.com/browse/CXXCBC-611[CXXCBC-611], https://jira.issues.couchbase.com/browse/CXXCBC-612[CXXCBC-612]:
The {cpp} SDK now follows RFC naming for metric operation names (https://github.com/couchbase/couchbase-cxx-client/pull/695[#695]).

* https://jira.issues.couchbase.com/browse/CXXCBC-615[CXXCBC-615]:
The {cpp} SDK now  exposes `insert_raw` and `replace_raw` in the core transactions attempt context (https://github.com/couchbase/couchbase-cxx-client/pull/686[#686]).

* https://jira.issues.couchbase.com/browse/CXXCBC-620[CXXCBC-620]:
Updated core `analytics_link_get_all` to follow the RFC (https://github.com/couchbase/couchbase-cxx-client/pull/687[#687]).

* https://jira.issues.couchbase.com/browse/CXXCBC-624[CXXCBC-624]:
Fixed user agent ID generation (https://github.com/couchbase/couchbase-cxx-client/pull/692[#692]).

* https://jira.issues.couchbase.com/browse/CXXCBC-632[CXXCBC-632]:
A crash on testing against Analytics nodes under rebalance was caused by the assumption that Analytics would always send meta fields in its response.
This has now been fixed, and the behoavior should not recur (https://github.com/couchbase/couchbase-cxx-client/pull/699[#699]).



=== Version 4.3.3 (22 October 2024)

Version 4.3.3 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,console]
----
$ python3 -m pip install couchbase==4.3.3
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.3.3/

==== Behavioral Change

The Couchbase Python SDK will stop providing Python 3.8 wheels with the next release (4.3.4) as Python 3.8 has reached https://peps.python.org/pep-0569/#lifespann[end-of-life].
See xref:project-docs:compatibility.adoc#python-version-compat[Python Version Compatibility] for details on supported Python versions.

==== Enhancements

* https://jira.issues.couchbase.com/browse/PYCBC-1456[PYCBC-1456]:
Ensure SDK encodes URIs.
* https://jira.issues.couchbase.com/browse/PYCBC-1619[PYCBC-1619]:
Added ability to use {cpp} core file logger.
* https://jira.issues.couchbase.com/browse/PYCBC-1625[PYCBC-1625]:
Updated multi methods to `COMMITTED`.

==== Fixes

* https://jira.issues.couchbase.com/browse/PYCBC-1569[PYCBC-1569]:
Added mechanism to do binary increment/decrement without initial value.
* https://jira.issues.couchbase.com/browse/PYCBC-1628[PYCBC-1628]:
Fixed typo in `InvalidArgumentException` message when invalid authentication `kwargs` are provided.
* https://jira.issues.couchbase.com/browse/PYCBC-1629[PYCBC-1629]:
Fixed subdocument `array_addunique` to follow the https://github.com/couchbaselabs/sdk-rfcs/blob/master/rfc/0053-sdk3-crud.md#mutatein[RFC].


==== Underlying {cpp} SDK Core Changes

===== Enhancements

* http://jira.issues.couchbase.com/browse/CXXCBC-582[CXXCBC-552]:
Cleaned up network selection options (https://github.com/couchbase/couchbase-cxx-client/pull/677[#677], https://github.com/couchbase/couchbase-cxx-client/pull/682[#682]).
Added cluster labels and system tag to spans.
Added cluster labels, keyspace, and outcome to metrics.

===== Fixes

* http://jira.issues.couchbase.com/browse/CXXCBC-311[CXXCBC-311]:
Ensure SDK encodes URIs (https://github.com/couchbase/couchbase-cxx-client/pull/674[#674]).
* http://jira.issues.couchbase.com/browse/CXXCBC-599[CXXCBC-599]:
Updated allowed connection string options (https://github.com/couchbase/couchbase-cxx-client/pull/668[#668]).
* http://jira.issues.couchbase.com/browse/CXXCBC-606[CXXCBC-606]:
Fixed detection of dysfunctional node (https://github.com/couchbase/couchbase-cxx-client/pull/673[#673]).
* http://jira.issues.couchbase.com/browse/CXXCBC-614[CXXCBC-614]:
Fixed memory leak in `observe_poll` (https://github.com/couchbase/couchbase-cxx-client/pull/679[#679]).



=== Version 4.3.2 (24 September 2024)

Version 4.3.2 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the 4.3.2 release adds support for Python 3.12 --
see xref:compatibility.adoc#python-version-compat[Python Version Compatibility] for details of supported Python versions.

[source,console]
----
$ python3 -m pip install couchbase==4.3.2
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.3.2/

==== Behavioral Change

The Couchbase Python SDK will soon stop providing Python 3.8 wheels as Python 3.8 reaches https://peps.python.org/pep-0569/#lifespann[end-of-life] in October 2024.
See xref:compatibility.adoc#python-version-compat[Python Version Compatibility] for details of supported Python versions.

==== Enhancements

* https://jira.issues.couchbase.com/browse/PYCBC-1563[PYCBC-1563]:
Added Python 3.12 Support.

==== Underlying {cpp} SDK Core Changes

===== Fixes

* http://jira.issues.couchbase.com/browse/CXXCBC-577[CXXCBC-577],
http://jira.issues.couchbase.com/browse/CXXCBC-552[CXXCBC-552], &
http://jira.issues.couchbase.com/browse/CXXCBC-576[CXXCBC-576]:
See xref:cxx-sdk:project-docs:sdk-release-notes.adoc#version-1-0-2-23-september-2024[{cpp} 1.0.2 release notes].



=== Version 4.3.1 (26 August 2024)

Version 4.3.1 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,console]
----
$ python3 -m pip install couchbase==4.3.1
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.3.1/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1612[PYCBC-1612]:
Fixed multi-mutation operations to honor durability when passed in options.


==== Underlying {cpp} SDK Core Changes

===== Enhancements

* Improve logging of DNS client
(https://github.com/couchbase/couchbase-cxx-client/pull/634[#634]).

* https://issues.couchbase.com/browse/CXXCBC-568/[CXXCBC-568]:
Cancel deferred operations when closing HTTP session manager
(https://github.com/couchbase/couchbase-cxx-client/pull/643[#643]).

===== Fixes

* https://issues.couchbase.com/browse/CXXCBC-531/[CXXCBC-531]:
Fixed memory leak in range scan implementation
(https://github.com/couchbase/couchbase-cxx-client/pull/645[#645],
https://github.com/couchbase/couchbase-cxx-client/pull/610[#610]).

* https://issues.couchbase.com/browse/CXXCBC-572/[CXXCBC-572]:
Always initialize service_type
(https://github.com/couchbase/couchbase-cxx-client/pull/610[#610]).

* https://issues.couchbase.com/browse/CXXCBC-569/[CXXCBC-569]:
Resolved cycle in shared pointers for `transaction_context`
(https://github.com/couchbase/couchbase-cxx-client/pull/641[#641]).

* https://issues.couchbase.com/browse/CXXCBC-550/[CXXCBC-550]:
Fixed use-after-move issue in command handler
(https://github.com/couchbase/couchbase-cxx-client/pull/628[#628]).

* Fixed behaviour when reading is complete before returning HTTP streaming resp
(https://github.com/couchbase/couchbase-cxx-client/pull/624[#624]).



=== Version 4.3.0 (27 June 2024)

Version 4.3.0 is next minor release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the 4.3.0 release adds support for base64 encoded vector types when using the SDK with Couchbase Server 7.6.2.

[source,console]
----
$ python3 -m pip install couchbase==4.3.0
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.3.0/


==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1596[PYCBC-1596]:
Fixed `AnalyticsStatus` Enum values.

* https://issues.couchbase.com/browse/PYCBC-1603[PYCBC-1603]:
Fixed `VectorQuery` validation to prevent empty `field_name`.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1597[PYCBC-1597]:
Added Support for base64 encoded vector types.

* https://issues.couchbase.com/browse/PYCBC-1588[PYCBC-1588]:
Added support for importing FTS index from JSON.


==== Underlying {cpp} SDK Core Changes

===== Enhancements

* https://issues.couchbase.com/browse/CXXCBC-381[CXXCBC-381]:
Updated `transactions_context` and `attempt_context` to use `std::shared_ptr` (https://github.com/couchbaselabs/couchbase-cxx-client/pull/590[#590]).

===== Fixes

* https://issues.couchbase.com/browse/CXXCBC-445[CXXCBC-445]:
Updated HTTP session logic to return `request_canceled` on IO error (https://github.com/couchbaselabs/couchbase-cxx-client/pull/568[#568]).

* https://issues.couchbase.com/browse/CXXCBC-511[CXXCBC-511]:
Updated HTTP session logic to prevent use of session if idle timer has expired (https://github.com/couchbaselabs/couchbase-cxx-client/pull/565[#565]).

* https://issues.couchbase.com/browse/CXXCBC-517[CXXCBC-517]:
Added HTTP session retries when client fails to resolve hostnames (https://github.com/couchbaselabs/couchbase-cxx-client/pull/589[#589]).

* https://issues.couchbase.com/browse/CXXCBC-518[CXXCBC-518]:
Fixed preferred node logic to handle alternate addresses (https://github.com/couchbaselabs/couchbase-cxx-client/pull/574[#574]).

* https://issues.couchbase.com/browse/CXXCBC-523[CXXCBC-523]:
Cleaned up config log output when `dump_configuration` is enabled (https://github.com/couchbaselabs/couchbase-cxx-client/pull/577[#577]).

* Fixed config poll to skip config fetch if bucket does not have any sessions (https://github.com/couchbaselabs/couchbase-cxx-client/pull/573[#573]).

* Cleaned up `attempt_context_impl` implementation (https://github.com/couchbaselabs/couchbase-cxx-client/pull/586[#586]).


== Python SDK 4.2 Releases

=== Version 4.2.1 (18 April 2024)

Version 4.2.1 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,console]
----
$ python3 -m pip install couchbase==4.2.1
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.2.1/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1575[PYCBC-1575]:
Added missing logic to handle alternate addresses when bootstrapping.

* https://issues.couchbase.com/browse/PYCBC-1532[PYCBC-1532],
https://issues.couchbase.com/browse/PYCBC-1566[PYCBC-1566],
https://issues.couchbase.com/browse/PYCBC-1589[PYCBC-1589]:
Fixed floating point exception if recieved config with empty vBucket map.

* https://issues.couchbase.com/browse/PYCBC-1590[PYCBC-1590]:
Fixed Python logger shutdown process.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1584[PYCBC-1584]:
Added support for scoped eventing functions.


==== Underlying {cpp} SDK Core Changes

===== Enhancements

* https://issues.couchbase.com/browse/CXXCBC-470[CXXCBC-470]:
Distinguish between 'unset' and 'off' query_profile (https://github.com/couchbaselabs/couchbase-cxx-client/pull/551[#551]).

* https://issues.couchbase.com/browse/CXXCBC-489[CXXCBC-489]:
Added support for scoped eventing functions (https://github.com/couchbaselabs/couchbase-cxx-client/pull/548[#548], (https://github.com/couchbaselabs/couchbase-cxx-client/pull/554[#554])).

===== Fixes

* https://issues.couchbase.com/browse/CXXCBC-30[CXXCBC-30]:
Fixed inconsistent behavior when using subdoc opcodes (https://github.com/couchbaselabs/couchbase-cxx-client/pull/559[#559]).

* https://issues.couchbase.com/browse/CXXCBC-487[CXXCBC-487]:
Added logic during bootstrap to check if alternate addressing is being used (https://github.com/couchbaselabs/couchbase-cxx-client/pull/545[#545]).

* https://issues.couchbase.com/browse/CXXCBC-492[CXXCBC-492]:
Updated collection_component get_collection_id to use retry strategy (https://github.com/couchbaselabs/couchbase-cxx-client/pull/552[#552]).

* https://issues.couchbase.com/browse/CXXCBC-494[CXXCBC-494]:
Fixed memory issue in range scan implementation (https://github.com/couchbaselabs/couchbase-cxx-client/pull/549[#549]).

* https://issues.couchbase.com/browse/CXXCBC-503[CXXCBC-503]:
Added logic to ignore configuration if it contains an empty vBucket map (https://github.com/couchbaselabs/couchbase-cxx-client/pull/556[#556], https://github.com/couchbaselabs/couchbase-cxx-client/pull/558[#558]).


=== Version 4.2.0 (14 March 2024)

Version 4.2.0 is second minor release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the 4.2.0 release adds support for Vector Search, KV Range Scans, and faster failover when using the SDK with Couchbase Server 7.6.0.

[source,console]
----
$ python3 -m pip install couchbase==4.2.0
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.2.0/

==== Known Issues

* https://issues.couchbase.com/browse/CXXCBC-447[CXXCBC-447]:
This version of the SDK will not be able to connect to a cluster utilizing alternate addressing.
The recommendation is to wait to upgrade to a version of the {name-sdk} that contains {cpp} SDK 1.0.0-dp.15 (or later).

==== Behavioral Change

It's important to use `Cluster.searchQuery()` / `Cluster.search()` for global indexes, and `Scope.search()` for scoped indexes.
Method `Scope.search_query()` is now deprecated and will be removed in a future release.
Method `Scope.search_query()` will _not_ work with scoped indexes.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1548[PYCBC-1548]:
Added support for Vector Search.

* https://issues.couchbase.com/browse/PYCBC-1565[PYCBC-1565]:
Updated {cpp} core for transactions metadata bucket improvements.

* https://issues.couchbase.com/browse/PYCBC-1572[PYCBC-1572]:
Updated search API for SDK API 3.5 support.
Included deprecation of `scope.search_query()`.

==== Underlying {cpp} SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-336[CXXCBC-336]:
Updated DNS config to not fallback to 8.8.8.8 if SDK cannot obtain system DNS server (https://github.com/couchbaselabs/couchbase-cxx-client/pull/533[#533]).

* https://issues.couchbase.com/browse/CXXCBC-461[CXXCBC-461]:
Updated ping operation to not send to nodes that have not completed bootstrap (https://github.com/couchbaselabs/couchbase-cxx-client/pull/540[#540]).

* https://issues.couchbase.com/browse/CXXCBC-462[CXXCBC-462]:
Fixed hanging when specifying a custom metadata collection via the public API & expose errors (https://github.com/couchbaselabs/couchbase-cxx-client/pull/532[#532]).

* https://issues.couchbase.com/browse/CXXCBC-479[CXXCBC-479]:
Fixed capabilities check for replica `LookupIn` operations (https://github.com/couchbaselabs/couchbase-cxx-client/pull/537[#537]).

* https://issues.couchbase.com/browse/CXXCBC-480[CXXCBC-480]:
Fixed capabilities check for replica LookupIn operations (https://github.com/couchbaselabs/couchbase-cxx-client/pull/539[#539]).

* https://issues.couchbase.com/browse/CXXCBC-481[CXXCBC-481]:
Fixed potential crash when parsing search result hits (https://github.com/couchbaselabs/couchbase-cxx-client/pull/541[#541]).

* https://issues.couchbase.com/browse/CXXCBC-482[CXXCBC-482]:
Update range scan orchestrator to use best effort retry strategy by default (https://github.com/couchbaselabs/couchbase-cxx-client/pull/542[#542]).



== Python SDK 4.1 Releases

=== Version 4.1.12 (1 March 2024)

Version 4.1.12 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,console]
----
$ python3 -m pip install couchbase==4.1.12
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.12/

==== Known Issues

* https://issues.couchbase.com/browse/CXXCBC-447[CXXCBC-447]:
This version of the SDK will not be able to connect to a cluster utilizing alternate addressing.
The recommendation is to wait to upgrade to a version of the {name-sdk} that contains {cpp} SDK 1.0.0-dp.15 (or later).

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1555[PYCBC-1555]:
Fixed bootstrap `select_bucket` logic to handle non-KV node.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1375[PYCBC-1375]:
Updated Query Index Management Create Index Key Encoding.

* https://issues.couchbase.com/browse/PYCBC-1550[PYCBC-1550]:
Added support for Scoped Search Indexes.

* https://issues.couchbase.com/browse/PYCBC-1523[PYCBC-1523]:
Updated configuration logic when 0xd response is received.

* https://issues.couchbase.com/browse/PYCBC-1525[PYCBC-1525]:
Added support for `LookupIn` and `MutateIn` macros.

* https://issues.couchbase.com/browse/PYCBC-1560[PYCBC-1560]:
Updated `ViewQueryOptions` to include `full_set` and `raw` options.

==== Underlying {cpp} SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-284[CXXCBC-284]:
Updated config polling to not use session that is not bootstrapped (https://github.com/couchbaselabs/couchbase-cxx-client/pull/528[#528]).

* https://issues.couchbase.com/browse/CXXCBC-345[CXXCBC-345]:
Added range scan improvements and resolved concurrency issues (https://github.com/couchbaselabs/couchbase-cxx-client/pull/525[#525]).

* https://issues.couchbase.com/browse/CXXCBC-421[CXXCBC-421]:
Updated query operation to return `feature_not_available` if query preserve expiry is specified but is not supported on the server(https://github.com/couchbaselabs/couchbase-cxx-client/pull/510[#510]).

* https://issues.couchbase.com/browse/CXXCBC-431[CXXCBC-431]:
Added check for history retention bucket capability in collection create/update (https://github.com/couchbaselabs/couchbase-cxx-client/pull/502[#502], https://github.com/couchbaselabs/couchbase-cxx-client/pull/505[#505]).

* https://issues.couchbase.com/browse/CXXCBC-447[CXXCBC-447]:
Updated bootstrap logic to use addresses from the config to bootstrap bucket (https://github.com/couchbaselabs/couchbase-cxx-client/pull/516[#516]).

* https://issues.couchbase.com/browse/CXXCBC-450[CXXCBC-450]:
Updated bootstrap logic to reset bootstrap handler before re-bootstrap (https://github.com/couchbaselabs/couchbase-cxx-client/pull/524[#524]).
** We do not want any actions from old bootstrap handler once the session decided to re-bootstrap. For example, bucket could not be selected, but we might still get configuration responses before socket reset.

* https://issues.couchbase.com/browse/CXXCBC-452[CXXCBC-452]:
Updated capabilities and fail fast when selected feature is not available. (https://github.com/couchbaselabs/couchbase-cxx-client/pull/522[#522], https://github.com/couchbaselabs/couchbase-cxx-client/pull/513[#513]).

* https://issues.couchbase.com/browse/CXXCBC-456[CXXCBC-456]:
Updated configuration logic when 0x0d (`EConfigOnly`) status code is received to have the SDK request new configuration and send current operation to retry orchestrator (https://github.com/couchbaselabs/couchbase-cxx-client/pull/523[#523]).


=== Version 4.1.11 (1 February 2024)

Version 4.1.11 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.11
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.11/

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1549[PYCBC-1549]:
Added support for `maxTTL` value of -1 for collection "no expiry".

==== Underlying {cpp} SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-284[CXXCBC-284]:
Reduced network traffic when polling for cluster configuration (https://github.com/couchbaselabs/couchbase-cxx-client/pull/504[#504]).
* https://issues.couchbase.com/browse/CXXCBC-421[CXXCBC-421]:
Updated query response to return `feature_not_available` when query preserve expiry is not supported (https://github.com/couchbaselabs/couchbase-cxx-client/pull/510[#510]).
* https://issues.couchbase.com/browse/CXXCBC-422[CXXCBC-422]:
Added insufficient credentials error code to common query error code conversion (https://github.com/couchbaselabs/couchbase-cxx-client/pull/511[#511]).
* https://issues.couchbase.com/browse/CXXCBC-431[CXXCBC-431]:
Added check for history retention bucket capability for collection create/update (https://github.com/couchbaselabs/couchbase-cxx-client/pull/502[#502], https://github.com/couchbaselabs/couchbase-cxx-client/pull/505[#505]).
* https://issues.couchbase.com/browse/CXXCBC-446[CXXCBC-446]:
Improved log formatting (https://github.com/couchbaselabs/couchbase-cxx-client/pull/506[#506], https://github.com/couchbaselabs/couchbase-cxx-client/pull/508[#508], https://github.com/couchbaselabs/couchbase-cxx-client/pull/509[#509]).


=== Version 4.1.10 (3 January 2024)

Version 4.1.10 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.10
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.10/

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1499[PYCBC-1499]:
Added improvements for Faster Failover and Config Push.

* https://issues.couchbase.com/browse/PYCBC-1545[PYCBC-1545]:
Added support for new KV error code to raise `DocumentNotLockedException`.

==== Underlying {cpp} SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-100[CXXCBC-100]:
Added support for using a timeout with `ping` operation (https://github.com/couchbaselabs/couchbase-cxx-client/pull/486[#486]).
* https://issues.couchbase.com/browse/CXXCBC-368[CXXCBC-368]:
Added support for subscribing to clustermap notifications to speedup failover (https://github.com/couchbaselabs/couchbase-cxx-client/pull/490[#490]).
* https://issues.couchbase.com/browse/CXXCBC-391[CXXCBC-391]:
Fixed transactions API inconsistencies (https://github.com/couchbaselabs/couchbase-cxx-client/pull/482[#482]).
* https://issues.couchbase.com/browse/CXXCBC-403[CXXCBC-403]:
Updated `not_my_vbucket` KV response to allow retries (https://github.com/couchbaselabs/couchbase-cxx-client/pull/480[#480]).
* https://issues.couchbase.com/browse/CXXCBC-404[CXXCBC-404]:
Fixed `unlock` operations to expose `KV_LOCKED` status as `cas_mismatch` (https://github.com/couchbaselabs/couchbase-cxx-client/pull/479[#479]).
* https://issues.couchbase.com/browse/CXXCBC-409[CXXCBC-409]:
Added handling for `index does not exist` query error (https://github.com/couchbaselabs/couchbase-cxx-client/pull/492[#492]).
* https://issues.couchbase.com/browse/CXXCBC-419[CXXCBC-419]:
Updated MCBP protocol parser to start with clean state (https://github.com/couchbaselabs/couchbase-cxx-client/pull/496[#496]).


=== Version 4.1.9 (14 November 2023)

Version 4.1.9 is the next patch release of the fourth generation Python SDK, bringing a number of improvements. 
Most notably the 4.1.9 release removes the `OpenSSL` dependency for published wheels and added _musllinux_ wheels for supported alpine environments.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.9
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.9/

==== Behavioral Change

The Couchbase Python SDK now publishes wheels that statically link against `BoringSSL`.  
The change removes the `OpenSSL` requirement from the SDK when using a published wheel. 
If building the SDK from source, the build will default to dynamically linking with the system provided `OpenSSL`.  
Build options are available if wanting to build from source and statically link against `BoringSSL`.  
Also, published wheels dynamically link against `stdlibs` where previously the default was to statically link against `stdlibs`.  
Build options are available if wanting to build from source and statically link against `stdlibs`.

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1538[PYCBC-1538]:
Fixed `get` with projections to not fail with `InvalidArgumentException` when projecting on more than 16 fields.

* https://issues.couchbase.com/browse/PYCBC-1534[PYCBC-1534]:
Fixed `MutateIn` replace operation to not fail if path is empty.

* https://issues.couchbase.com/browse/PYCBC-1531[PYCBC-1531]:
Fixed `CollectionQueryIndexManager` to raise `InvalidArgumentException` when `scope_name` or `collection_name` options are set.

* https://issues.couchbase.com/browse/PYCBC-1521[PYCBC-1521]:
Fixed streaming APIs to use cluster timeout values from `ClusterTimeoutOptions` if provided.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1536[PYCBC-1536]:
Updated MANIFEST.in to only include necessary files for source install.

* https://issues.couchbase.com/browse/PYCBC-1518[PYCBC-1520],
https://issues.couchbase.com/browse/PYCBC-1520[PYCBC-1518]:
Updated published wheels to statically link against BoringSSL.

* https://issues.couchbase.com/browse/PYCBC-1515[PYCBC-1515]:
Added support for bucket settings for 'no dedup' feature.

* https://issues.couchbase.com/browse/PYCBC-1512[PYCBC-1512]:
Reduced default HTTP Idle Timeout.

* https://issues.couchbase.com/browse/PYCBC-1495[PYCBC-1495]:
Updated wheels and build to dynamically link against stdlibs by default.

==== Underlying {cpp} SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-387[CXXCBC-387]:
Optimising tags for `noop_tracer` and cache formatted `mbcp_session` endpoints (https://github.com/couchbaselabs/couchbase-cxx-client/pull/461[#461], https://github.com/couchbaselabs/couchbase-cxx-client/pull/462[#462], https://github.com/couchbaselabs/couchbase-cxx-client/pull/464[#464]).
* https://issues.couchbase.com/browse/CXXCBC-383[CXXCBC-383]:
Map `subdoc_doc_too_deep` KV status to `path_too_deep` error code (https://github.com/couchbaselabs/couchbase-cxx-client/pull/455[#455]).
* https://issues.couchbase.com/browse/CXXCBC-377[CXXCBC-377]:
Implement `ExtParallelUnstaging` in transactions (https://github.com/couchbaselabs/couchbase-cxx-client/pull/457[#457]).
* https://issues.couchbase.com/browse/CXXCBC-386[CXXCBC-386]:
Allow option to statically link against BoringSSL (https://github.com/couchbaselabs/couchbase-cxx-client/pull/458[#458], https://github.com/couchbaselabs/couchbase-cxx-client/pull/465[#465], https://github.com/couchbaselabs/couchbase-cxx-client/pull/471[#471], https://github.com/couchbaselabs/couchbase-cxx-client/pull/474[#474], https://github.com/couchbaselabs/couchbase-cxx-client/pull/478[#478]).
* https://issues.couchbase.com/browse/CXXCBC-376[CXXCBC-376]:
Revisit what 'create' and 'update' bucket operations send to the server. 
Make optional bucket settings fields optional, and do not send anything unless the settings explicitly specified (https://github.com/couchbaselabs/couchbase-cxx-client/pull/451[#451]).
* https://issues.couchbase.com/browse/CXXCBC-374[CXXCBC-374]:
Return 'bucket_exists' error when the bucket already exists during 'create' operation (https://github.com/couchbaselabs/couchbase-cxx-client/pull/449[#449]).
* https://issues.couchbase.com/browse/CXXCBC-359[CXXCBC-359]:
Reduced the default timeout for idle HTTP connections to 1 second. 
The previous default (4.5 seconds) was too close to the 5-second server-side timeout, and could lead to spurious request failures (https://github.com/couchbaselabs/couchbase-cxx-client/pull/448[#448]).
* https://issues.couchbase.com/browse/CXXCBC-367[CXXCBC-367];
https://issues.couchbase.com/browse/CXXCBC-370[CXXCBC-370]:
Added history retention settings to buckets/collection management (https://github.com/couchbaselabs/couchbase-cxx-client/pull/446[#446]).
* https://issues.couchbase.com/browse/CXXCBC-119[CXXCBC-119]:
Return booleans for subdocument 'exists' operation instead of error code (https://github.com/couchbaselabs/couchbase-cxx-client/pull/444[#444], https://github.com/couchbaselabs/couchbase-cxx-client/pull/452[#452]).
* Add more information to diagnose timeouts on NMVB responses (https://github.com/couchbaselabs/couchbase-cxx-client/pull/475[#475]).


=== Version 4.1.8 (25 August 2023)

Version 4.1.8 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.8
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.8/

==== Behavioral Change

The Couchbase Python SDK no longer provides Python 3.7 wheels as Python 3.7 has reached https://peps.python.org/pep-0537/#lifespan[end-of-life]. See https://docs.couchbase.com/python-sdk/current/project-docs/compatibility.html#python-version-compat[Python Version Compatibility] for details.

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1514[PYCBC-1514]:
Fixed parsing of `LookupIn` options if provided for lookup-in operations.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1497[PYCBC-1497]:
Added support for Sub-Document Read from Replica.

==== Underlying {cpp} SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-362[CXXCBC-362]:
Removed node hostname port stripping logic from config parsing (https://github.com/couchbaselabs/couchbase-cxx-client/pull/438[#438]).
* https://issues.couchbase.com/browse/CXXCBC-340[CXXCBC-340]:
Added support for Query Read from Replica (https://github.com/couchbaselabs/couchbase-cxx-client/pull/435[#435]).
* https://issues.couchbase.com/browse/CXXCBC-341[CXXCBC-341],
https://issues.couchbase.com/browse/CXXCBC-365[CXXCBC-365]:
Added support for Sub-Document Read from Replica (https://github.com/couchbaselabs/couchbase-cxx-client/pull/436[#436], https://github.com/couchbaselabs/couchbase-cxx-client/pull/441[#441], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/443[#443]).


=== Version 4.1.7 (8 August 2023)

Version 4.1.7 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.7
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.7/

==== Behavioral Change

Since Python 3.7 has reached https://peps.python.org/pep-0537/#lifespan[end-of-life], the Couchbase Python SDK will no longer provide Python 3.7 wheels in future releases (>4.1.7). See https://docs.couchbase.com/python-sdk/current/project-docs/compatibility.html#python-version-compat[Python Version Compatibility] for details.

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1502[PYCBC-1502]:
Added `PasswordAuthenticator` validation.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1496[PYCBC-1496]:
Added support for Query with Read from Replica.

* https://issues.couchbase.com/browse/PYCBC-1419[PYCBC-1419]:
Added support for Native KV Range Scans.

* https://issues.couchbase.com/browse/PYCBC-1505[PYCBC-1504];
https://issues.couchbase.com/browse/PYCBC-1505[PYCBC-1505]:
Updated API documentation to provide correct information on `LockMode`.

* https://issues.couchbase.com/browse/PYCBC-1510[PYCBC-1510]:
Updated CONTRIBUTING.md to improve contributing guidelines.

* https://issues.couchbase.com/browse/PYCBC-1095[PYCBC-1095]:
Added Subdoc mutate-in deletions with a blank path.

==== Underlying {cpp} SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-349[CXXCBC-349]:
Allow to pass trust certificate by value (https://github.com/couchbaselabs/couchbase-cxx-client/pull/430[#430]).
** The change affects TLS v1.0 and v1.1 which are now disabled by default.
* https://issues.couchbase.com/browse/CXXCBC-343[CXXCBC-343]:
Continue bootsrap if DNS-SRV resolution fails (https://github.com/couchbaselabs/couchbase-cxx-client/pull/422[#422]).
* https://issues.couchbase.com/browse/CXXCBC-340[CXXCBC-340]:
Support Query with Read from Replica (https://github.com/couchbaselabs/couchbase-cxx-client/pull/429[#429]).
* https://issues.couchbase.com/browse/CXXCBC-339[CXXCBC-339]:
Disabled older TLS protocols (https://github.com/couchbaselabs/couchbase-cxx-client/pull/418[#418]).
* https://issues.couchbase.com/browse/CXXCBC-333[CXXCBC-333]:
Fixed parsing 'resolv.conf' on Linux. (https://github.com/couchbaselabs/couchbase-cxx-client/pull/416[#416]).
** The library might not ignore trailing characters when reading nameserver address from the file.
* https://issues.couchbase.com/browse/CXXCBC-242[CXXCBC-242]:
SDK Support for Native KV Range Scans (https://github.com/couchbaselabs/couchbase-cxx-client/pull/419[#419], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/423[#423], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/424[#424], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/426[#426], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/428[#428], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/431[#431], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/432[#432],  
https://github.com/couchbaselabs/couchbase-cxx-client/pull/433[#433],  
https://github.com/couchbaselabs/couchbase-cxx-client/pull/434[#434]).


=== Version 4.1.6 (13 July 2023)

Version 4.1.6 is the sixth patch release of the fourth generation Python SDK, bringing a number of improvements. Most notably the 4.1.6 release adds support for Python 3.11 and significantly reduces the size of published _manylinux_ wheels.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.6
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.6/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1500[PYCBC-1500]:
Added `max_expiry` to `CollectionSpec` for collections returned in `get_all_scopes()` result.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1473[PYCBC-1473]:
Added Support for Python 3.11.

* https://issues.couchbase.com/browse/PYCBC-1459[PYCBC-1459]:
Reduced size of manylinux wheels.

* https://issues.couchbase.com/browse/PYCBC-1494[PYCBC-1494]:
Updated API docs to include binary `multiOptions`.

* https://issues.couchbase.com/browse/PYCBC-1498[PYCBC-1498]:
Updated connection tests to only use valid mixed environment format.


=== Version 4.1.5 (8 June 2023)

Version `4.1.5` is the fifth patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.5
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.5/

==== Behavioral Change

Accessing content from an Exist operation with the `LookupInResult`'s `content_as` method now returns a boolean.
This boolean is `True` if the path exists, `False` otherwise. 
Prior to this change the SDK raised a `DocumentNotFoundException` if the path existed or `PathNotFoundException` if the path didn't exist.
The behavioral change aligns the Python SDK with Couchbase's https://github.com/couchbaselabs/sdk-rfcs/blob/master/rfc/0053-sdk3-crud.md[CRUD RFC].

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1480[PYCBC-1480]:
Fixed subdocument read operations to allow for null values.

* https://issues.couchbase.com/browse/PYCBC-1486[PYCBC-1486]:
Fixed broken imports for search `GeoBoundingBoxQuery`, `GeoDistanceQuery`, and `GeoPolygonQuery`.

* https://issues.couchbase.com/browse/PYCBC-1487[PYCBC-1487]:
Updated Transcoders to be able to decode value when `flags=0`.

* https://issues.couchbase.com/browse/PYCBC-1490[PYCBC-1490]:
Fixed `InternalServerFailureException` when executing a `Regex` Search query.

* https://issues.couchbase.com/browse/PYCBC-1493[PYCBC-1493]:
Updated search operations to correctly pass MutationState to {cpp} core.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1488[PYCBC-1488]:
Added `dump_configuration` to `ClusterOptions`.

* https://issues.couchbase.com/browse/PYCBC-1479[PYCBC-1479]:
Bundled Mozilla certificates with the library.
Source: https://curl.se/docs/caextract.html. 
Use the `disable_mozilla_ca_certificates` connection string option to disable the bundled certificates.
See https://docs.couchbase.com/python-sdk/current/howtos/managing-connections.html#ssl[Secure Connections] for more details.


==== Underlying {cpp} SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-328[CXXCBC-328]:
Fix socket reconnection during rebalance process
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/406[#406]).
** Several improvements have been implemented to make the library resilient to rapid topology changes when both DNS-SRV bootstrap is being used along with alternative addresses. 
The changes include:
*** Taking into account alternative hostname and ports during detection of added/removed nodes on configuration update.
*** Replacing node index tracking with hostname/port matching when restarting the connections -- 
this way the library ensures that no duplicate connections will be left, or live connections replaced by restarted session.
*** Improved logging of critical events during rebalance: restarting, preservation, and removing connections.


=== Version 4.1.4 (9 May 2023)

Version `4.1.4` is the fourth patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.4
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.4/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1469[PYCBC-1469]:
Added check to determine if Python interpreter is finalizing prior to logging.

* https://issues.couchbase.com/browse/PYCBC-1471[PYCBC-1471]:
Fixed `acouchbase` streaming API blocking behavior while when executing queries.

* https://issues.couchbase.com/browse/PYCBC-1474[PYCBC-1474]:
Fixed transaction error handling.

* https://issues.couchbase.com/browse/PYCBC-1475[PYCBC-1475]:
Updated exception classes to allow first positional arg to be a string message.

* https://issues.couchbase.com/browse/PYCBC-1477[PYCBC-1477]:
Fixed potential crash in certain scenarios that use `MutationState`.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1468[PYCBC-1468]:
Added replica read operations to API docs.

* https://issues.couchbase.com/browse/PYCBC-1472[PYCBC-1472]:
Updated API Docs to indicate expiry option should be a timedelta.

* https://issues.couchbase.com/browse/PYCBC-1478[PYCBC-1478]:
Added missing bootstrap timeouts to WAN Config Profile.

==== Underlying {cpp} SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-31[CXXCBC-31]:
Allow the use of schemaless connection strings (e.g. `"cb1.example.com,cb2.example.com"`)
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/394[#394]).

* https://issues.couchbase.com/browse/CXXCBC-320[CXXCBC-320]:
Negative expiry in atr was leaving docs in a stuck state -- this has been fixed, with expiry atr now becoming an `int32_t`
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/393[#393]).

* https://issues.couchbase.com/browse/CXXCBC-318[CXXCBC-318]:
Always try TCP if UDP fails in DNS-SRV resolver
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/390[#390]).

* https://issues.couchbase.com/browse/CXXCBC-145[CXXCBC-145]:
Search query request raw option now used
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/380[#380]).

* https://issues.couchbase.com/browse/CXXCBC-144[CXXCBC-144]:
Search query on collections now no longer requires `scope_name`, as it can be inferred from the index
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/379[#379]).


=== Version 4.1.3 (9 March 2023)

Version `4.1.3` is the third patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.3
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.3/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1443[PYCBC-1443]:
Fixed ssl import error.

* https://issues.couchbase.com/browse/PYCBC-1446[PYCBC-1446]:
Updated API Documentation.

* https://issues.couchbase.com/browse/PYCBC-1455[PYCBC-1455]:
Fixed build issue for Fedora 37 (gcc 12).

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1431[PYCBC-1431]:
Updated the SDK to handle new `query_context` changes.

* https://issues.couchbase.com/browse/PYCBC-1444[PYCBC-1444]:
Improved CertificateAuthenticator parameter validation.

* https://issues.couchbase.com/browse/PYCBC-1445[PYCBC-1445]:
Updated the SDK to only populate `allowed_sasl_mechanisms` if user explicitly chooses.


=== Version 4.1.2 (9 February 2023)

Version `4.1.2` is the second patch release of the fourth generation Python SDK, bringing a number of improvements. Most notably the `4.1.2` release provides improved performance for key-value operations.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.2
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.2/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1433[PYCBC-1433]:
Fixed initialization of legacy durability options in {cpp} bindings.

* https://issues.couchbase.com/browse/PYCBC-1434[PYCBC-1434]:
Added Python SDK and Python version to {cpp} `user_agent` option.

* https://issues.couchbase.com/browse/PYCBC-1441[PYCBC-1441]:
Fixed inconsistencies when handling of `MutationState` in streaming APIs.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1371[PYCBC-1371]:
Implemented `ChangePassword` feature in user management API.

* https://issues.couchbase.com/browse/PYCBC-1436[PYCBC-1436]:
Updated pre-commit iSort Revision.

* https://issues.couchbase.com/browse/PYCBC-1440[PYCBC-1440]:
Updated logging to get latest from {cpp} client.

* https://issues.couchbase.com/browse/PYCBC-1438[PYCBC-1438]:
Updated Test Suite/Framework.


=== Version 4.1.1 (14 December 2022)

Version `4.1.1` is the first patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.1
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.1/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1428[PYCBC-1428]:
Fixed view query `ViewOrdering` to allow user specified ordering to be applied.

* https://issues.couchbase.com/browse/PYCBC-1429[PYCBC-1429]:
Fixed defaults for boolean options in N1QL query `QueryOptions`.


=== Version 4.1.0 (3 November 2022)

Version `4.1.0` is the first minor release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.0
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.0/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1420[PYCBC-1420]:
Fixed potential `InternalSDKException` for replica read operations.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1402[PYCBC-1402]:
Added support for using PYCBC_LOG_LEVEL to create console logger.

* https://issues.couchbase.com/browse/PYCBC-1417[PYCBC-1417]:
Updated authentication error message for Bucket Hibernation.

* https://issues.couchbase.com/browse/PYCBC-1422[PYCBC-1422]:
Updated {cbpp} version to incorporate latest changes.

* https://issues.couchbase.com/browse/PYCBC-1167[PYCBC-1167]:
Added support for Serverless Execution Environments.

* https://issues.couchbase.com/browse/PYCBC-1423[PYCBC-1423]:
Added durability improvements.



== Python SDK 4.0 Releases

=== Version 4.0.5 (7 October 2022)

Version `4.0.5` is the fifth patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.0.5
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.5/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1312[PYCBC-1312];
https://issues.couchbase.com/browse/PYCBC-1407[PYCBC-1407]:
Fixed crash related to closing a cluster connection.

* https://issues.couchbase.com/browse/PYCBC-1409[PYCBC-1409]:
Updated to version of {cbpp} client that correctly closes HTTP connections.

* https://issues.couchbase.com/browse/PYCBC-1413[PYCBC-1413]:
Fixed possible streaming API exceptions when executing in threaded environment.

* https://issues.couchbase.com/browse/PYCBC-1415[PYCBC-1415]:
Updated async APIs to use correct future chaining method for read KV operations.

* https://issues.couchbase.com/browse/PYCBC-1416[PYCBC-1416]:
Fixed `txcouchbase` search API.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1405[PYCBC-1405]:
Updated legacy durability to use the internal {cbpp} client API.

* https://issues.couchbase.com/browse/PYCBC-1406[PYCBC-1406]:
Updated replica reads to use the internal {cbpp} client API.

* https://issues.couchbase.com/browse/PYCBC-1411[PYCBC-1411]:
Added support for LDAP authentication.

=== Version 4.0.4 (8 September 2022)

Version `4.0.4` is the fourth patch release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the `4.0.4` release added legacy durability to mutation operations, tracing, and metrics.

[source,bash]
----
$ python3 -m pip install couchbase==4.0.4
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.4/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1398[PYCBC-1398]:
Fixed potential crash when accessing `error_context` from a `base_exception` object.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Added Tracing API, including the ability to use an external tracer such as OpenTelemetry.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Added legacy durability to mutation operations.
This allows the use of client durability within operations that allow for a durability option.

* https://issues.couchbase.com/browse/PYCBC-1399[PYCBC-1399]:
Added Metrics API -- users can now provide a custom meter for logging metrics. 

* https://issues.couchbase.com/browse/PYCBC-1391[PYCBC-1391]:
Removed `_raw_metrics` property from streaming API Metrics result objects.

* https://issues.couchbase.com/browse/PYCBC-1392[PYCBC-1392]:
Updated `collection.exists()` logic to align with a recent change in the underlying {cbpp} client.
Users will no longer see an error if a document doesn't exist, instead the `resp.exists()` method will be needed to determine whether a document is there or not.

* https://issues.couchbase.com/browse/PYCBC-1395[PYCBC-1395]:
Updated build deferred index logic to align with recent change in {cbpp} client.


=== Version 4.0.3 (2 August 2022)

Version `4.0.3` is the third patch release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the `4.0.3` release added key-value replica read operations and improved memory performance.

[source,bash]
----
$ python3 -m pip install couchbase==4.0.3
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.3/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1201[PYCBC-1201];
https://issues.couchbase.com/browse/PYCBC-1282[PYCBC-1282];
https://issues.couchbase.com/browse/PYCBC-1382[PYCBC-1382]
Fixed memory leak in key-value Result objects.

* https://issues.couchbase.com/browse/PYCBC-1383[PYCBC-1383]:
Fixed memory leak in key-value Exception objects.

* https://issues.couchbase.com/browse/PYCBC-1386[PYCBC-1386]:
Fixed OpenSSL discovery for MacOS M1 platforms.

* https://issues.couchbase.com/browse/PYCBC-1389[PYCBC-1389]:
Removed typing-extensions dependency.

* https://issues.couchbase.com/browse/PYCBC-1390[PYCBC-1390]:
Fixed Search query results to forward metrics for user access.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1257[PYCBC-1257]:
Added replica reads.

* https://issues.couchbase.com/browse/PYCBC-1385[PYCBC-1385]:
Updated {cbpp} version.

* https://issues.couchbase.com/browse/PYCBC-1137[PYCBC-1137]:
Deprecated the `CounterResult` CAS property.

==== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Distributed tracing is not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Legacy durability operations are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1290[PYCBC-1290]:
Transactions for `txcouchbase` are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1321[PYCBC-1321]:
API docs for `txcouchbase` API are not yet available.


=== Version 4.0.2 (29 June 2022)

Version `4.0.2` is the second patch release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the `4.0.2` release provides manylinux wheels which significantly improves the installation process on Linux platforms.

[source,console]
----
$ python3 -m pip install couchbase==4.0.2
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.2/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1370[PYCBC-1370]:
Added environment variables to direct CMake to use specified Python3 version.

* https://issues.couchbase.com/browse/PYCBC-1374[PYCBC-1374]:
Added option to dynamically link `stdc++` libs.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-628[PYCBC-628];
https://issues.couchbase.com/browse/PYCBC-1330[PYCBC-1330];
https://issues.couchbase.com/browse/PYCBC-1367[PYCBC-1367]:
Added manylinux wheels.

* https://issues.couchbase.com/browse/PYCBC-1232[PYCBC-1232];
https://issues.couchbase.com/browse/PYCBC-1368[PYCBC-1368]:
Created custom spdlog sink for pass-through logging to python logging.

* https://issues.couchbase.com/browse/PYCBC-1373[PYCBC-1373]:
Provided example Linux build system Dockerfiles.

* https://issues.couchbase.com/browse/PYCBC-1332[PYCBC-1332]:
Added formatting and linting to CI pipeline.

==== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1257[PYCBC-1257]:
Replica reads are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Distributed tracing is not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Legacy durability operations are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1290[PYCBC-1290]:
Transactions for txcouchbase are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1321[PYCBC-1321]:
API docs for txcouchbase API are not yet available.


=== Version 4.0.1 (9 June 2022)

Version 4.0.1 is the first patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.0.1
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.1/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1324[PYCBC-1324]:
Fixed N1QL Query options `scan_wait/scan_cap` misspelling.

* https://issues.couchbase.com/browse/PYCBC-1335[PYCBC-1335]:
Fixed issue where positional and named parameters were not used in `TransactionQueryOptions`.

* https://issues.couchbase.com/browse/PYCBC-1336[PYCBC-1336]:
Fixed crash when using `ViewOptions` keys parameter.

* https://issues.couchbase.com/browse/PYCBC-1342[PYCBC-1342]:
Fixed the txcouchbase API Bucket Management API.

* https://issues.couchbase.com/browse/PYCBC-1343[PYCBC-1343]:
Fixed the txcouchbase Collection Management API.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1328[PYCBC-1328]
Implemented txcouchbase test suite.

* https://issues.couchbase.com/browse/PYCBC-1320[PYCBC-1320]:
Added acouchbase core API Docs.

* https://issues.couchbase.com/browse/PYCBC-1329[PYCBC-1329]:
Cleaned up the acouchbase API test suite.

* https://issues.couchbase.com/browse/PYCBC-1331[PYCBC-1331]:
Updated streaming API options tests to validate all parameters.

* https://issues.couchbase.com/browse/PYCBC-1333[PYCBC-1333]:
Updated README, API docs for 4.0.1 release.

* https://issues.couchbase.com/browse/PYCBC-1334[PYCBC-1334]:
Cleaned up couchbase API test suite.

* https://issues.couchbase.com/browse/PYCBC-1358[PYCBC-1358]:
Updated Windows wheel to dynamically link against OpenSSL.

==== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1232[PYCBC-1232]:
Core IO logging is not forwarded through to Python.

* https://issues.couchbase.com/browse/PYCBC-1257[PYCBC-1257]:
Replica reads are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Distributed tracing is not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Legacy durability operations are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1290[PYCBC-1290]:
Transactions for txcouchbase are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1321[PYCBC-1321]:
API docs for txcouchbase API are not yet available.


=== Version 4.0.0 (6 May 2022)

Version 4.0.0 is the first major release of the next generation Python SDK, built on the the Couchbase {cpp} library -- featuring multi-document distributed ACID transactions, and bringing a number of improvements to the SDK.

[source,console]
----
$ python3 -m pip install couchbase==4.0.0
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.0/

==== New Features

* Support for distributed transactions has now been implemented.
* Reimplemented the library using the Couchbase {cpp} SDK.
* Improved alignment between couchbase, acouchbase and txcouchbase APIs.
* Support for Python versions 3.7 - 3.10.
* Improved API documentation.

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-849[PYCBC-849]:
Implemented wait until ready.

* https://issues.couchbase.com/browse/PYCBC-1146[PYCBC-1146]:
Aligned multi key-value methods with couchbase API.

* https://issues.couchbase.com/browse/PYCBC-1280[PYCBC-1280]:
Fixed implementation of the `CertificateAuthenticator`.

* https://issues.couchbase.com/browse/PYCBC-1296[PYCBC-1296]:
Updated `SearchRow` to not print locations when not included.

==== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1232[PYCBC-1232]:
Core IO logging is not forwarded through to Python.

* https://issues.couchbase.com/browse/PYCBC-1257[PYCBC-1257]:
Replica reads are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Distributed tracing is not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Legacy durability operations are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1290[PYCBC-1290]:
Transactions for txcouchbase are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1319[PYCBC-1319]:
Management APIs for txcouchbase are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1320[PYCBC-1320]:
API docs for acouchbase API are not yet available.

* https://issues.couchbase.com/browse/PYCBC-1321[PYCBC-1321]:
API docs for txcouchbase API are not yet available.

* https://issues.couchbase.com/browse/PYCBC-1322[PYCBC-1322]:
Scoped transactional queries currently throw a `TransactionFailed` error.







////

// Don't think we really need this?

== Upgrading to 4.x

Python SDK 4.x automatically bundles the Couchbase {cpp} SDK (downloading and building it if necessary).
Generally, there is no need to download and install it separately, and we recommend using the built-in the Couchbase {cpp} SDK.
There are binary Python wheels provided for Windows, and for Mac.
////


== Older Releases

For documentation on older releases please refer to the https://docs-archive.couchbase.com/python-sdk/3.2/project-docs/sdk-release-notes.html[archived 3.x release notes] page.
// end::all[] 
