= Couchbase Python SDK Release Notes and Archives
:description: Release notes, installation instructions, and download archive for the Couchbase Python Client.
:navtitle: Release Notes
:page-partial:
:page-topic-type: project-doc
:page-aliases: ROOT:relnotes-python-sdk,ROOT:download-links,ROOT:release-notes,ROOT:sdk-release-notes

[abstract]
{description}

include::hello-world:page$start-using-sdk.adoc[tag=prep]

NOTE: Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.


== Installation

You may install previous versions of the SDK using pip (after installing the required xref:hello-world:start-using-sdk.adoc[dependencies])

[source,console]
----
$ python3 -m pip install git+https://github.com/couchbase/couchbase-python-client@VERSION
----

where VERSION is the version you wish to install. For example, to
install version 2.5.4:

[source,console]
----
$ python3 -m pip install git+http://github.com/couchbase/couchbase-python-client@2.5.4
----

include::hello-world:page$start-using-sdk.adoc[tag=install]


== Upgrading to 3.x

Python SDK 3.n automatically bundles libcouchbase (downloading and building it if necessary).
Generally, there is no need to download and install it separately, and we recommend using the built-in libcouchbase.
There are binary Python wheels provided for Windows.

== Version 3.0.10 (4 March 2021)

[source,console]

----
$ python3 -m pip install couchbase==3.0.10
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.10/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-865[PYCBC-865]:
Cluster-level ping will now use cluster, instead of open bucket.

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1073[PYCBC-1073]:
SDK now supports the Scopes & Collections API Changes in Server 7.0 beta.


== Version 3.0.9 (2 February 2021)

[source,console]
----
$ python3 -m pip install couchbase==3.0.9
----

*API Docs:* https://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.9/

=== Behavioral Change

This release deprecates a field on responses that show the expiration as a duration replacing it with an `expiryTime` which represents an instant point in time as a UNIX timestamp.
It also introduces warnings when the duration specfied is likely an incorrect use of the API.

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-968[PYCBC-968]:
Refactored Document Expiry Duration.

* https://issues.couchbase.com/browse/PYCBC-999[PYCBC-999]:
Deprecated `GetResult.expiry()`.

=== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1094[PYCBC-1094]:
The new `expiryTime` field is returning a float to represent the expiration, rather than a datetime.  
Discovered too late for 3.0.9, this will be fixed in the next release.


== Version 3.0.8 (13 January 2021)

[source,console]
----
$ python3 -m pip install couchbase==3.0.8
----

*API Docs:* https://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.8/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-949[PYCBC-949]:
PasswordAuthenticator no longer fails with the optional `cert_path` argument.

* https://issues.couchbase.com/browse/PYCBC-969[PYCBC-969]:
Implemented SearchScanConsistency to replace QueryScanConsistency in the Search Service.

* https://issues.couchbase.com/browse/PYCBC-1078[PYCBC-1078]:
Design doc unprefix was trimming off too many characters.
A change in the `unprefix` method has fixed this.

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-904[PYCBC-904]:
Code snippets added to xref:howtos/pages/health-check.adoc[Health Check documentation].

* https://issues.couchbase.com/browse/PYCBC-960[PYCBC-960]:
Geopolygon Search Support added.

=== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1037[PYCBC-1037]:
KV and Query latency are ~30% higher than SDK 2.x _with external libcouchbase installed_.
*Workaround*: Remove any externally-installed libcouchbase releases from the system; when run with the built-in libcouchbase, the higher latency is not observed.


== Version 3.0.7 (8 December 2020)

[source,console]
----
$ python3 -m pip install couchbase==3.0.7
----

*API Docs:* https://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.7/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-587[PYCBC-587]:
Flask references returned to the introductory docs.

* https://issues.couchbase.com/browse/PYCBC-797[PYCBC-797],
https://issues.couchbase.com/browse/PYCBC-836[PYCBC-836],
https://issues.couchbase.com/browse/PYCBC-1045[PYCBC-1045]:
`Bucket.ping` timeout can now be set as an option, following use of new `lcb_cmdping_timeout` from libcouchbase.
`Bucket.ping` timeout on some remote nodes also fixed by this,
as is the previous lack of an error enum status for `PingState`.

* https://issues.couchbase.com/browse/PYCBC-1030[PYCBC-1030]:
collection_name and scope_name added to User Roles.

* https://issues.couchbase.com/browse/PYCBC-1033[PYCBC-1033]:
Exception on `six` import fixed.

* https://issues.couchbase.com/browse/PYCBC-1038[PYCBC-1038]:
Fix to handle change in how existing scope is reported by Couchbase Server 7.0.

* https://issues.couchbase.com/browse/PYCBC-1056[PYCBC-1056]:
`MutateIn` was broken for all flavors of async.
Now fixed for `asyncio` and for tested `twisted` uses.

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1063[PYCBC-1063]:
Intermittent fail in `CollectionsTests.test_unlock_wrong_cas` has been fixed.


== Version 3.0.6 (3 November 2020)

Version 3.0.6 is the seventh release of the 3.0 series, bringing enhancements and bug fixes over the last stable release.

[source,console]
----
$ python3 -m pip install couchbase==3.0.6
----

*API Docs:* https://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.6/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-976[PYCBC-976]:
Added AnalyticsScanConsistency.

* https://issues.couchbase.com/browse/PYCBC-1019[PYCBC-1019]:
Fixed a memory leak in N1QL Query.

* https://issues.couchbase.com/browse/PYCBC-1047[PYCBC-1047]:
Updated namespace key for ping test to match change in libcouchbase. 
Ping test now works again.

* https://issues.couchbase.com/browse/PYCBC-1048[PYCBC-1048]:
Collection tests were failing against upcoming 7.0 Server owing to changes in how the exceptions are structured or nested.  
Changed now to parse the HTTP error context's result_body first, and improved the test suite for these and other services.

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-822[PYCBC-822]:
Added documentation on Certificate Authentication and LDAP.

* https://issues.couchbase.com/browse/PYCBC-1057[PYCBC-1057]:
Subdoc expiry intermittent test fails fixed.

* https://issues.couchbase.com/browse/PYCBC-961[PYCBC-961]:
Added Options To Use FTS Hints (Flex Index).

* https://issues.couchbase.com/browse/PYCBC-963[PYCBC-963]:
Added Ephemeral Bucket Management Support.


== Version 3.0.5 (4 September 2020)

Version 3.0.5 is the sixth release of the 3.0 series, bringing enhancements and bug fixes over the last stable release.

[source,console]
----
$ python3 -m pip install couchbase==3.0.5
----

*API Docs:* https://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.5/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-976[PYCBC-976]:
Added `AnalyticsScanConsistency`.

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1011[PYCBC-1011]:
If tests.ini not in current dir, now uses base path of PYCBC distro.

* https://issues.couchbase.com/browse/PYCBC-1016[PYCBC-1016]:
Reenabled non-hybrid build for CLion.


== Version 3.0.4 (11 August 2020)

Version 3.0.4 is the fifth release of the 3.0 series, bringing enhancements and bug fixes over the last stable release.

[source,console]
----
$ python3 -m pip install couchbase==3.0.4
----

*API Docs:* https://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.4/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-915[PYCBC-915]:
Remove support for Python <3.5.

* https://issues.couchbase.com/browse/PYCBC-951[PYCBC-951]:
The MutateInOptions don't have durability.

* https://issues.couchbase.com/browse/PYCBC-986[PYCBC-986]:
Expose and document 'condition' parameter used to create partial N1QL indices.

* https://issues.couchbase.com/browse/PYCBC-989[PYCBC-989]:
Add xattr flag to SD.upsert.

* https://issues.couchbase.com/browse/PYCBC-954[PYCBC-954]:
Can't query in the cloud.

* https://issues.couchbase.com/browse/PYCBC-983[PYCBC-983]:
Make Conan/PyGithub deps contingent on build reqs, enable 3.5 support.

* https://issues.couchbase.com/browse/PYCBC-984[PYCBC-984]:
Some N1QL query settings may not get set.

* https://issues.couchbase.com/browse/PYCBC-987[PYCBC-987]:
ImportError: DLL load failed: The specified module could not be found. - SSL.

* https://issues.couchbase.com/browse/PYCBC-988[PYCBC-988]:
Update release notes generator.

* https://issues.couchbase.com/browse/PYCBC-994[PYCBC-994]:
Remove error_map test as fetching is now automatic

* https://issues.couchbase.com/browse/PYCBC-1001[PYCBC-1001]:
"Could NOT find PythonLibs (missing: PYTHON_LIBRARIES)" causing PEP517 install error.

* https://issues.couchbase.com/browse/PYCBC-1002[PYCBC-1002]:
Explicitly set adhoc to off with lcb_cmdquery_adhoc and prepared statements.

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-671[PYCBC-671]:
Add Amazon Linux 2 verification testing.

* https://issues.couchbase.com/browse/PYCBC-933[PYCBC-933]:
Review docs for update items, identify/file issues.

* https://issues.couchbase.com/browse/PYCBC-992[PYCBC-992]:
Pin LCB to 3.0.3

* https://issues.couchbase.com/browse/PYCBC-998[PYCBC-998]:
SSL install notes update.


== Version 3.0.3 (15 July 2020)

Version 3.0.3 is the fourth release of the 3.0 series, bringing enhancements and bug fixes over the last stable release.

[source,console]
----
$ python3 -m pip install couchbase==3.0.3
----

*API Docs:* https://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.3/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-981[PYCBC-981]:
Fix for PEP517 install issue

== Version 3.0.2 (14 July 2020)

Version 3.0.2 is the third release of the 3.0 series, bringing enhancements and bug fixes over the last stable release.

[source,console]
----
$ python3 -m pip install couchbase==3.0.2
----

*API Docs:* https://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.2/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-920[PYCBC-920]:
Twisted api seeing lots of timeouts.

* https://issues.couchbase.com/browse/PYCBC-941[PYCBC-941]:
Build against correct OpenSSL version on Windows.

* https://issues.couchbase.com/browse/PYCBC-950[PYCBC-950]:
N1QL query connections remain open after completion.

* https://issues.couchbase.com/browse/PYCBC-970[PYCBC-970]:
Python SDK assumes docstrings are available.

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-885[PYCBC-885]:
FTS Doc for Python 3.0.

* https://issues.couchbase.com/browse/PYCBC-929[PYCBC-929]:
Document how to get encrypted connections to clusters.

* https://issues.couchbase.com/browse/PYCBC-591[PYCBC-591]:
Document analytics using the Python SDK at draft level.


== Version 3.0.1 (12 June 2020)

Version 3.0.1 is the second release of the 3.0 series, bringing enhancements and bug fixes over the last stable release.

[source,console]
----
$ python3 -m pip install couchbase==3.0.1
----

*API Docs:* https://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.1/

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-670[PYCBC-670]:
Added CentOS 8 verification testing.

* https://issues.couchbase.com/browse/PYCBC-916[PYCBC-916]:
Added standard clang-format to repository.

* https://issues.couchbase.com/browse/PYCBC-947[PYCBC-947]:
Pin LCB to 3.0.2

=== Bug Fixes

* https://issues.couchbase.com/browse/PYCBC-714[PYCBC-714]:
Python SDK throwing SystemError.

* https://issues.couchbase.com/browse/PYCBC-833[PYCBC-833]:
get_all_replicas segfaults.

* https://issues.couchbase.com/browse/PYCBC-834[PYCBC-834]:
Intermittent segfault in collection.exists.

* https://issues.couchbase.com/browse/PYCBC-912[PYCBC-912]:
Generated docs need a second pass.

* https://issues.couchbase.com/browse/PYCBC-918[PYCBC-918]:
Version 3 needs access to bucket "default" to connect.

* https://issues.couchbase.com/browse/PYCBC-924[PYCBC-924]:
CBCollection.__new__ invoking type superconstructor on some platforms.

* https://issues.couchbase.com/browse/PYCBC-928[PYCBC-928]:
Bootstrap timing out on Centos.

* https://issues.couchbase.com/browse/PYCBC-930[PYCBC-930]:
Using `cert_path=` in ClusterOptions hit inner_cause='cert_path' is an invalid keyword argument for this function, C Source=(src/bucket.c,1047).

* https://issues.couchbase.com/browse/PYCBC-934[PYCBC-934]:
Some Query OptionBlocks not passing kwargs to constructor.

* https://issues.couchbase.com/browse/PYCBC-936[PYCBC-936]:
QueryScanConsistency object should be an Enum.

* https://issues.couchbase.com/browse/PYCBC-937[PYCBC-937]:
Rename CBAS to ANALYTICS/Analytics to match LCB/RFC.

* https://issues.couchbase.com/browse/PYCBC-939[PYCBC-939]:
Unpin some dev_requirements entries.


== Version 3.0.0 (1 May 2020)

This is the first GA release of the third generation Python SDK.

[source,console]
----
$ python3 -m pip install couchbase==3.0.0
----

*API Docs:* https://docs.couchbase.com/sdk-api/couchbase-python-client-3.0.0/

WARNING: Whilst we have made our best efforts to update the API documentation to accurately reflect the functionality provided, 
there are still some known documentation issues to be resolved. 
We aim to fix these as soon as possible.


=== Known issues

* https://issues.couchbase.com/browse/PYCBC-912[PYCBC-912]
Generated docs need a second pass.

* https://issues.couchbase.com/browse/PYCBC-834[PYCBC-834]
Intermittent segfault in collection.exists.

* https://issues.couchbase.com/browse/PYCBC-833[PYCBC-833]
get_all_replicas segfaults.

And an issue in libcouchbase that impacts upon the Python Client:

* https://issues.couchbase.com/browse/CCBC-1218[CCBC-128]
Segfault in lcbtrace_span_add_tag_uint64.

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-816[PYCBC-816]:
Migrate txcouchbase to SDK3.

* https://issues.couchbase.com/browse/PYCBC-805[PYCBC-805]:
Provide async access to Cluster.

* https://issues.couchbase.com/browse/PYCBC-658[PYCBC-658]:
Provide txcouchbase support for durability.

* https://issues.couchbase.com/browse/PYCBC-826[PYCBC-826]:
Implement acouchbase for Windows.

* https://issues.couchbase.com/browse/PYCBC-622[PYCBC-622]:
Document/configure Git dependency.

* https://issues.couchbase.com/browse/PYCBC-673[PYCBC-673]:
Prefer locally bundled lcb include for installs.

* https://issues.couchbase.com/browse/PYCBC-681[PYCBC-681]:
Make OptionBlock arguments discoverable.

* https://issues.couchbase.com/browse/PYCBC-698[PYCBC-698]:
Fixed test failures against real servers.

* https://issues.couchbase.com/browse/PYCBC-711[PYCBC-711]:
Create AnalyticsIndexManager, fix analytics queries, with v3 tests.

* https://issues.couchbase.com/browse/PYCBC-719[PYCBC-719]:
The ViewIteratorTests all are skipping when they should not.

* https://issues.couchbase.com/browse/PYCBC-723[PYCBC-723]:
bucket.ping needs to be implemented.

* https://issues.couchbase.com/browse/PYCBC-732[PYCBC-732]:
QueryIndexManager interface work, plus fixes for failing tests.

* https://issues.couchbase.com/browse/PYCBC-746[PYCBC-746]:
Remove NodeManager from API.

* https://issues.couchbase.com/browse/PYCBC-747[PYCBC-747]:
Remove generic Manager API.

* https://issues.couchbase.com/browse/PYCBC-752[PYCBC-752]:
ViewIndexManager needs proper SDK3 interface.

* https://issues.couchbase.com/browse/PYCBC-754[PYCBC-754]:
Fix invalid named args in Collection.get.

* https://issues.couchbase.com/browse/PYCBC-771[PYCBC-771]:
Mark multi-operations as volatile until sdk-rfc done.

* https://issues.couchbase.com/browse/PYCBC-785[PYCBC-785]:
Expose ErrorContexts.

* https://issues.couchbase.com/browse/PYCBC-794[PYCBC-794]:
Implement Cluster.disconnect.

* https://issues.couchbase.com/browse/PYCBC-798[PYCBC-798]:
Ping is returning 'scope' instead of 'namespace'.

* https://issues.couchbase.com/browse/PYCBC-801[PYCBC-801]:
Reflect optional nature of parameters in OptionBlock constructors.

* https://issues.couchbase.com/browse/PYCBC-803[PYCBC-803]:
Reinstate non-hybrid (pure CMake) build.

* https://issues.couchbase.com/browse/PYCBC-815[PYCBC-815]:
Share lcb_INSTANCE objects between collections.

* https://issues.couchbase.com/browse/PYCBC-817[PYCBC-817]:
Collection get_and_touch, get_and_lock need to be SDK3-ized.

* https://issues.couchbase.com/browse/PYCBC-838[PYCBC-838]:
Client Durability support.

* https://issues.couchbase.com/browse/PYCBC-473[PYCBC-473]:
Add FTS Index Management.

* https://issues.couchbase.com/browse/PYCBC-691[PYCBC-691]:
Set up Combination Testing for SDK 3 - Server 5.5, 6.0, 6.5.

* https://issues.couchbase.com/browse/PYCBC-729[PYCBC-729]:
Add necessary build tools to the readme.md.

* https://issues.couchbase.com/browse/PYCBC-777[PYCBC-777]:
Complete KV doc for GA.

* https://issues.couchbase.com/browse/PYCBC-779[PYCBC-779]:
Getting Started docs Tidy Up.

* https://issues.couchbase.com/browse/PYCBC-781[PYCBC-781]:
Managing Connections doc.

* https://issues.couchbase.com/browse/PYCBC-841[PYCBC-841]:
Update integration testing Jenkins node labels.

* https://issues.couchbase.com/browse/PYCBC-844[PYCBC-844]:
Convert integration tests to nightlies.

* https://issues.couchbase.com/browse/PYCBC-743[PYCBC-743]:
Mark all ErrorContexts as Uncommitted.

* https://issues.couchbase.com/browse/PYCBC-751[PYCBC-751]:
AnalyticsIndexes manager missing on Cluster.

* https://issues.couchbase.com/browse/PYCBC-775[PYCBC-775]:
Migrate collection attributes to use timedelta for durations.

* https://issues.couchbase.com/browse/PYCBC-744[PYCBC-744]:
Ensure precedence between named param and option block is described.

* https://issues.couchbase.com/browse/PYCBC-864[PYCBC-864]:
Provide asyncio access to Cluster, also analytics and search.

* https://issues.couchbase.com/browse/PYCBC-707[PYCBC-707]:
Sweep through tests, examine why some are skipped.

* https://issues.couchbase.com/browse/PYCBC-840[PYCBC-840]:
Add testing for 6.5 with DP enabled.

* https://issues.couchbase.com/browse/PYCBC-845[PYCBC-845]:
Nightlies need to build and test (against mock) on more platforms.

* https://issues.couchbase.com/browse/PYCBC-847[PYCBC-847]:
Consolidate exceptions into one place.

* https://issues.couchbase.com/browse/PYCBC-870[PYCBC-870]:
Testing on MacOS.

* https://issues.couchbase.com/browse/PYCBC-873[PYCBC-873]:
CMake: Skip PythonLibs search for Hybrid builds, remove -pthreads.

* https://issues.couchbase.com/browse/PYCBC-886[PYCBC-886]:
Expiry not properly returned or set.

* https://issues.couchbase.com/browse/PYCBC-895[PYCBC-895]:
Improve navigability/API docs for async, remove factories.

* https://issues.couchbase.com/browse/PYCBC-896[PYCBC-896]:
Remove unused code (unshared collection, v2 async code).


=== Fixes

* https://issues.couchbase.com/browse/PYCBC-774[PYCBC-774]:
Proper implementation for Collection.get_all_replicas.

* https://issues.couchbase.com/browse/PYCBC-782[PYCBC-782]:
Fix durability_level on collection.remove.

* https://issues.couchbase.com/browse/PYCBC-789[PYCBC-789]:
N1QL query request to create index appears to fail.

* https://issues.couchbase.com/browse/PYCBC-792[PYCBC-792]:
Cluster.diagnostics always times out.

* https://issues.couchbase.com/browse/PYCBC-795[PYCBC-795]:
ViewManager needs to wrap http calls for proper exceptions.

* https://issues.couchbase.com/browse/PYCBC-799[PYCBC-799]:
Ensure v3 tests all pass on Jenkins against real servers.

* https://issues.couchbase.com/browse/PYCBC-800[PYCBC-800]:
Fix BucketMissingException when trying to connect to Cluster.

* https://issues.couchbase.com/browse/PYCBC-807[PYCBC-807]:
Correct CollectionManager docstrings.

* https://issues.couchbase.com/browse/PYCBC-808[PYCBC-808]:
Fix AnalyticsOptions code.

* https://issues.couchbase.com/browse/PYCBC-818[PYCBC-818]:
Collection.exists always returning true.

* https://issues.couchbase.com/browse/PYCBC-829[PYCBC-829]:
Collection.get_and_lock should not get and lock in 2 commands.

* https://issues.couchbase.com/browse/PYCBC-850[PYCBC-850]:
CBCollectionShared not passing through collection name.

* https://issues.couchbase.com/browse/PYCBC-855[PYCBC-855]:
ViewResult recurses infinitely on some platforms.

* https://issues.couchbase.com/browse/PYCBC-857[PYCBC-857]:
Address some missing error context types.

* https://issues.couchbase.com/browse/PYCBC-859[PYCBC-859]:
Bucket exception parsing broken by server message change.

* https://issues.couchbase.com/browse/PYCBC-756[PYCBC-756]:
Append, Prepend, Increment, Decrement need to move to BinaryCollection.

* https://issues.couchbase.com/browse/PYCBC-749[PYCBC-749]:
Remove additional overloads for query and search.

* https://issues.couchbase.com/browse/PYCBC-806[PYCBC-806]:
Various PEP8 formatting fixes.

* https://issues.couchbase.com/browse/PYCBC-809[PYCBC-809]:
PEP8/MyPy warning removal.

* https://issues.couchbase.com/browse/PYCBC-839[PYCBC-839]:
CreateCollection CollectionSpec must include MaxTTL.

* https://issues.couchbase.com/browse/PYCBC-760[PYCBC-760]
Fixed Collection.exists implementation.

* https://issues.couchbase.com/browse/PYCBC-640[PYCBC-640]
Implemented replica reads according to RFC.

* https://issues.couchbase.com/browse/PYCBC-768[PYCBC-768]:
Refactored durability params to prevent impossible combinations.

* https://issues.couchbase.com/browse/PYCBC-639[PYCBC-639]:
Example N1QL statements don't seem to work in "Hello Couchbase" example.

* https://issues.couchbase.com/browse/PYCBC-667[PYCBC-667]:
Fixed Upsert Group fails with 'roles: value must be supplied'.

* https://issues.couchbase.com/browse/PYCBC-674[PYCBC-674]:
Fixed deprecation warnings from sdk2 when running sdk3.

* https://issues.couchbase.com/browse/PYCBC-675[PYCBC-675]:
Brough Result objects in line with RFC, removed unidiomatic interfaces.

* https://issues.couchbase.com/browse/PYCBC-694[PYCBC-694]:
Completed query implementation.

* https://issues.couchbase.com/browse/PYCBC-753[PYCBC-753]:
Collection APIs marked volatile.

* https://issues.couchbase.com/browse/PYCBC-763[PYCBC-763]:
Corrected MutateInResult.content_as implementation.

* https://issues.couchbase.com/browse/PYCBC-764[PYCBC-764]:
Delete or renamed remaining SDK2 references in main API:
Renamed SDK2/sdk2 to Core/core where applicable.
Removed classes & methods inapplicable to SDK3.

* https://issues.couchbase.com/browse/PYCBC-704[PYCBC-704]:
Implemented `*CollectionOptions` for Collection management API.

* https://issues.couchbase.com/browse/PYCBC-716[PYCBC-716]:
Tests should no longer try to do 6.5-specific tests against a 6.0 server.

* https://issues.couchbase.com/browse/PYCBC-686[PYCBC-686]:
Applied new naming convention for interfaces/protocols.

* https://issues.couchbase.com/browse/PYCBC-687[PYCBC-687]:
Support added for Python 3.8.

* https://issues.couchbase.com/browse/PYCBC-761[PYCBC-761]:
Added timeout to `lookup_in` operation.

* https://issues.couchbase.com/browse/PYCBC-784[PYCBC-784]:
Remove/move/mark "internal" Admin methods/class.

* https://issues.couchbase.com/browse/PYCBC-793[PYCBC-793]:
Cluster.bucket needs kwargs for the tests to work against the mock.

* https://issues.couchbase.com/browse/PYCBC-796[PYCBC-796]:
Move some tests on sdk2 to sdk3.

* https://issues.couchbase.com/browse/PYCBC-797[PYCBC-797]:
Bucket.ping needs to respect the timeout in the options if any.

* https://issues.couchbase.com/browse/PYCBC-824[PYCBC-824]:
QueryResult has a few fields that are not implemented yet.

* https://issues.couchbase.com/browse/PYCBC-831[PYCBC-831]:
Cluster settings like compression, tracing, etc.. should be set at Cluster initialisation only.

* https://issues.couchbase.com/browse/PYCBC-832[PYCBC-832]:
Test issues with cluster and opening new buckets.

* https://issues.couchbase.com/browse/PYCBC-835[PYCBC-835]:
Diagnostics hangs on any server < 6.5.

* https://issues.couchbase.com/browse/PYCBC-854[PYCBC-854]:
ping() needs to be at the cluster level as well.

* https://issues.couchbase.com/browse/PYCBC-860[PYCBC-860]:
Don't pass a bucket name for cluster connections by default.

* https://issues.couchbase.com/browse/PYCBC-863[PYCBC-863]:
iterable_wrapper failing for some async operations.

* https://issues.couchbase.com/browse/PYCBC-869[PYCBC-869]:
Cattrs library doesn't work with python 3.5.2.

* https://issues.couchbase.com/browse/PYCBC-874[PYCBC-874]:
Do cluster ops on 6.5-DP.

* https://issues.couchbase.com/browse/PYCBC-875[PYCBC-875]:
ViewQuery segfaults in bindings.

* https://issues.couchbase.com/browse/PYCBC-878[PYCBC-878]:
Tx stuff seems to have broken imports recently.

* https://issues.couchbase.com/browse/PYCBC-881[PYCBC-881]:
Make (txcouchbase|acouchbase).cluster.Cluster.connect return an instance of the relevant class.

* https://issues.couchbase.com/browse/PYCBC-882[PYCBC-882]:
Fix dropped imports.

* https://issues.couchbase.com/browse/PYCBC-883[PYCBC-883]:
Some remaining exceptions not listed in Error Handling RFC.

* https://issues.couchbase.com/browse/PYCBC-898[PYCBC-898]:
Correct threshold naming for search and query.

* https://issues.couchbase.com/browse/PYCBC-899[PYCBC-899]:
Import error in search tests.

* https://issues.couchbase.com/browse/PYCBC-902[PYCBC-902]:
Add more coverage to integration tests.

* https://issues.couchbase.com/browse/PYCBC-903[PYCBC-903]:
Further improve Async API/docstrings.

* https://issues.couchbase.com/browse/PYCBC-905[PYCBC-905]:
Pip install fails for latest sdk commits on python 3.5.x.

* https://issues.couchbase.com/browse/PYCBC-908[PYCBC-908]:
Add some missing View result types.

* https://issues.couchbase.com/browse/PYCBC-897[PYCBC-897]:
Update 'long_description' settings to conform with PyPi.

* https://issues.couchbase.com/browse/PYCBC-910[PYCBC-910]:
Factor CBCollectionShared into CBCollectionBase.

* https://issues.couchbase.com/browse/PYCBC-911[PYCBC-911]:
Remove content_as_array as not in RFC.


== Pre-releases

Numerous _Alpha_ and _Beta_ releases were made in the run-up to the 3.0 release, and although unsupported, the release notes and download links are retained for archive purposes xref:3.0-pre-release-notes.adoc[here].


== Older Releases

Although https://www.couchbase.com/support-policy/enterprise-software[no longer supported], documentation for older releases continues to be available in our https://docs-archive.couchbase.com/home/index.html[docs archive].
 
