= Couchbase Python SDK Release Notes and Archives
:description: Release notes, installation instructions, and download archive for the Couchbase Python Client.
:navtitle: Release Notes
:page-partial:
:page-topic-type: project-doc
:page-aliases: ROOT:relnotes-python-sdk,ROOT:download-links,ROOT:release-notes,ROOT:sdk-release-notes

// tag::all[]
[abstract]
{description}

Couchbase Python SDK 4.x is built upon {cbpp}, and SDK 3.x is built upon LCB (libcouchbase), but both conform to the xref:project-docs:compatibility.adoc#api-version[SDK API 3.x].
The move to {cbpp} facilitates the introduction of xref:howtos:distributed-acid-transactions-from-the-sdk.adoc[distributed ACID transactions].

NOTE: Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.


== Installation

You may install previous versions of the SDK using pip (after installing the required xref:hello-world:start-using-sdk.adoc[dependencies])

[source,console]
----
$ python3 -m pip install git+https://github.com/couchbase/couchbase-python-client@VERSION
----

where VERSION is the version you wish to install. 
For example, to install version 3.2.6:

[source,console]
----
$ python3 -m pip install git+https://github.com/couchbase/couchbase-python-client@3.2.6
----

For more detailed installation instructions, see the xref:project-docs:sdk-full-installation.adoc[full installation guide].




== Release Notes

== Version 4.0.0 (6 May 2022)

Version 4.0.0 is the first major release of the next generation Python SDK, built on the Couchbase++ library -- featuring multi-document distributed ACID transactions, and bringing a number of improvements to the SDK.

[source,console]
----
$ pip install couchbase==4.0.0
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.0/

=== New Features

* Support for distributed transactions has now been implemented.
* Reimplemented the library using couchbase++.
* Improved alignment between couchbase, acouchbase and txcouchbase APIs.
* Support for Python versions 3.7 - 3.10.
* Improved API documentation.

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-849[PYCBC-849]:
Implemented wait until ready.

* https://issues.couchbase.com/browse/PYCBC-1146[PYCBC-1146]:
Aligned multi key-value methods with couchbase API.

* https://issues.couchbase.com/browse/PYCBC-1280[PYCBC-1280]:
Fixed implementation of the `CertificateAuthenticator`.

* https://issues.couchbase.com/browse/PYCBC-1296[PYCBC-1296]:
Updated `SearchRow` to not print locations when not included.

=== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1232[PYCBC-1232]:
Core IO logging is not forwarded through to Python.

* https://issues.couchbase.com/browse/PYCBC-1257[PYCBC-1257]:
Replica reads are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Distributed tracing is not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Legacy durability operations are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1290[PYCBC-1290]:
Transactions for txcouchbase are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1319[PYCBC-1319]:
Management APIs for txcouchbase are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1320[PYCBC-1320]:
API docs for acouchbase API are not yet available.

* https://issues.couchbase.com/browse/PYCBC-1321[PYCBC-1321]:
API docs for txcouchbase API are not yet available.

* https://issues.couchbase.com/browse/PYCBC-1322[PYCBC-1322]:
Scoped transactional queries currently throw a `TransactionFailed` error.







////

// Don't think we really need this?

== Upgrading to 4.x

Python SDK 4.x automatically bundles Couchbase++ (downloading and building it if necessary).
Generally, there is no need to download and install it separately, and we recommend using the built-in Couchbase++.
There are binary Python wheels provided for Windows, and for Mac.
////


== Older Releases

For documentation on older releases please refer to the xref:3.2@python-sdk:project-docs:sdk-release-notes.adoc[3.x release notes] page.
// end::all[] 
