= Release Notes
:description: Release notes, installation instructions, and download archive for the Couchbase Python Client.
:page-partial:
:page-topic-type: reference
:page-aliases: ROOT:relnotes-python-sdk,ROOT:download-links,ROOT:release-notes,ROOT:sdk-release-notes

// tag::all[]
[abstract]
{description}

Couchbase Python SDK 4.x is built upon {cbpp}, and SDK 3.x is built upon LCB (libcouchbase), but both conform to the xref:project-docs:compatibility.adoc#api-version[SDK API 3.x].
The move to {cbpp} facilitates the introduction of xref:howtos:distributed-acid-transactions-from-the-sdk.adoc[distributed ACID transactions].

NOTE: Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.


== Installation

You may install previous versions of the SDK using pip (after installing the required xref:hello-world:start-using-sdk.adoc[dependencies])

[source,console]
----
$ python3 -m pip install git+https://github.com/couchbase/couchbase-python-client@VERSION
----

where VERSION is the version you wish to install. 
For example, to install version 4.1.0:

[source,console]
----
$ python3 -m pip install git+https://github.com/couchbase/couchbase-python-client@4.1.0
----

For more detailed installation instructions, see the xref:project-docs:sdk-full-installation.adoc[full installation guide].


== Release Notes


== Version 4.1.0 (3 November 2022)

Version `4.1.0` is the first minor release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.0
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.0/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-1420[PYCBC-1420]:
Fixed potential `InternalSDKException` for replica read operations.

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1402[PYCBC-1402]:
Added support for using PYCBC_LOG_LEVEL to create console logger.

* https://issues.couchbase.com/browse/PYCBC-1417[PYCBC-1417]:
Updated authentication error message for Bucket Hibernation.

* https://issues.couchbase.com/browse/PYCBC-1422[PYCBC-1422]:
Updated {cbpp} version to incorporate latest changes.

* https://issues.couchbase.com/browse/PYCBC-1167[PYCBC-1167]:
Added support for Serverless Execution Environments.

* https://issues.couchbase.com/browse/PYCBC-1423[PYCBC-1423]:
Added durability improvements.


== Version 4.0.5 (7 October 2022)

Version `4.0.5` is the fifth patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.0.5
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.5/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-1312[PYCBC-1312];
https://issues.couchbase.com/browse/PYCBC-1407[PYCBC-1407]:
Fixed crash related to closing a cluster connection.

* https://issues.couchbase.com/browse/PYCBC-1409[PYCBC-1409]:
Updated to version of {cbpp} client that correctly closes HTTP connections.

* https://issues.couchbase.com/browse/PYCBC-1413[PYCBC-1413]:
Fixed possible streaming API exceptions when executing in threaded environment.

* https://issues.couchbase.com/browse/PYCBC-1415[PYCBC-1415]:
Updated async APIs to use correct future chaining method for read KV operations.

* https://issues.couchbase.com/browse/PYCBC-1416[PYCBC-1416]:
Fixed `txcouchbase` search API.

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1405[PYCBC-1405]:
Updated legacy durability to use the internal {cbpp} client API.

* https://issues.couchbase.com/browse/PYCBC-1406[PYCBC-1406]:
Updated replica reads to use the internal {cbpp} client API.

* https://issues.couchbase.com/browse/PYCBC-1411[PYCBC-1411]:
Added support for LDAP authentication.

== Version 4.0.4 (8 September 2022)

Version `4.0.4` is the fourth patch release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the `4.0.4` release added legacy durability to mutation operations, tracing, and metrics.

[source,bash]
----
$ python3 -m pip install couchbase==4.0.4
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.4/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-1398[PYCBC-1398]:
Fixed potential crash when accessing `error_context` from a `base_exception` object.

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Added Tracing API, including the ability to use an external tracer such as OpenTelemetry.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Added legacy durability to mutation operations.
This allows the use of client durability within operations that allow for a durability option.

* https://issues.couchbase.com/browse/PYCBC-1399[PYCBC-1399]:
Added Metrics API -- users can now provide a custom meter for logging metrics. 

* https://issues.couchbase.com/browse/PYCBC-1391[PYCBC-1391]:
Removed `_raw_metrics` property from streaming API Metrics result objects.

* https://issues.couchbase.com/browse/PYCBC-1392[PYCBC-1392]:
Updated `collection.exists()` logic to align with a recent change in the underlying {cbpp} client.
Users will no longer see an error if a document doesn't exist, instead the `resp.exists()` method will be needed to determine whether a document is there or not.

* https://issues.couchbase.com/browse/PYCBC-1395[PYCBC-1395]:
Updated build deferred index logic to align with recent change in {cbpp} client.


== Version 4.0.3 (2 August 2022)

Version `4.0.3` is the third patch release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the `4.0.3` release added key-value replica read operations and improved memory performance.

[source,bash]
----
$ python3 -m pip install couchbase==4.0.3
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.3/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-1201[PYCBC-1201];
https://issues.couchbase.com/browse/PYCBC-1282[PYCBC-1282];
https://issues.couchbase.com/browse/PYCBC-1382[PYCBC-1382]
Fixed memory leak in key-value Result objects.

* https://issues.couchbase.com/browse/PYCBC-1383[PYCBC-1383]:
Fixed memory leak in key-value Exception objects.

* https://issues.couchbase.com/browse/PYCBC-1386[PYCBC-1386]:
Fixed OpenSSL discovery for MacOS M1 platforms.

* https://issues.couchbase.com/browse/PYCBC-1389[PYCBC-1389]:
Removed typing-extensions dependency.

* https://issues.couchbase.com/browse/PYCBC-1390[PYCBC-1390]:
Fixed Search query results to forward metrics for user access.

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1257[PYCBC-1257]:
Added replica reads.

* https://issues.couchbase.com/browse/PYCBC-1385[PYCBC-1385]:
Updated {cbpp} version.

* https://issues.couchbase.com/browse/PYCBC-1137[PYCBC-1137]:
Deprecated the `CounterResult` CAS property.

=== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Distributed tracing is not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Legacy durability operations are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1290[PYCBC-1290]:
Transactions for `txcouchbase` are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1321[PYCBC-1321]:
API docs for `txcouchbase` API are not yet available.


== Version 4.0.2 (29 June 2022)

Version `4.0.2` is the second patch release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the `4.0.2` release provides manylinux wheels which significantly improves the installation process on Linux platforms.

[source,console]
----
$ python3 -m pip install couchbase==4.0.2
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.2/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-1370[PYCBC-1370]:
Added environment variables to direct CMake to use specified Python3 version.

* https://issues.couchbase.com/browse/PYCBC-1374[PYCBC-1374]:
Added option to dynamically link stdc++ libs.

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-628[PYCBC-628];
https://issues.couchbase.com/browse/PYCBC-1330[PYCBC-1330];
https://issues.couchbase.com/browse/PYCBC-1367[PYCBC-1367]:
Added manylinux wheels.

* https://issues.couchbase.com/browse/PYCBC-1232[PYCBC-1232];
https://issues.couchbase.com/browse/PYCBC-1368[PYCBC-1368]:
Created custom spdlog sink for pass-through logging to python logging.

* https://issues.couchbase.com/browse/PYCBC-1373[PYCBC-1373]:
Provided example Linux build system Dockerfiles.

* https://issues.couchbase.com/browse/PYCBC-1332[PYCBC-1332]:
Added formatting and linting to CI pipeline.

=== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1257[PYCBC-1257]:
Replica reads are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Distributed tracing is not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Legacy durability operations are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1290[PYCBC-1290]:
Transactions for txcouchbase are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1321[PYCBC-1321]:
API docs for txcouchbase API are not yet available.


== Version 4.0.1 (9 June 2022)

Version 4.0.1 is the first patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.0.1
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.1/

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-1324[PYCBC-1324]:
Fixed N1QL Query options `scan_wait/scan_cap` misspelling.

* https://issues.couchbase.com/browse/PYCBC-1335[PYCBC-1335]:
Fixed issue where positional and named parameters were not used in `TransactionQueryOptions`.

* https://issues.couchbase.com/browse/PYCBC-1336[PYCBC-1336]:
Fixed crash when using `ViewOptions` keys parameter.

* https://issues.couchbase.com/browse/PYCBC-1342[PYCBC-1342]:
Fixed the txcouchbase API Bucket Management API.

* https://issues.couchbase.com/browse/PYCBC-1343[PYCBC-1343]:
Fixed the txcouchbase Collection Management API.

=== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1328[PYCBC-1328]
Implemented txcouchbase test suite.

* https://issues.couchbase.com/browse/PYCBC-1320[PYCBC-1320]:
Added acouchbase core API Docs.

* https://issues.couchbase.com/browse/PYCBC-1329[PYCBC-1329]:
Cleaned up the acouchbase API test suite.

* https://issues.couchbase.com/browse/PYCBC-1331[PYCBC-1331]:
Updated streaming API options tests to validate all parameters.

* https://issues.couchbase.com/browse/PYCBC-1333[PYCBC-1333]:
Updated README, API docs for 4.0.1 release.

* https://issues.couchbase.com/browse/PYCBC-1334[PYCBC-1334]:
Cleaned up couchbase API test suite.

* https://issues.couchbase.com/browse/PYCBC-1358[PYCBC-1358]:
Updated Windows wheel to dynamically link against OpenSSL.

=== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1232[PYCBC-1232]:
Core IO logging is not forwarded through to Python.

* https://issues.couchbase.com/browse/PYCBC-1257[PYCBC-1257]:
Replica reads are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Distributed tracing is not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Legacy durability operations are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1290[PYCBC-1290]:
Transactions for txcouchbase are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1321[PYCBC-1321]:
API docs for txcouchbase API are not yet available.


== Version 4.0.0 (6 May 2022)

Version 4.0.0 is the first major release of the next generation Python SDK, built on the Couchbase++ library -- featuring multi-document distributed ACID transactions, and bringing a number of improvements to the SDK.

[source,console]
----
$ python3 -m pip install couchbase==4.0.0
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.0/

=== New Features

* Support for distributed transactions has now been implemented.
* Reimplemented the library using couchbase++.
* Improved alignment between couchbase, acouchbase and txcouchbase APIs.
* Support for Python versions 3.7 - 3.10.
* Improved API documentation.

=== Fixes

* https://issues.couchbase.com/browse/PYCBC-849[PYCBC-849]:
Implemented wait until ready.

* https://issues.couchbase.com/browse/PYCBC-1146[PYCBC-1146]:
Aligned multi key-value methods with couchbase API.

* https://issues.couchbase.com/browse/PYCBC-1280[PYCBC-1280]:
Fixed implementation of the `CertificateAuthenticator`.

* https://issues.couchbase.com/browse/PYCBC-1296[PYCBC-1296]:
Updated `SearchRow` to not print locations when not included.

=== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1232[PYCBC-1232]:
Core IO logging is not forwarded through to Python.

* https://issues.couchbase.com/browse/PYCBC-1257[PYCBC-1257]:
Replica reads are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Distributed tracing is not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Legacy durability operations are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1290[PYCBC-1290]:
Transactions for txcouchbase are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1319[PYCBC-1319]:
Management APIs for txcouchbase are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1320[PYCBC-1320]:
API docs for acouchbase API are not yet available.

* https://issues.couchbase.com/browse/PYCBC-1321[PYCBC-1321]:
API docs for txcouchbase API are not yet available.

* https://issues.couchbase.com/browse/PYCBC-1322[PYCBC-1322]:
Scoped transactional queries currently throw a `TransactionFailed` error.







////

// Don't think we really need this?

== Upgrading to 4.x

Python SDK 4.x automatically bundles Couchbase++ (downloading and building it if necessary).
Generally, there is no need to download and install it separately, and we recommend using the built-in Couchbase++.
There are binary Python wheels provided for Windows, and for Mac.
////


== Older Releases

For documentation on older releases please refer to the xref:3.2@python-sdk:project-docs:sdk-release-notes.adoc[3.x release notes] page.
// end::all[] 
