= Couchbase Python SDK Release Notes and Archives
:description: Release notes, installation instructions, and download archive for the Couchbase Python Client.
:navtitle: Release Notes
:page-partial:
:page-topic-type: project-doc
:page-aliases: ROOT:relnotes-python-sdk,ROOT:download-links,ROOT:release-notes,ROOT:sdk-release-notes

// tag::all[]
[abstract]
{description}

include::hello-world:page$start-using-sdk.adoc[tag=prep]



Couchbase Python SDK 4.x is built upon Couchbase++, and SDK 3.x is built upon LCB (libcouchbase), but both conform to the xref:compatibility.adoc#api-version[3.x SDK API].
The move to Couchbase++ facilitates the introduction of xref:howtos:distributed-acid-transactions-from-the-sdk.adoc[distributed ACID transactions].

NOTE: Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.


== Installation

You may install previous versions of the SDK using pip (after installing the required xref:hello-world:start-using-sdk.adoc[dependencies])

[source,console]
----
$ python3 -m pip install git+https://github.com/couchbase/couchbase-python-client@VERSION
----

where VERSION is the version you wish to install. 
For example, to install version 3.2.6:

[source,console]
----
$ python3 -m pip install git+https://github.com/couchbase/couchbase-python-client@3.2.6
----

For more detailed installation instructions, see the xref:project-pages:sdk-full-installation.adoc[full installation guide].




== Release Notes

// === Version 3.2.6 (2 February 2022)










////

// Don't think we really need this?

== Upgrading to 4.x

Python SDK 4.x automatically bundles Couchbase++ (downloading and building it if necessary).
Generally, there is no need to download and install it separately, and we recommend using the built-in Couchbase++.
There are binary Python wheels provided for Windows, and for Mac.
////


== Older Releases

Couchbase Python SDK 4.x is built upon Couchbase++, and SDK 3.x is built upon LCB (libcouchbase), but both conform to the xref:compatibility.adoc#api-version[3.x SDK API], and as such you may find the xref:3.2@python-sdk:project-docs:sdk-release-notes.adoc[3.x release notes] of use.
// end::all[] 
