= SDK Release Notes
:description: Release notes, installation instructions, and download archive for the Couchbase Python Client.
:navtitle: Release Notes
:page-partial:
:page-toclevels: 2
:page-topic-type: reference
:page-aliases: ROOT:relnotes-python-sdk,ROOT:download-links,ROOT:release-notes,ROOT:sdk-release-notes

// tag::all[]
[abstract]
{description}

Couchbase Python SDK 4.x is built upon {cbpp}, and SDK 3.x is built upon LCB (libcouchbase), but both conform to the xref:project-docs:compatibility.adoc#api-version[SDK API 3.x].
The move to {cbpp} facilitates the introduction of xref:howtos:distributed-acid-transactions-from-the-sdk.adoc[distributed ACID transactions].

NOTE: Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.


== Installation

You may install previous versions of the SDK using pip (after installing the required xref:hello-world:start-using-sdk.adoc[dependencies])

[source,console]
----
$ python3 -m pip install git+https://github.com/couchbase/couchbase-python-client@VERSION
----

where VERSION is the version you wish to install. 
For example, to install version 4.1.0:

[source,console]
----
$ python3 -m pip install git+https://github.com/couchbase/couchbase-python-client@4.1.0
----

For more detailed installation instructions, see the xref:project-docs:sdk-full-installation.adoc[full installation guide].



[#latest-release]
== Python SDK 4.2 Releases

We always recommend using the latest version of the SDK -- it contains all of the latest security patches and support for new and upcoming features.
All patch releases for each dot minor release should be API compatible, and safe to upgrade;
any changes to expected behavior are noted in the release notes that follow.


=== Version 4.2.0 (March 2024)





== Python SDK 4.1 Releases

=== Version 4.1.12 (1 March 2024)

Version 4.1.12 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.12
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.12/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1555[PYCBC-1555]:
Fixed bootstrap `select_bucket` logic to handle non-KV node.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1375[PYCBC-1375]:
Updated Query Index Management Create Index Key Encoding.

* https://issues.couchbase.com/browse/PYCBC-1550[PYCBC-1550]:
Added support for Scoped Search Indexes.

* https://issues.couchbase.com/browse/PYCBC-1523[PYCBC-1523]:
Updated configuration logic when 0xd response is received.

* https://issues.couchbase.com/browse/PYCBC-1525[PYCBC-1525]:
Added support for `LookupIn` and `MutateIn` macros.

* https://issues.couchbase.com/browse/PYCBC-1560[PYCBC-1560]:
Updated `ViewQueryOptions` to include `full_set` and `raw` options.

==== Underlying C++ SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-284[CXXCBC-284]:
Updated config polling to not use session that is not bootstrapped (https://github.com/couchbaselabs/couchbase-cxx-client/pull/528[#528]).

* https://issues.couchbase.com/browse/CXXCBC-345[CXXCBC-345]:
Added range scan improvements and resolved concurrency issues (https://github.com/couchbaselabs/couchbase-cxx-client/pull/525[#525]).

* https://issues.couchbase.com/browse/CXXCBC-421[CXXCBC-421]:
Updated query operation to return `feature_not_available` if query preserve expiry is specified but is not supported on the server(https://github.com/couchbaselabs/couchbase-cxx-client/pull/510[#510]).

* https://issues.couchbase.com/browse/CXXCBC-431[CXXCBC-431]:
Added check for history retention bucket capability in collection create/update (https://github.com/couchbaselabs/couchbase-cxx-client/pull/502[#502], https://github.com/couchbaselabs/couchbase-cxx-client/pull/505[#505]).

* https://issues.couchbase.com/browse/CXXCBC-447[CXXCBC-447]:
Updated bootstrap logic to use addresses from the config to bootstrap bucket (https://github.com/couchbaselabs/couchbase-cxx-client/pull/516[#516]).

* https://issues.couchbase.com/browse/CXXCBC-450[CXXCBC-450]:
Updated bootstrap logic to reset bootstrap handler before re-bootstrap (https://github.com/couchbaselabs/couchbase-cxx-client/pull/524[#524]).
** We do not want any actions from old bootstrap handler once the session decided to re-bootstrap. For example, bucket could not be selected, but we might still get configuration responses before socket reset.

* https://issues.couchbase.com/browse/CXXCBC-452[CXXCBC-452]:
Updated capabilities and fail fast when selected feature is not available. (https://github.com/couchbaselabs/couchbase-cxx-client/pull/522[#522], https://github.com/couchbaselabs/couchbase-cxx-client/pull/513[#513]).

* https://issues.couchbase.com/browse/CXXCBC-456[CXXCBC-456]:
Updated configuration logic when 0x0d (`EConfigOnly`) status code is received to have the SDK request new configuration and send current operation to retry orchestrator (https://github.com/couchbaselabs/couchbase-cxx-client/pull/523[#523]).


=== Version 4.1.11 (1 February 2024)

Version 4.1.11 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.11
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.11/

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1549[PYCBC-1549]:
Added support for `maxTTL` value of -1 for collection "no expiry".

==== Underlying C++ SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-284[CXXCBC-284]:
Reduced network traffic when polling for cluster configuration (https://github.com/couchbaselabs/couchbase-cxx-client/pull/504[#504]).
* https://issues.couchbase.com/browse/CXXCBC-421[CXXCBC-421]:
Updated query response to return `feature_not_available` when query preserve expiry is not supported (https://github.com/couchbaselabs/couchbase-cxx-client/pull/510[#510]).
* https://issues.couchbase.com/browse/CXXCBC-422[CXXCBC-422]:
Added insufficient credentials error code to common query error code conversion (https://github.com/couchbaselabs/couchbase-cxx-client/pull/511[#511]).
* https://issues.couchbase.com/browse/CXXCBC-431[CXXCBC-431]:
Added check for history retention bucket capability for collection create/update (https://github.com/couchbaselabs/couchbase-cxx-client/pull/502[#502], https://github.com/couchbaselabs/couchbase-cxx-client/pull/505[#505]).
* https://issues.couchbase.com/browse/CXXCBC-446[CXXCBC-446]:
Improved log formatting (https://github.com/couchbaselabs/couchbase-cxx-client/pull/506[#506], https://github.com/couchbaselabs/couchbase-cxx-client/pull/508[#508], https://github.com/couchbaselabs/couchbase-cxx-client/pull/509[#509]).


=== Version 4.1.10 (3 January 2024)

Version 4.1.10 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.10
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.10/

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1499[PYCBC-1499]:
Added improvements for Faster Failover and Config Push.

* https://issues.couchbase.com/browse/PYCBC-1545[PYCBC-1545]:
Added support for new KV error code to raise `DocumentNotLockedException`.

==== Underlying C++ SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-100[CXXCBC-100]:
Added support for using a timeout with `ping` operation (https://github.com/couchbaselabs/couchbase-cxx-client/pull/486[#486]).
* https://issues.couchbase.com/browse/CXXCBC-368[CXXCBC-368]:
Added support for subscribing to clustermap notifications to speedup failover (https://github.com/couchbaselabs/couchbase-cxx-client/pull/490[#490]).
* https://issues.couchbase.com/browse/CXXCBC-391[CXXCBC-391]:
Fixed transactions API inconsistencies (https://github.com/couchbaselabs/couchbase-cxx-client/pull/482[#482]).
* https://issues.couchbase.com/browse/CXXCBC-403[CXXCBC-403]:
Updated `not_my_vbucket` KV response to allow retries (https://github.com/couchbaselabs/couchbase-cxx-client/pull/480[#480]).
* https://issues.couchbase.com/browse/CXXCBC-404[CXXCBC-404]:
Fixed `unlock` operations to expose `KV_LOCKED` status as `cas_mismatch` (https://github.com/couchbaselabs/couchbase-cxx-client/pull/479[#479]).
* https://issues.couchbase.com/browse/CXXCBC-409[CXXCBC-409]:
Added handling for `index does not exist` query error (https://github.com/couchbaselabs/couchbase-cxx-client/pull/492[#492]).
* https://issues.couchbase.com/browse/CXXCBC-419[CXXCBC-419]:
Updated MCBP protocol parser to start with clean state (https://github.com/couchbaselabs/couchbase-cxx-client/pull/496[#496]).


=== Version 4.1.9 (14 November 2023)

Version 4.1.9 is the next patch release of the fourth generation Python SDK, bringing a number of improvements. 
Most notably the 4.1.9 release removes the `OpenSSL` dependency for published wheels and added _musllinux_ wheels for supported alpine environments.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.9
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.9/

==== Behavioral Change

The Couchbase Python SDK now publishes wheels that statically link against BoringSSL.  
The change removes the `OpenSSL` requirement from the SDK when using a published wheel. 
If building the SDK from source, the build will default to dynamically linking with the system provided `OpenSSL`.  
Build options are availalbe if wanting to build from source and statically link against BoringSSL.  
Also, published wheels dynamically link against stdlibs where previously the default was to statically link against stdlibs.  
Build options are available if wanting to build from source and statically link against stdlibs.

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1538[PYCBC-1538]:
Fixed `get` with projections to not fail with `InvalidArgumentException` when projecting on more than 16 fields.

* https://issues.couchbase.com/browse/PYCBC-1534[PYCBC-1534]:
Fixed `MutateIn` replace operation to not fail if path is empty.

* https://issues.couchbase.com/browse/PYCBC-1531[PYCBC-1531]:
Fixed `CollectionQueryIndexManager` to raise `InvalidArgumentException` when `scope_name` or `collection_name` options are set.

* https://issues.couchbase.com/browse/PYCBC-1521[PYCBC-1521]:
Fixed streaming APIs to use cluster timeout values from `ClusterTimeoutOptions` if provided.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1536[PYCBC-1536]:
Updated MANIFEST.in to only include necessary files for source install.

* https://issues.couchbase.com/browse/PYCBC-1518[PYCBC-1520],
https://issues.couchbase.com/browse/PYCBC-1520[PYCBC-1518]:
Updated published wheels to statically link against BoringSSL.

* https://issues.couchbase.com/browse/PYCBC-1515[PYCBC-1515]:
Added support for bucket settings for 'no dedup' feature.

* https://issues.couchbase.com/browse/PYCBC-1512[PYCBC-1512]:
Reduced default HTTP Idle Timeout.

* https://issues.couchbase.com/browse/PYCBC-1495[PYCBC-1495]:
Updated wheels and build to dynamically link against stdlibs by default.

==== Underlying C++ SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-387[CXXCBC-387]:
Optimising tags for `noop_tracer` and cache formatted `mbcp_session` endpoints (https://github.com/couchbaselabs/couchbase-cxx-client/pull/461[#461], https://github.com/couchbaselabs/couchbase-cxx-client/pull/462[#462], https://github.com/couchbaselabs/couchbase-cxx-client/pull/464[#464]).
* https://issues.couchbase.com/browse/CXXCBC-383[CXXCBC-383]:
Map `subdoc_doc_too_deep` KV status to `path_too_deep` error code (https://github.com/couchbaselabs/couchbase-cxx-client/pull/455[#455]).
* https://issues.couchbase.com/browse/CXXCBC-377[CXXCBC-377]:
Implement `ExtParallelUnstaging` in transactions (https://github.com/couchbaselabs/couchbase-cxx-client/pull/457[#457]).
* https://issues.couchbase.com/browse/CXXCBC-386[CXXCBC-386]:
Allow option to statically link against BoringSSL (https://github.com/couchbaselabs/couchbase-cxx-client/pull/458[#458], https://github.com/couchbaselabs/couchbase-cxx-client/pull/465[#465], https://github.com/couchbaselabs/couchbase-cxx-client/pull/471[#471], https://github.com/couchbaselabs/couchbase-cxx-client/pull/474[#474], https://github.com/couchbaselabs/couchbase-cxx-client/pull/478[#478]).
* https://issues.couchbase.com/browse/CXXCBC-376[CXXCBC-376]:
Revisit what 'create' and 'update' bucket operations send to the server. 
Make optional bucket settings fields optional, and do not send anything unless the settings explicitly specified (https://github.com/couchbaselabs/couchbase-cxx-client/pull/451[#451]).
* https://issues.couchbase.com/browse/CXXCBC-374[CXXCBC-374]:
Return 'bucket_exists' error when the bucket already exists during 'create' operation (https://github.com/couchbaselabs/couchbase-cxx-client/pull/449[#449]).
* https://issues.couchbase.com/browse/CXXCBC-359[CXXCBC-359]:
Reduced the default timeout for idle HTTP connections to 1 second. 
The previous default (4.5 seconds) was too close to the 5-second server-side timeout, and could lead to spurious request failures (https://github.com/couchbaselabs/couchbase-cxx-client/pull/448[#448]).
* https://issues.couchbase.com/browse/CXXCBC-367[CXXCBC-367];
https://issues.couchbase.com/browse/CXXCBC-370[CXXCBC-370]:
Added history retention settings to buckets/collection management (https://github.com/couchbaselabs/couchbase-cxx-client/pull/446[#446]).
* https://issues.couchbase.com/browse/CXXCBC-119[CXXCBC-119]:
Return booleans for subdocument 'exists' operation instead of error code (https://github.com/couchbaselabs/couchbase-cxx-client/pull/444[#444], https://github.com/couchbaselabs/couchbase-cxx-client/pull/452[#452]).
* Add more information to diagnose timeouts on NMVB responses (https://github.com/couchbaselabs/couchbase-cxx-client/pull/475[#475]).


=== Version 4.1.8 (25 August 2023)

Version 4.1.8 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.8
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.8/

==== Behavioral Change

The Couchbase Python SDK no longer provides Python 3.7 wheels as Python 3.7 has reached https://peps.python.org/pep-0537/#lifespan[end-of-life]. See https://docs.couchbase.com/python-sdk/current/project-docs/compatibility.html#python-version-compat[Python Version Compatibility] for details.

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1514[PYCBC-1514]:
Fixed parsing of `LookupIn` options if provided for lookup-in operations.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1497[PYCBC-1497]:
Added support for Sub-Document Read from Replica.

==== Underlying C++ SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-362[CXXCBC-362]:
Removed node hostname port stripping logic from config parsing (https://github.com/couchbaselabs/couchbase-cxx-client/pull/438[#438]).
* https://issues.couchbase.com/browse/CXXCBC-340[CXXCBC-340]:
Added support for Query Read from Replica (https://github.com/couchbaselabs/couchbase-cxx-client/pull/435[#435]).
* https://issues.couchbase.com/browse/CXXCBC-341[CXXCBC-341],
https://issues.couchbase.com/browse/CXXCBC-365[CXXCBC-365]:
Added support for Sub-Document Read from Replica (https://github.com/couchbaselabs/couchbase-cxx-client/pull/436[#436], https://github.com/couchbaselabs/couchbase-cxx-client/pull/441[#441], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/443[#443]).


=== Version 4.1.7 (8 August 2023)

Version 4.1.7 is the next patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.7
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.7/

==== Behavioral Change

Since Python 3.7 has reached https://peps.python.org/pep-0537/#lifespan[end-of-life], the Couchbase Python SDK will no longer provide Python 3.7 wheels in future releases (>4.1.7). See https://docs.couchbase.com/python-sdk/current/project-docs/compatibility.html#python-version-compat[Python Version Compatibility] for details.

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1502[PYCBC-1502]:
Added `PasswordAuthenticator` validation.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1496[PYCBC-1496]:
Added support for Query with Read from Replica.

* https://issues.couchbase.com/browse/PYCBC-1419[PYCBC-1419]:
Added support for Native KV Range Scans.

* https://issues.couchbase.com/browse/PYCBC-1505[PYCBC-1504];
https://issues.couchbase.com/browse/PYCBC-1505[PYCBC-1505]:
Updated API documentation to provide correct information on `LockMode`.

* https://issues.couchbase.com/browse/PYCBC-1510[PYCBC-1510]:
Updated CONTRIBUTING.md to improve contributing guidelines.

* https://issues.couchbase.com/browse/PYCBC-1095[PYCBC-1095]:
Added Subdoc mutate-in deletions with a blank path.

==== Underlying C++ SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-349[CXXCBC-349]:
Allow to pass trust certificate by value (https://github.com/couchbaselabs/couchbase-cxx-client/pull/430[#430]).
** The change affects TLS v1.0 and v1.1 which are now disabled by default.
* https://issues.couchbase.com/browse/CXXCBC-343[CXXCBC-343]:
Continue bootsrap if DNS-SRV resolution fails (https://github.com/couchbaselabs/couchbase-cxx-client/pull/422[#422]).
* https://issues.couchbase.com/browse/CXXCBC-340[CXXCBC-340]:
Support Query with Read from Replica (https://github.com/couchbaselabs/couchbase-cxx-client/pull/429[#429]).
* https://issues.couchbase.com/browse/CXXCBC-339[CXXCBC-339]:
Disabled older TLS protocols (https://github.com/couchbaselabs/couchbase-cxx-client/pull/418[#418]).
* https://issues.couchbase.com/browse/CXXCBC-333[CXXCBC-333]:
Fixed parsing 'resolv.conf' on Linux. (https://github.com/couchbaselabs/couchbase-cxx-client/pull/416[#416]).
** The library might not ignore trailing characters when reading nameserver address from the file.
* https://issues.couchbase.com/browse/CXXCBC-242[CXXCBC-242]:
SDK Support for Native KV Range Scans (https://github.com/couchbaselabs/couchbase-cxx-client/pull/419[#419], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/423[#423], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/424[#424], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/426[#426], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/428[#428], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/431[#431], 
https://github.com/couchbaselabs/couchbase-cxx-client/pull/432[#432],  
https://github.com/couchbaselabs/couchbase-cxx-client/pull/433[#433],  
https://github.com/couchbaselabs/couchbase-cxx-client/pull/434[#434]).


=== Version 4.1.6 (13 July 2023)

Version 4.1.6 is the sixth patch release of the fourth generation Python SDK, bringing a number of improvements. Most notably the 4.1.6 release adds support for Python 3.11 and significantly reduces the size of published _manylinux_ wheels.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.6
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.6/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1500[PYCBC-1500]:
Added `max_expiry` to `CollectionSpec` for collections returned in `get_all_scopes()` result.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1473[PYCBC-1473]:
Added Support for Python 3.11.

* https://issues.couchbase.com/browse/PYCBC-1459[PYCBC-1459]:
Reduced size of manylinux wheels.

* https://issues.couchbase.com/browse/PYCBC-1494[PYCBC-1494]:
Updated API docs to include binary `multiOptions`.

* https://issues.couchbase.com/browse/PYCBC-1498[PYCBC-1498]:
Updated connection tests to only use valid mixed environment format.


=== Version 4.1.5 (8 June 2023)

Version `4.1.5` is the fifth patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.5
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.5/

==== Behavioral Change

Accessing content from an Exist operation with the `LookupInResult`'s `content_as` method now returns a boolean.
This boolean is `True` if the path exists, `False` otherwise. 
Prior to this change the SDK raised a `DocumentNotFoundException` if the path existed or `PathNotFoundException` if the path didn't exist.
The behavioral change aligns the Python SDK with Couchbase's https://github.com/couchbaselabs/sdk-rfcs/blob/master/rfc/0053-sdk3-crud.md[CRUD RFC].

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1480[PYCBC-1480]:
Fixed subdocument read operations to allow for null values.

* https://issues.couchbase.com/browse/PYCBC-1486[PYCBC-1486]:
Fixed broken imports for search `GeoBoundingBoxQuery`, `GeoDistanceQuery`, and `GeoPolygonQuery`.

* https://issues.couchbase.com/browse/PYCBC-1487[PYCBC-1487]:
Updated Transcoders to be able to decode value when `flags=0`.

* https://issues.couchbase.com/browse/PYCBC-1490[PYCBC-1490]:
Fixed `InternalServerFailureException` when executing a `Regex` Search query.

* https://issues.couchbase.com/browse/PYCBC-1493[PYCBC-1493]:
Updated search operations to correctly pass MutationState to {cpp} core.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1488[PYCBC-1488]:
Added `dump_configuration` to `ClusterOptions`.

* https://issues.couchbase.com/browse/PYCBC-1479[PYCBC-1479]:
Bundled Mozilla certificates with the library.
Source: https://curl.se/docs/caextract.html. 
Use the `disable_mozilla_ca_certificates` connection string option to disable the bundled certificates.
See https://docs.couchbase.com/python-sdk/current/howtos/managing-connections.html#ssl[Secure Connections] for more details.


==== Underlying C++ SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-328[CXXCBC-328]:
Fix socket reconnection during rebalance process
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/406[#406]).
** Several improvements have been implemented to make the library resilient to rapid topology changes when both DNS-SRV bootstrap is being used along with alternative addresses. 
The changes include:
*** Taking into account alternative hostname and ports during detection of added/removed nodes on configuration update.
*** Replacing node index tracking with hostname/port matching when restarting the connections -- 
this way the library ensures that no duplicate connections will be left, or live connections replaced by restarted session.
*** Improved logging of critical events during rebalance: restarting, preservation, and removing connections.


=== Version 4.1.4 (9 May 2023)

Version `4.1.4` is the fourth patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.4
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.4/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1469[PYCBC-1469]:
Added check to determine if Python interpreter is finalizing prior to logging.

* https://issues.couchbase.com/browse/PYCBC-1471[PYCBC-1471]:
Fixed `acouchbase` streaming API blocking behavior while when executing queries.

* https://issues.couchbase.com/browse/PYCBC-1474[PYCBC-1474]:
Fixed transaction error handling.

* https://issues.couchbase.com/browse/PYCBC-1475[PYCBC-1475]:
Updated exception classes to allow first positional arg to be a string message.

* https://issues.couchbase.com/browse/PYCBC-1477[PYCBC-1477]:
Fixed potential crash in certain scenarios that use `MutationState`.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1468[PYCBC-1468]:
Added replica read operations to API docs.

* https://issues.couchbase.com/browse/PYCBC-1472[PYCBC-1472]:
Updated API Docs to indicate expiry option should be a timedelta.

* https://issues.couchbase.com/browse/PYCBC-1478[PYCBC-1478]:
Added missing bootstrap timeouts to WAN Config Profile.

==== Underlying C++ SDK Core Changes

* https://issues.couchbase.com/browse/CXXCBC-31[CXXCBC-31]:
Allow the use of schemaless connection strings (e.g. `"cb1.example.com,cb2.example.com"`)
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/394[#394]).

* https://issues.couchbase.com/browse/CXXCBC-320[CXXCBC-320]:
Negative expiry in atr was leaving docs in a stuck state -- this has been fixed, with expiry atr now becoming an `int32_t`
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/393[#393]).

* https://issues.couchbase.com/browse/CXXCBC-318[CXXCBC-318]:
Always try TCP if UDP fails in DNS-SRV resolver
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/390[#390]).

* https://issues.couchbase.com/browse/CXXCBC-145[CXXCBC-145]:
Search query request raw option now used
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/380[#380]).

* https://issues.couchbase.com/browse/CXXCBC-144[CXXCBC-144]:
Search query on collections now no longer requires `scope_name`, as it can be inferred from the index
(https://github.com/couchbaselabs/couchbase-cxx-client/pull/379[#379]).


=== Version 4.1.3 (9 March 2023)

Version `4.1.3` is the third patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.3
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.3/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1443[PYCBC-1443]:
Fixed ssl import error.

* https://issues.couchbase.com/browse/PYCBC-1446[PYCBC-1446]:
Updated API Documentation.

* https://issues.couchbase.com/browse/PYCBC-1455[PYCBC-1455]:
Fixed build issue for Fedora 37 (gcc 12).

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1431[PYCBC-1431]:
Updated the SDK to handle new `query_context` changes.

* https://issues.couchbase.com/browse/PYCBC-1444[PYCBC-1444]:
Improved CertificateAuthenticator parameter validation.

* https://issues.couchbase.com/browse/PYCBC-1445[PYCBC-1445]:
Updated the SDK to only populate `allowed_sasl_mechanisms` if user explicitly chooses.


=== Version 4.1.2 (9 February 2023)

Version `4.1.2` is the second patch release of the fourth generation Python SDK, bringing a number of improvements. Most notably the `4.1.2` release provides improved performance for key-value operations.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.2
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.2/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1433[PYCBC-1433]:
Fixed initialization of legacy durability options in {cpp} bindings.

* https://issues.couchbase.com/browse/PYCBC-1434[PYCBC-1434]:
Added Python SDK and Python version to {cpp} `user_agent` option.

* https://issues.couchbase.com/browse/PYCBC-1441[PYCBC-1441]:
Fixed inconsistencies when handling of `MutationState` in streaming APIs.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1371[PYCBC-1371]:
Implemented `ChangePassword` feature in user management API.

* https://issues.couchbase.com/browse/PYCBC-1436[PYCBC-1436]:
Updated pre-commit iSort Revision.

* https://issues.couchbase.com/browse/PYCBC-1440[PYCBC-1440]:
Updated logging to get latest from {cpp} client.

* https://issues.couchbase.com/browse/PYCBC-1438[PYCBC-1438]:
Updated Test Suite/Framework.


=== Version 4.1.1 (14 December 2022)

Version `4.1.1` is the first patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.1
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.1/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1428[PYCBC-1428]:
Fixed view query `ViewOrdering` to allow user specified ordering to be applied.

* https://issues.couchbase.com/browse/PYCBC-1429[PYCBC-1429]:
Fixed defaults for boolean options in N1QL query `QueryOptions`.


=== Version 4.1.0 (3 November 2022)

Version `4.1.0` is the first minor release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.1.0
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.1.0/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1420[PYCBC-1420]:
Fixed potential `InternalSDKException` for replica read operations.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1402[PYCBC-1402]:
Added support for using PYCBC_LOG_LEVEL to create console logger.

* https://issues.couchbase.com/browse/PYCBC-1417[PYCBC-1417]:
Updated authentication error message for Bucket Hibernation.

* https://issues.couchbase.com/browse/PYCBC-1422[PYCBC-1422]:
Updated {cbpp} version to incorporate latest changes.

* https://issues.couchbase.com/browse/PYCBC-1167[PYCBC-1167]:
Added support for Serverless Execution Environments.

* https://issues.couchbase.com/browse/PYCBC-1423[PYCBC-1423]:
Added durability improvements.



== Python SDK 4.0 Releases

=== Version 4.0.5 (7 October 2022)

Version `4.0.5` is the fifth patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.0.5
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.5/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1312[PYCBC-1312];
https://issues.couchbase.com/browse/PYCBC-1407[PYCBC-1407]:
Fixed crash related to closing a cluster connection.

* https://issues.couchbase.com/browse/PYCBC-1409[PYCBC-1409]:
Updated to version of {cbpp} client that correctly closes HTTP connections.

* https://issues.couchbase.com/browse/PYCBC-1413[PYCBC-1413]:
Fixed possible streaming API exceptions when executing in threaded environment.

* https://issues.couchbase.com/browse/PYCBC-1415[PYCBC-1415]:
Updated async APIs to use correct future chaining method for read KV operations.

* https://issues.couchbase.com/browse/PYCBC-1416[PYCBC-1416]:
Fixed `txcouchbase` search API.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1405[PYCBC-1405]:
Updated legacy durability to use the internal {cbpp} client API.

* https://issues.couchbase.com/browse/PYCBC-1406[PYCBC-1406]:
Updated replica reads to use the internal {cbpp} client API.

* https://issues.couchbase.com/browse/PYCBC-1411[PYCBC-1411]:
Added support for LDAP authentication.

=== Version 4.0.4 (8 September 2022)

Version `4.0.4` is the fourth patch release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the `4.0.4` release added legacy durability to mutation operations, tracing, and metrics.

[source,bash]
----
$ python3 -m pip install couchbase==4.0.4
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.4/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1398[PYCBC-1398]:
Fixed potential crash when accessing `error_context` from a `base_exception` object.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Added Tracing API, including the ability to use an external tracer such as OpenTelemetry.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Added legacy durability to mutation operations.
This allows the use of client durability within operations that allow for a durability option.

* https://issues.couchbase.com/browse/PYCBC-1399[PYCBC-1399]:
Added Metrics API -- users can now provide a custom meter for logging metrics. 

* https://issues.couchbase.com/browse/PYCBC-1391[PYCBC-1391]:
Removed `_raw_metrics` property from streaming API Metrics result objects.

* https://issues.couchbase.com/browse/PYCBC-1392[PYCBC-1392]:
Updated `collection.exists()` logic to align with a recent change in the underlying {cbpp} client.
Users will no longer see an error if a document doesn't exist, instead the `resp.exists()` method will be needed to determine whether a document is there or not.

* https://issues.couchbase.com/browse/PYCBC-1395[PYCBC-1395]:
Updated build deferred index logic to align with recent change in {cbpp} client.


=== Version 4.0.3 (2 August 2022)

Version `4.0.3` is the third patch release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the `4.0.3` release added key-value replica read operations and improved memory performance.

[source,bash]
----
$ python3 -m pip install couchbase==4.0.3
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.3/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1201[PYCBC-1201];
https://issues.couchbase.com/browse/PYCBC-1282[PYCBC-1282];
https://issues.couchbase.com/browse/PYCBC-1382[PYCBC-1382]
Fixed memory leak in key-value Result objects.

* https://issues.couchbase.com/browse/PYCBC-1383[PYCBC-1383]:
Fixed memory leak in key-value Exception objects.

* https://issues.couchbase.com/browse/PYCBC-1386[PYCBC-1386]:
Fixed OpenSSL discovery for MacOS M1 platforms.

* https://issues.couchbase.com/browse/PYCBC-1389[PYCBC-1389]:
Removed typing-extensions dependency.

* https://issues.couchbase.com/browse/PYCBC-1390[PYCBC-1390]:
Fixed Search query results to forward metrics for user access.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1257[PYCBC-1257]:
Added replica reads.

* https://issues.couchbase.com/browse/PYCBC-1385[PYCBC-1385]:
Updated {cbpp} version.

* https://issues.couchbase.com/browse/PYCBC-1137[PYCBC-1137]:
Deprecated the `CounterResult` CAS property.

==== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Distributed tracing is not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Legacy durability operations are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1290[PYCBC-1290]:
Transactions for `txcouchbase` are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1321[PYCBC-1321]:
API docs for `txcouchbase` API are not yet available.


=== Version 4.0.2 (29 June 2022)

Version `4.0.2` is the second patch release of the fourth generation Python SDK, bringing a number of improvements.
Most notably the `4.0.2` release provides manylinux wheels which significantly improves the installation process on Linux platforms.

[source,console]
----
$ python3 -m pip install couchbase==4.0.2
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.2/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1370[PYCBC-1370]:
Added environment variables to direct CMake to use specified Python3 version.

* https://issues.couchbase.com/browse/PYCBC-1374[PYCBC-1374]:
Added option to dynamically link stdc++ libs.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-628[PYCBC-628];
https://issues.couchbase.com/browse/PYCBC-1330[PYCBC-1330];
https://issues.couchbase.com/browse/PYCBC-1367[PYCBC-1367]:
Added manylinux wheels.

* https://issues.couchbase.com/browse/PYCBC-1232[PYCBC-1232];
https://issues.couchbase.com/browse/PYCBC-1368[PYCBC-1368]:
Created custom spdlog sink for pass-through logging to python logging.

* https://issues.couchbase.com/browse/PYCBC-1373[PYCBC-1373]:
Provided example Linux build system Dockerfiles.

* https://issues.couchbase.com/browse/PYCBC-1332[PYCBC-1332]:
Added formatting and linting to CI pipeline.

==== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1257[PYCBC-1257]:
Replica reads are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Distributed tracing is not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Legacy durability operations are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1290[PYCBC-1290]:
Transactions for txcouchbase are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1321[PYCBC-1321]:
API docs for txcouchbase API are not yet available.


=== Version 4.0.1 (9 June 2022)

Version 4.0.1 is the first patch release of the fourth generation Python SDK, bringing a number of improvements.

[source,bash]
----
$ python3 -m pip install couchbase==4.0.1
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.1/

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-1324[PYCBC-1324]:
Fixed N1QL Query options `scan_wait/scan_cap` misspelling.

* https://issues.couchbase.com/browse/PYCBC-1335[PYCBC-1335]:
Fixed issue where positional and named parameters were not used in `TransactionQueryOptions`.

* https://issues.couchbase.com/browse/PYCBC-1336[PYCBC-1336]:
Fixed crash when using `ViewOptions` keys parameter.

* https://issues.couchbase.com/browse/PYCBC-1342[PYCBC-1342]:
Fixed the txcouchbase API Bucket Management API.

* https://issues.couchbase.com/browse/PYCBC-1343[PYCBC-1343]:
Fixed the txcouchbase Collection Management API.

==== Enhancements

* https://issues.couchbase.com/browse/PYCBC-1328[PYCBC-1328]
Implemented txcouchbase test suite.

* https://issues.couchbase.com/browse/PYCBC-1320[PYCBC-1320]:
Added acouchbase core API Docs.

* https://issues.couchbase.com/browse/PYCBC-1329[PYCBC-1329]:
Cleaned up the acouchbase API test suite.

* https://issues.couchbase.com/browse/PYCBC-1331[PYCBC-1331]:
Updated streaming API options tests to validate all parameters.

* https://issues.couchbase.com/browse/PYCBC-1333[PYCBC-1333]:
Updated README, API docs for 4.0.1 release.

* https://issues.couchbase.com/browse/PYCBC-1334[PYCBC-1334]:
Cleaned up couchbase API test suite.

* https://issues.couchbase.com/browse/PYCBC-1358[PYCBC-1358]:
Updated Windows wheel to dynamically link against OpenSSL.

==== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1232[PYCBC-1232]:
Core IO logging is not forwarded through to Python.

* https://issues.couchbase.com/browse/PYCBC-1257[PYCBC-1257]:
Replica reads are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Distributed tracing is not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Legacy durability operations are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1290[PYCBC-1290]:
Transactions for txcouchbase are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1321[PYCBC-1321]:
API docs for txcouchbase API are not yet available.


=== Version 4.0.0 (6 May 2022)

Version 4.0.0 is the first major release of the next generation Python SDK, built on the Couchbase++ library -- featuring multi-document distributed ACID transactions, and bringing a number of improvements to the SDK.

[source,console]
----
$ python3 -m pip install couchbase==4.0.0
----

*API Docs:* http://docs.couchbase.com/sdk-api/couchbase-python-client-4.0.0/

==== New Features

* Support for distributed transactions has now been implemented.
* Reimplemented the library using couchbase++.
* Improved alignment between couchbase, acouchbase and txcouchbase APIs.
* Support for Python versions 3.7 - 3.10.
* Improved API documentation.

==== Fixes

* https://issues.couchbase.com/browse/PYCBC-849[PYCBC-849]:
Implemented wait until ready.

* https://issues.couchbase.com/browse/PYCBC-1146[PYCBC-1146]:
Aligned multi key-value methods with couchbase API.

* https://issues.couchbase.com/browse/PYCBC-1280[PYCBC-1280]:
Fixed implementation of the `CertificateAuthenticator`.

* https://issues.couchbase.com/browse/PYCBC-1296[PYCBC-1296]:
Updated `SearchRow` to not print locations when not included.

==== Known Issues

* https://issues.couchbase.com/browse/PYCBC-1232[PYCBC-1232]:
Core IO logging is not forwarded through to Python.

* https://issues.couchbase.com/browse/PYCBC-1257[PYCBC-1257]:
Replica reads are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1261[PYCBC-1261]:
Distributed tracing is not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1276[PYCBC-1276]:
Legacy durability operations are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1290[PYCBC-1290]:
Transactions for txcouchbase are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1319[PYCBC-1319]:
Management APIs for txcouchbase are not yet supported.

* https://issues.couchbase.com/browse/PYCBC-1320[PYCBC-1320]:
API docs for acouchbase API are not yet available.

* https://issues.couchbase.com/browse/PYCBC-1321[PYCBC-1321]:
API docs for txcouchbase API are not yet available.

* https://issues.couchbase.com/browse/PYCBC-1322[PYCBC-1322]:
Scoped transactional queries currently throw a `TransactionFailed` error.







////

// Don't think we really need this?

== Upgrading to 4.x

Python SDK 4.x automatically bundles Couchbase++ (downloading and building it if necessary).
Generally, there is no need to download and install it separately, and we recommend using the built-in Couchbase++.
There are binary Python wheels provided for Windows, and for Mac.
////


== Older Releases

For documentation on older releases please refer to the xref:3.2@python-sdk:project-docs:sdk-release-notes.adoc[3.x release notes] page.
// end::all[] 
