= Couchbase Python SDK Installation
:description: Installation instructions for the Couchbase Python Client.
:navtitle: Full Installation
:page-partial:
:page-topic-type: project-doc

[abstract]
{description}




This page covers installation of the SDK.
A quick start guide in our xref:hello-world:start-using-sdk.adoc#[Getting Started Guide] should work for most users --
and for anyone in a hurry to try out the SDK and our _Hello World_ program, that page is usually the best place to get started --
but more detailed installation instructions are provided here on this page for every supported platform.
This guide assumes you have some familiarity with development using Python -- if you are evaluating the SDK as a software architect, tester, or other non-Python role, you will benefit from our xref:hello-world:platform-help.adoc#[Platform Help page].







// tag::prep[]
The Couchbase SDK 3.x API (used in the Python SDK 3.0 - 4.0) is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area, and adding support for Couchbase Server features like xref:concept-docs:collections.adoc[Collections and Scopes] (available from Couchbase Server 7.0).

3.x Python SDK introduced comprehensive https://www.python.org/dev/peps/pep-0484/[PEP-484] style type annotations.


== Requirements

Couchbase Python SDK bundles Couchbase++ automatically, so no need to install it separately.
You may need CMake to install, although the installer will attempt to download it from PyPI automatically.

The Python SDK 4.x requires Python 3, with versions 3.7 - 3.10 supported. See the xref:project-docs:compatibility.adoc#python-version-compat[Compatibility] section for details.

[NOTE]
====
Currently the Python Client source distribution requires the OpenSSL headers and libraries that the Python client itself was built against to be installed prior to the client itself for TLS support to be provided.
Additionally the installer relies on PEP517 which older versions of PIP do not support.
If you experience issues installing it is advised to upgrade your PIP/setuptools installation as follows:
[source,console]
----
$ python3 -m pip install --upgrade pip setuptools wheel
----
====

// end::prep[]

// tag::install[]
[{tabs}] 
====
macOS::
+
--
Best practice is to use a Python virtual environment such as _venv_ or _pyenv_ to manage multible versions of Python, but in cases where this is not practicable follow the `brew` steps below, and also modify your `$PATH` as shown.

NOTE: There can be a problem when using the Python (3.8.2) that ships with Xcode on Catalina. 
It is advised to install Python via https://github.com/pyenv/pyenv#homebrew-on-macos[pyenv^]
(see the Python SDK https://github.com/couchbase/couchbase-python-client#mac-os-pyenv-install[Github README^] for further details on pyenv installation), http://brew.sh/[Homebrew^], or https://www.python.org/downloads[python.org^]

To install the library on Mac OS, first install http://brew.sh/[Homebrew^]. 

NOTE: Later versions of Mac OS can break the python3 homebrew installer. 
Simple mitigating steps may be found https://stackoverflow.com/questions/47255517/brew-install-python3-didnt-install-pip3[here^].

The following example uses the Python supplied by the _Homebrew_ package manager and not the vendor-supplied Python which ships with Mac OS. Once _Homebrew_ is configured:

.Get a list of the latest packages
[source,console]
----
$ brew update
----

.Install compatible Python 3
[source,console]
----
$ brew install python3
----

.For ZSH (MacOS 10.15 Catalina and newer)
[source,console]
----
$ echo 'export PATH="/usr/local/bin:"$PATH' >> ~/.zshrc
----

.For BASH (MacOS 10.14 Mojave and older)
[source,console]
----
$ echo 'export PATH="/usr/local/bin:"$PATH' >> ~/.bash_profile
----

.For TLS/SSL support - recommended

Best practice is to use a secure connection.
However, since some scenarios don't require a secure connection, TLS support is recommended but not required.

NOTE: Connecting to Couchbase Capella _requires_ TLS support.

[source,console]
----
$ brew install openssl
----


Install the latest Python SDK:

[source,console]
----
$ sudo -H python3 -m pip install couchbase
----
--

Debian & Ubuntu::
+
--
Best practice is to use a Python virtual environment such as _venv_ or _pyenv_ to manage multible versions of Python. 
See https://github.com/pyenv/pyenv#basic-github-checkout[pyenv docs^] for details.

During first-time setup:

[source,console]
----
$ sudo apt-get install git-all python3-dev python3-pip python3-setuptools cmake build-essential
----

For TLS/SSL support (recommended):

NOTE: Connecting to Couchbase Capella _requires_ TLS support.

[source,console]
----
$ sudo apt-get install libssl-dev
----

First, make sure the <<linux, requirements>> have been installed.

Install the latest Python SDK:

[source,console]
----
$ python3 -m pip install couchbase
----
--

RHEL & CentOS::
+
--
Best practice is to use a Python virtual environment such as _venv_ or _pyenv_ to manage multible versions of Python. 
See https://github.com/pyenv/pyenv#basic-github-checkout[pyenv docs^] for details.

During first-time setup:

[source,console]
----
$ sudo yum install gcc gcc-c++ python3-devel python3-pip cmake
----

TIP: You may need to update your installed version of CMake.
For example, by following the steps https://idroot.us/install-cmake-centos-8[here^].

For TLS/SSL support (recommended):

NOTE: Connecting to Couchbase Capella _requires_ TLS support.

[source,console]
----
$ sudo yum install openssl-devel
----

NOTE: RHEL/CentOS distributions may not provide the `python3-pip` package in the base repositories.
It may be found in the https://fedoraproject.org/wiki/EPEL[EPEL^] repository.

First, make sure the <<linux, requirements>> have been installed.

Install the latest Python SDK:

[source,console]
----
$ python3 -m pip install couchbase
----
--

Windows::
+
--
Download and install Python from https://www.python.org/downloads[python.org^].  
Best practice is to use a Python virtual environment such as _venv_ or _pyenv_.

TIP: Checkout the https://github.com/pyenv-win/pyenv-win[pyenv-win^] project to manage multiple versions of Python.

Wheels are available on Windows for Python 3.7, 3.8 and 3.9.

First, make sure the <<microsoft-windows, requirements>> have been installed.

NOTE: Commands assume user is working within a virtual environment.

Install the latest Python SDK (if using Python 3.7, 3.8 or 3.9):

[source,console]
----
python -m pip install couchbase
----

The standard Python distributions for Windows include OpenSSL DLLs, as PIP and the inbuilt `ssl` module require it for correct operation.
The binary wheels for Windows are packaged as a binary wheel built against the relevant version OpenSSL (which is fixed per Windows version of Python).

If you require a version without OpenSSL support, or that doesn't have a suitable binary wheel on PyPi, follow the https://github.com/couchbase/couchbase-python-client#alternative-installation-methods[build instructions] on the GitHub repo.
--

Anaconda/Miniconda::
+
--
To use the SDK within the Anaconda/Miniconda platform, make sure the prerequisites for the desired Operating System are met:

* <<linux, Linux>>
* <<mac-os, Mac OS>>
* <<microsoft-windows, Windows>>

In the _Anaconda Prompt_, create a new environment:
[source,console]
----
conda create -n test_env python=3.9
----

Activate the environment:
[source,console]
----
conda activate test_env
----

Install the SDK:
[source,console]
----
python -m pip install couchbase
----
--
====

NOTE: If using Windows, and no wheel is available, see the https://github.com/couchbase/couchbase-python-client#alternative-installation-methods[alternate installlation] methods on the Github README.  
The same process should work within the Anaconda/Miniconda platform.
// end::install[]


=== PyPy support

Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.

