= Full Installation
:description: Installation instructions for the Couchbase Python Client.
:page-partial:
:page-topic-type: reference

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}




This page covers installation of the SDK.
A quick start guide in our xref:hello-world:start-using-sdk.adoc#[Getting Started Guide] should work for most users --
and for anyone in a hurry to try out the SDK and our _Hello World_ program, that page is usually the best place to get started --
but more detailed installation instructions are provided here on this page for every supported platform.
This guide assumes you have some familiarity with development using Python -- if you are evaluating the SDK as a software architect, tester, or other non-Python role, you will benefit from our xref:hello-world:platform-help.adoc#[Platform Help page].







// tag::prep[]
The Couchbase SDK 3.x API (used in the Python SDK 3.0 - 4.0) is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area, and adding support for Couchbase Server features like xref:concept-docs:collections.adoc[Collections and Scopes] (available from Couchbase Server 7.0).

3.x Python SDK introduced comprehensive https://www.python.org/dev/peps/pep-0484/[PEP-484] style type annotations.


== Requirements

Couchbase Python SDK bundles Couchbase++ automatically, so no need to install it separately.
You may need CMake (a version >= 3.18) to install, although the installer will attempt to download it from PyPI automatically.

The Python SDK 4.x requires Python 3. See the xref:project-docs:compatibility.adoc#python-version-compat[Python Version Compatibility] section for details on supported versions of Python.

[NOTE]
====
Currently the Python Client source distribution requires the OpenSSL headers and libraries that the Python client itself was built against to be installed prior to the client itself.
Additionally the installer relies on PEP517 which older versions of PIP do not support.
If you experience issues installing it is advised to upgrade your PIP/setuptools installation as follows:
[source,console]
----
$ python3 -m pip install --upgrade pip setuptools wheel
----
====

// end::prep[]


== Installation

For xref:compatibility.adoc#platform-compatibility[supported Operating Systems]:

// tag::install[]
[{tabs}] 
====
macOS::
+
--
Best practice is to use a Python virtual environment such as _venv_ or _pyenv_ to manage multible versions of Python, but in cases where this is not practicable follow the `brew` steps below, and also modify your `$PATH` as shown.

The Python SDK has wheels are available on macOS for xref:compatibility.adoc#python-version-compat[supported versions of Python].

NOTE: There can be a problem when using the Python (3.8.2) that ships with Xcode on Catalina. 
It is advised to install Python via https://github.com/pyenv/pyenv#homebrew-on-macos[pyenv^]
(see the Python SDK https://github.com/couchbase/couchbase-python-client#mac-os-pyenv-install[Github README^] for further details on pyenv installation), http://brew.sh/[Homebrew^], or https://www.python.org/downloads[python.org^]

To install the library on Mac OS, first install http://brew.sh/[Homebrew^]. 

NOTE: Later versions of Mac OS can break the python3 homebrew installer. 
Simple mitigating steps may be found https://stackoverflow.com/questions/47255517/brew-install-python3-didnt-install-pip3[here^].

The following example uses the Python supplied by the _Homebrew_ package manager and not the vendor-supplied Python which ships with Mac OS. Once _Homebrew_ is configured:

.Get a list of the latest packages
[source,console]
----
$ brew update
----

.Install compatible Python 3
[source,console]
----
$ brew install python3
----

.For ZSH (MacOS 10.15 Catalina and newer)
[source,console]
----
$ echo 'export PATH="/usr/local/bin:"$PATH' >> ~/.zshrc
----

.For TLS/SSL support - required for Python SDK 4.x

[source,console]
----
$ brew install openssl@1.1
----

[source,console]
----
$ source ~/.zshrc
----

Install the latest Python SDK:

[source,console]
----
$ sudo -H python3 -m pip install couchbase
----

NOTE: Starting with Python 3.11.5, macOS installers from python.org now use https://docs.python.org/3/whatsnew/3.11.html#notable-changes-in-3-11-5[OpenSSL 3.0]. If using a version prior to 4.1.9 of the Python SDK, a potential side-effect of this change is an `ImportError: DLL load failed while importing pycbc_core` error. Upgrade the SDK to a version >= 4.1.9 to avoid this side-effect. If unable to upgrade, a work-around is to set the `PYCBC_OPENSSL_DIR` environment variable to the path where the OpenSSL 1.1 libraries (`libssl.1.1.dylib ` and `libcrypto.1.1.dylib`) can be found.

--

Debian & Ubuntu::
+
--
This SDK runs on top of the {cpp} core, Couchbase{plus}{plus}, which requires a {cpp} 17 compiler, such as GCC 8.0, or more recent versions. Older versions of Debian and Ubuntu ship with an older version of GCC.

IMPORTANT:  While workarounds are available for installing a newer build chain, some may not be within your company’s policy, so also take a look at container options -- such as the unofficial Docker builds provided in the Python SDK 4.x examples folder https://github.com/couchbase/couchbase-python-client/tree/master/examples/dockerfiles[here^], which can at least be used as a reference to a known working set-up.

Check that you have a new enough release of Python.

Best practice is to use a Python virtual environment such as _venv_ or _pyenv_ to manage multible versions of Python. 
See https://github.com/pyenv/pyenv#basic-github-checkout[pyenv docs^] for details.

The Python SDK has manylinux wheels available for xref:compatibility.adoc#python-version-compat[supported versions of Python].

During first-time setup:

[source,console]
----
$ sudo apt-get install git-all python3-dev python3-pip python3-setuptools build-essential
----

For TLS/SSL support (required for Python SDK 4.x):

[source,console]
----
$ sudo apt-get install libssl-dev
----

First, make sure the <<linux, requirements>> have been installed.

Install the latest Python SDK:

[source,console]
----
$ python3 -m pip install couchbase
----
--

RHEL & CentOS::
+
--
This SDK runs on top of the {cpp} core, Couchbase{plus}{plus}, which requires a {cpp} 17 compiler, such as GCC 8.0, or more recent versions. Older versions of Debian and Ubuntu ship with an older version of GCC.

IMPORTANT:  Workarounds are available for installing a newer build chain with https://fedoraproject.org/wiki/EPEL[EPEL^], but this may not be within your company’s policy, so also take a look at container options -- such as the unofficial Docker builds provided in the Python SDK 4.x examples folder https://github.com/couchbase/couchbase-python-client/tree/master/examples/dockerfiles[here^], which can at least be used as a reference to a known working set-up.

Check that you have a new enough release of Python, and if not then investigate the https://fedoraproject.org/wiki/EPEL[EPEL^] repository.

Best practice is to use a Python virtual environment such as _venv_ or _pyenv_ to manage multible versions of Python. 
See https://github.com/pyenv/pyenv#basic-github-checkout[pyenv docs^] for details.

The Python SDK has manylinux wheels available for xref:compatibility.adoc#python-version-compat[supported versions of Python].

During first-time setup:

[source,console]
----
$ sudo yum install gcc gcc-c++ python3-devel python3-pip
----

TIP: You may need to update your installed version of CMake.
For example, by following the steps https://idroot.us/install-cmake-centos-8[here^].

For TLS/SSL support (required for Python SDK 4.x):

[source,console]
----
$ sudo yum install openssl-devel
----

NOTE: RHEL/CentOS distributions may not provide the `python3-pip` package in the base repositories.
It may be found in the https://fedoraproject.org/wiki/EPEL[EPEL^] repository.

First, make sure the <<linux, requirements>> have been installed.

Install the latest Python SDK:

[source,console]
----
$ python3 -m pip install couchbase
----

Note, the OpenSSL version needed for TLS 1.3 (mandated for secure connection to Couchbase Capella) is openssl 1.1.1.
This is newer than the one available in CentOS 7, and updated your OS's libraries is beyond the scope of this documentation --
but this can be installed through the already-mentioned EPEL repository.
Once openssl (and other dependencies) are updated, an already-installed Couchbase Python SDK can be re-installed to use the libraries with:

[source,console]
----
$ python3 -m pip install --force-reinstall --no-cache couchbase
----
--

Windows::
+
--
Download and install Python from https://www.python.org/downloads[python.org^].  
Best practice is to use a Python virtual environment such as _venv_ or _pyenv_.

TIP: Checkout the https://github.com/pyenv-win/pyenv-win[pyenv-win^] project to manage multiple versions of Python.

The Python SDK has wheels available on Windows for xref:compatibility.adoc#python-version-compat[supported versions of Python].

First, make sure the <<microsoft-windows, requirements>> have been installed.

NOTE: Commands assume user is working within a virtual environment.

Install the latest Python SDK:

[source,console]
----
python -m pip install couchbase
----

NOTE: Starting with Python 3.11.5, Windows builds from python.org now use https://docs.python.org/3/whatsnew/3.11.html#notable-changes-in-3-11-5[OpenSSL 3.0]. If using a version prior to 4.1.9 of the Python SDK, a potential side-effect of this change is an `ImportError: DLL load failed while importing pycbc_core` error. Upgrade the SDK to a version >= 4.1.9 to avoid this side-effect. If unable to upgrade, a work-around is to set the `PYCBC_OPENSSL_DIR` environment variable to the path where the OpenSSL 1.1 libraries (`libssl-1_1.dll` and `libcrypto-1_1.dll`) can be found.

The standard Python distributions for Windows include OpenSSL DLLs, as PIP and the inbuilt `ssl` module require it for correct operation.
Prior to version 4.1.9 of the Python SDK, the binary wheels for Windows are built against OpenSSL 1.1.  Version 4.1.9 and beyond statically link against BoringSSL thus removing the OpenSSL requirement.

NOTE: If you require a version that doesn't have a suitable binary wheel on PyPI, follow the https://github.com/couchbase/couchbase-python-client#alternative-installation-methods[build instructions] on the GitHub repo.
--

Conda::
+
--
To use the SDK within the Anaconda / Miniconda platform, make sure the prerequisites for the desired Operating System are met:

`git-all python3-dev python3-pip python3-setuptools build-essential`

In the _Anaconda Prompt_, create a new environment:
[source,console]
----
conda create -n test_env python=3.9
----

Activate the environment:
[source,console]
----
conda activate test_env
----

Install the SDK:
[source,console]
----
python -m pip install couchbase
----

NOTE: If you require a version that doesn't have a suitable binary wheel on PyPI, follow the https://github.com/couchbase/couchbase-python-client#alternative-installation-methods[build instructions] on the GitHub repo.
--
====
// end::install[]


=== PyPy support

Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.

