= Install and Start Using the Python SDK with Couchbase Server
:description: Installing the Couchbase Python SDK & a Hello World example program.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK
:description: Get up and running quickly, installing the Couchbase Python SDK, and running our Hello World example.
:page-toclevels: 2
:page-partial:

include::project-docs:partial$attributes.adoc[]

[abstract]
{description}

The Couchbase Python SDK allows Python applications to access a Couchbase cluster.
It offers a traditional synchronous API as well as integration with _twisted_ and _asyncio_.


== Hello Couchbase

On this page we show you how to quickly get up and running -- installing the Couchbase Python SDK, and trying out the _Hello World_ code example against Couchbase Capella, or against a local Couchbase cluster.

We will go through the code sample step by step, but for those in a hurry to see it, here it is:

[{tabs}] 
==== 
Couchbase Capella Sample::
+
--
To connect to xref:cloud::index.adoc[Couchbase Capella], be sure to get the correct endpoint as well as user, password, certificate and bucket name  -- and see the <<cloud-connections, Cloud section>>, below.

[source,python]
----
include::hello-world:example$cloud.py[tag=cloud_connect]
----
--

Local Couchbase Server::
+ 
-- 
[source,python]
----
include::hello-world:example$hello_world_t.py[tag=connect]

include::hello-world:example$hello_world_t.py[tag=bucket]

include::hello-world:example$hello_world_t.py[tag=collection]

include::hello-world:example$hello_world_t.py[tag=upsert-func]

include::hello-world:example$hello_world_t.py[tag=get-func]

include::hello-world:example$hello_world_t.py[tag=lookup-func]

include::hello-world:example$hello_world_t.py[tag=test-doc]

include::hello-world:example$hello_world_t.py[tag=upsert-invoke]

include::hello-world:example$hello_world_t.py[tag=get-invoke]

include::hello-world:example$hello_world_t.py[tag=lookup-invoke]

----

As well as the Python SDK (see below), and a running instance of Couchbase Server, you will need to load up the Travel Sample Bucket
using either the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].
--
====

The Couchbase Capella free trial version comes with the Travel Sample Bucket, and its Query indexes, loaded and ready.


== Quick Installation

A more detailed guide in our xref:project-pages:sdk-full-installation.adoc[Installation page] covers every supported platform, but this section should be enough to get up and running in most cases.

[{tabs}] 
====
macOS 11 & 12::
+
--
If you are running Catalina (macOS 10.15) or earlier -- or have other detailed requirements -- take a look at our xref:project-pages:sdk-full-installation.adoc[full installation guide].
Otherwise, read on for a quick install on macOS _Big Sur_ or _Monterey_.

First, make sure that your _brew_ package index is up-to-date:
[source,console]
----
$ brew update
----

Install a compatible Python 3:
[source,console]
----
$ brew install openssl python3
----

Ensure that the Python installation can be called from the shell:
[source,console]
----
$ echo 'export PATH="/usr/local/bin:"$PATH' >> ~/.zshrc
----

Now, install the Python SDK:
[source,console]
----
$ sudo -H python3 -m pip install couchbase
----
--

Red Hat & CentOS::
+
--
During first-time setup, install the prerequisites:

[source,console]
----
$ sudo yum install gcc gcc-c++ python3-devel python3-pip cmake openssl-devel
----
Full details of prerequisites can be found xref:project-docs:sdk-full-installation.adoc#requirements[here].

Now you can install the latest Python SDK (for older versions, see the xref:project-docs:sdk-release-notes.adoc[Release Notes page]):

[source,console]
----
$ python3 -m pip install couchbase
----
--

Debian & Ubuntu::
+
--
During first-time setup, install the prerequisites:

[source,console]
----
$ sudo apt-get install git-all python3-dev python3-pip python3-setuptools cmake build-essential libssl-dev
----
Full details of prerequisites can be found xref:project-docs:sdk-full-installation.adoc#requirements[here].

Now you can install the latest Python SDK (for older versions, see the xref:project-docs:sdk-release-notes.adoc[Release Notes page]):

[source,console]
----
$ python3 -m pip install couchbase
----
--

Windows::
+
--
Download and install Python from https://www.python.org/downloads[python.org^].  
Best practice is to use a Python virtual environment such as _venv_ or _pyenv_.

TIP: Checkout the https://github.com/pyenv-win/pyenv-win[pyenv-win^] project to manage multiple versions of Python.

Wheels are available on Windows for Python 3.7, 3.8 and 3.9.

[source,console]
----
python -m pip install couchbase
----

The standard Python distributions for Windows include OpenSSL DLLs, as PIP and the inbuilt `ssl` module require it for correct operation.
The binary wheels for Windows are packaged as a binary wheel built against the relevant version OpenSSL (which is fixed per Windows version of Python).

If you require a version without OpenSSL support, or that doesn't have a suitable binary wheel on PyPi, follow the https://github.com/couchbase/couchbase-python-client#alternative-installation-methods[build instructions] on the GitHub repo.
--
====

If there are any problems, refer to the full xref:project-pages:sdk-full-installation.adoc[Installation page].


TIP: If you are evaluating the Python SDK as a tester, architect, or otherwise not a regular Python developer, our xref:platform-help.adoc[Platform Help] pages may help get you over any humps in the road.


== Step-by-Step

At this point we want to transition from the terminal to your code editor of choice.

Let's now create an empty file named `cb-test.py` and walk through adding code step-by-step:

* Connect to a cluster, bucket, and default collection;
* Add and retrieve a new document;
* Look up (SQL-type query) the new document by attribute value.

=== Prerequisites

Here are all of the import statements that you will need to run the sample code.

[source,python,indent=0]
----
from datetime import timedelta

# needed for any cluster connection
from couchbase.auth import PasswordAuthenticator
from couchbase.cluster import Cluster

# needed for options -- cluster, timeout, SQL++ (N1QL) query, etc.
from couchbase.options import (ClusterOptions,
                               ClusterTimeoutOptions,
                               QueryOptions)
----

=== Connection

The basic imports and connection string that you'll need are given below -- for more background information, refer to the xref:howtos:managing-connections.adoc#connection-strings[Managing Connections page].

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=connect]
----

Couchbase uses xref:{version-server}@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
For the sake of this example, we are connecting to Couchbase using the _Full Admin_ role created during the installation of our Couchbase Server.
The connection is being made to a single Couchbase node, running locally.

Couchbase RBAC is fully described in the section xref:{version-server}@server:manage:manage-security/manage-users-and-roles.adoc[Authorization].
An _authenticator_, containing username and password, should be defined, and then passed to the cluster.
Following successful authentication, the bucket can be opened:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=bucket]
----

NOTE: We are working with the link:https://docs.couchbase.com/server/current/manage/manage-settings/install-sample-buckets.html[travel-sample] data bucket. If you are not, substitute _travel-sample_ with your _bucket-name_.

If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Capella] rather than a local Couchbase Server, then also refer to the <<cloud-connections, Cloud section>>, below.

See xref:howtos:managing-connections.adoc[Managing Connections] for more connection options and details about the connection string.

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=collection]
----

The 3.2 SDK is ready for the introduction of xref:concept-docs:collections.adoc[Collections] in the xref:{version-server}@server:introduction:whats-new.adoc#whats-new-server-700[7.0 release] of the Couchbase Data Platform.
The latest release, Couchbase Server 7.0, brings Collections, allowing Documents to be grouped by purpose or theme, according to specified _Scope_.

NOTE: This feature was previously available as a _developer preview_ from Couchbase Server 6.6. _When connecting to a 6.6 cluster or earlier_, we must use the `DefaultCollection`, which covers the whole Bucket.

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=default-collection]
----

=== Document Addition and Retrieval

Let's create a dictionary object in our application that we can add to our `travel-sample` bucket that conforms to the structure of a document of type `airline`.

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=test-doc]
----

xref:howtos:kv-operations.adoc[Document operations], such as storing and retrieving documents, can be done using simple methods on the `Collection` class such as `Collection.get` and `Collection.upsert`.
Simply pass the key (and value, if applicable) to the relevant methods.

The following function will `upsert()` a document and print the returned link:https://docs.couchbase.com/python-sdk/3.2/howtos/concurrent-document-mutations.html[CAS] value:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=upsert-func]
----

Now, we can simply call the `upsert_document` function passing in our `airline` document:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=upsert-invoke]
----

Now let's retrieve that document using a key-value operation. The following function runs a `get()` for a document key and either logs out the result or error in our console:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=get-func]
----

Key-value Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].

Now, we can simply call the `get_airline_by_key` function passing in our valid document key `airline_8091`:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=get-invoke]
----


=== SQL++ Lookup

Couchbase N1QL queries are performed by invoking the `Cluster.query()` method.  The following function executes a lookup for documents of `type='airline'` by a provided `callsign`:

[source,python]
----
include::../examples/hello_world_t.py[tag=lookup-func]
----

We call the `lookup_by_callsign` function passing in our callsign `CBS`:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=lookup-invoke]
----

=== Execute!

Now we can run our code using the following command:

[source,console]
----
$ python3 cb-test.py
----

The results you should expect are as follows:

[source,console]
----
Upsert CAS:
1598469741559152640

Get Result:
{'type': 'airline', 'id': 8091, 'callsign': 'CBS', 'iata': None, 'icao': None, 'name': 'Couchbase Airways'}

Lookup Result:
Couchbase Airways
----


== Next Steps

Now you're up and running, try one of the following:

// Should search and analytics be removed?

* Our xref:hello-world:sample-application.adoc[Travel Sample Application] demonstrates all the basics you need to know;
* Explore xref:howtos:kv-operations.adoc[Key Value Operations] (CRUD) against a document database;
* Or xref:howtos:n1ql-queries-with-sdk.adoc[Query] with our SQL-based N1QL language
* Try longer-running queries with our xref:howtos:analytics-using-sdk.adoc[Analytics Service];
* A xref:howtos:full-text-searching-with-sdk.adoc[Full Text Search];
* Or read up on xref:concept-docs:data-services.adoc[which service fits your use case].

=== Additional Resources

The API reference is generated for each release and the latest can be found http://docs.couchbase.com/sdk-api/couchbase-python-client/[here].

Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Individual Release Notes].
Most of the API documentation can also be accessed via `pydoc`.

xref:project-docs:migrating-sdk-code-to-3.n.adoc[Migration page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Python SDK.
The Python SDK source code is available on https://github.com/couchbase/couchbase-python-client[GitHub].

=== Troubleshooting

* Couchbase Server is designed to work in the same WAN or availability zone as the client application.
If you're running the SDK on your laptop against a Capella cluster, see further information on:
** Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
** xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
** If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].
* Our https://forums.couchbase.com/c/python-sdk/10[community forum] is a great source of help.
