= Install and Start Using the Python SDK with Couchbase Server
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK
:page-partial:

[abstract]
The Couchbase Python SDK allows Python applications to access a Couchbase cluster.
The Python SDK offers a traditional synchronous API as well as integration with _twisted_, _gevent_, and _asyncio_.
It depends on the C SDK, _libcouchbase_, which it uses for performance and reliability.

// tag::prep[]

The Couchbase Python SDK 3.0 is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area, and adding support for future Couchbase Server features like Collections and Scopes (available in Couchbase Server 6.5 as a xref:concept-docs:collections.adoc[developer preview]).
The 3.0 Python SDK introduces comprehensive https://www.python.org/dev/peps/pep-0484/[PEP-484] style type annotations.



== Requirements

Couchbase Python SDK bundles libcouchbase automatically, so no need to install it separately.
You may need cmake to install, although the installer will attempt to download it from PyPI automatically.

The Python SDK 3.0 requires Python 3, with Python 3.5 and above supported.

// end::prep[]

// tag::install[]

[NOTE]
====
Currently the Python Client source distribution requires the OpenSSL headers and libraries that the Python client itself was built against to be installed prior to the client itself for TLS support to be provided. 
Additionally the installer relies on PEP517 which older versions of PIP do not support. 
If you experience issues installing it is advised to upgrade your PIP/setuptools installation as follows: 
[source,console]
----
$ python3 -m pip install --upgrade pip setuptools wheel
----
====


== Installing on Linux

.Debian and Ubuntu
[source,console]
----
# Only needed during first-time setup:
sudo apt-get install git-all python3-dev python3-pip python3-setuptools cmake build-essential

# for TLS/SSL support (optional)
sudo apt-get install libssl-dev

python3 -m  pip install couchbase

----

.RHEL and CentOS
[source,console]
----
# Only needed during first-time setup:
sudo yum install gcc gcc-c++ python-devel python-pip cmake

# for TLS/SSL support (optional)
sudo yum install openssl-devel

python -m pip install couchbase
----

NOTE: RHEL/CentOS distributions may not provide the `python-pip` package in the base repositories.
It may be found in the https://fedoraproject.org/wiki/EPEL[EPEL^] repository.

== Installation on Mac OS X

To install the library on Mac OS X, first install the de-facto package manager for OS X: http://brew.sh/[Homebrew^].
Once _Homebrew_ is configured:

[source,console]
----
$ brew update # get list of latest packages
----

[source,console]
----
$ brew install python
----

[source,console]
----
$ brew install openssl # for TLS/SSL support - optional
----

[source,console]
----
$ python -m pip install couchbase
----

NOTE: The above example uses the Python supplied by Homebrew and not the vendor-supplied Python which ships with OS X.
The Python SDK will still work with the vendor-supplied Python (though _pip install_ may be a privileged command), but it is recommended to use Homebrew's Python instead.

== Installing on Microsoft Windows

[source,console]
----
$ python -m pip install couchbase
----

The standard Python distributions for Windows include OpenSSL DLLs, as PIP and the inbuilt `ssl` module require it for correct operation. 
The binary wheels for Windows are packaged as a binary wheel built against the relevant version OpenSSL (which is fixed per Windows version of Python).

If you require a version without OpenSSL support, or that doesn't have a suitable binary wheel on PyPi, follow the build instructions on the GitHub repo.

// end::install[]


== Hello Couchbase

The code snippet below shows how the Python SDK may be used for some common operations.

[source,python]
----
include::example$hello_world_t.py[tag=intro]
----

=== Connecting

To connect to a Couchbase bucket, you must use Couchbase _Role-Based Access Control_ (RBAC).
This is fully described in the section xref:6.5@server:manage:manage-security/manage-users-and-roles.adoc[Authorization].
An _authenticator_, containing username and password, should be defined, and then passed to the cluster.
Following successful authentication, the bucket can be opened:

[source,python]
----
include::example$hello_world_t.py[tag=connecting]
----

Once defined, the authenticator can be passed to other clusters, as appropriate.

If you are connecting to Couchbase Cloud rather than a local Couchbase Server, then also refer to the <<cloud-connections, Cloud section>>, below.

See xref:howtos:managing-connections.adoc[Managing Connections] for more connection options and details about the connection string.

=== Document Operations

xref:howtos:kv-operations.adoc[Document operations], such as storing and retrieving documents, can be done using simple methods on the `Bucket` class such as `Bucket.get` and `Bucket.upsert`.
Simply pass the key (and value, if applicable) to the relevant methods.

[source,python]
----
include::example$hello_world_t.py[tag=docopsget]
----

[source,python]
----
include::example$hello_world_t.py[tag=docopsupsert]
----

=== N1QL Queries

Couchbase N1QL queries are performed by running the `Cluster.query` method.

[source,python]
----
include::example$hello_world_t.py[tag=n1ql]
----


== PyPy support

Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.

Please let us know if you require a PyPy-compatible version of the SDK.


== Cloud Connections

For developing on Couchbase Cloud, 
try the https://github.com/couchbase/docs-sdk-python/blob/release/3.0/modules/devguide/examples/python/cloud.py[Cloud-based Hello World program].

If you are not working from the same _Availability Zone_ as your Couchbase Cloud, refer to the follorwing:

* Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments], 
* xref:project-docs:compatibility.adoc#network-requirements[Network Requirements], 
* If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].


== Additional Resources

The API reference is generated for each release and the latest can be found http://docs.couchbase.com/sdk-api/couchbase-python-client/[here].
Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Release Notes].
Most of the API documentation can also be accessed via `pydoc`.

xref:project-docs:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Python SDK.
The Python SDK source code is available on link:https://github.com/couchbase/couchbase-python-client[GitHub].

Information on new features, fixes, known issues as well as information on how to install older release versions is xref:project-docs:sdk-release-notes.adoc[in the release notes].

