= Install and Start Using the Python SDK with Couchbase Server
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:overview
:navtitle: Start Using the SDK

[abstract]
The Couchbase Python SDK allows Python applications to access a Couchbase cluster.
The Python SDK offers a traditional synchronous API as well as integration with _twisted_, _gevent_, and _asyncio_.
It depends on the C SDK, _libcouchbase_, which it uses for performance and reliability.

[WARNING]
====
These pages cover the Alpha of the Couchbase Python SDK. 
As such they are likely to change without notice. 
This alpha code should not be used in production.

Documentation is incomplete, subject to change, and likely to contain broken links.
====

Couchbase Python SDK bundles libcouchbase automatically, so no need to install it separately.
You may need cmake to install, although the installer will attempt to download it from PyPI automatically.

== Installing on Linux


.Debian and Ubuntu
[source,bash]
----
# Only needed during first-time setup:
sudo apt-get install build-essential python-dev python-pip
sudo pip install couchbase-3.0.0a2
----

.RHEL and CentOS
[source,bash]
----
# Only needed during first-time setup:
sudo yum install gcc gcc-c++ python-devel python-pip
sudo pip install couchbase-3.0.0a2
----

NOTE: RHEL/CentOS distributions may not provide the `python-pip` package in the base repositories.
It may be found in the https://fedoraproject.org/wiki/EPEL[EPEL^] repository.

== Installation on Mac OS X

To install the library on Mac OS X, first install the de-facto package manager for OS X: http://brew.sh/[Homebrew^].
Once _Homebrew_ is configured:

[source,bash]
----
brew update # get list of latest packages
brew install python
pip install couchbase-3.0.0a2
----

NOTE: The above example uses the Python supplied by Homebrew and not the vendor-supplied Python which ships with OS X.
The Python SDK will still work with the vendor-supplied Python (though _pip install_ may be a privileged command), but it is recommended to use Homebrew's Python instead.

== Installing on Microsoft Windows

[source,shell]
----
pip install couchbase-3.0.0a2
----

== Hello Couchbase

The code snippet below shows how the Python SDK may be used for some common operations.

[source,python]
----
include::example$hello_world_t.py[tag=intro]
----

=== Connecting

To connect to a Couchbase bucket, you must use Couchbase _Role-Based Access Control_ (RBAC).
This is fully described in the section xref:6.5@server:manage:manage-security/manage-users-and-roles.adoc[Authorization].
An _authenticator_, containing username and password, should be defined, and then passed to the cluster.
Following successful authentication, the bucket can be opened:

[source,python]
----
include::example$hello_world_t.py[tag=connecting]
----

Once defined, the authenticator can be passed to other clusters, as appropriate.

See xref:howtos:managing-connections.adoc[Managing Connections] for more connection options and details about the connection string.

=== Document Operations

xref:howtos:kv-operations.adoc[Document operations], such as storing and retrieving documents, can be done using simple methods on the `Bucket` class such as `Bucket.get` and `Bucket.upsert`.
Simply pass the key (and value, if applicable) to the relevant methods.

[source,python]
----
include::example$hello_world_t.py[tag=docopsget]
----

[source,python]
----
include::example$hello_world_t.py[tag=docopsupsert]
----

=== N1QL Queries

Couchbase N1QL queries are performed by creating a `N1QLQuery` object and passing that to the `Bucket.n1ql_query()` method:

[source,python]
----
include::example$hello_world_t.py[tag=n1ql]
----


== Additional Resources


The API reference is generated for each release and can be found linked from the xref:relnotes-python-sdk.adoc[release notes for your version of the Python SDK].
Most of the API documentation can also be accessed via `pydoc`.

// xref:project-docsmigrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Java SDK.
The Python SDK source code is available on link:https://github.com/couchbase/couchbase-python-client[GitHub].

Information on new features, fixes, known issues as well as information on how to install older release versions is xref:project-docs:sdk-release-notes.adoc[in the release notes].

=== PyPy support

Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.

An unofficial module, https://github.com/couchbaselabs/couchbase-python-cffi[couchbase_ffi^] uses ffi rather than the CPython C API to implement the internals of the library, and may be used with PyPy.
