= Install and Start Using the Python SDK with Couchbase Server
:description: Installing the Couchbase Python SDK & a Hello World example program.
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK
:page-partial:

[abstract]
The Couchbase Python SDK allows Python applications to access a Couchbase cluster.
It offers a traditional synchronous API as well as integration with _twisted_, _gevent_, and _asyncio_.
It depends on the C SDK, _libcouchbase_, (included automatically) which it uses for performance and reliability.

// tag::prep[]

The Couchbase Python SDK 3.x is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area, and adding support for Couchbase Server features like xref:concept-docs:collections.adoc[Collections and Scopes] (available from Couchbase Server 7.0).

The 3.x Python SDK introduces comprehensive https://www.python.org/dev/peps/pep-0484/[PEP-484] style type annotations.


== Requirements

Couchbase Python SDK bundles libcouchbase automatically, so no need to install it separately.
You may need CMake to install, although the installer will attempt to download it from PyPI automatically.

The Python SDK 3.x requires Python 3, with Python 3.5 and above supported.

// end::prep[]

// tag::install[]

[NOTE]
====
Currently the Python Client source distribution requires the OpenSSL headers and libraries that the Python client itself was built against to be installed prior to the client itself for TLS support to be provided.
Additionally the installer relies on PEP517 which older versions of PIP do not support.
If you experience issues installing it is advised to upgrade your PIP/setuptools installation as follows:
[source,console]
----
$ python3 -m pip install --upgrade pip setuptools wheel
----
====


=== Linux

Best practice is to use a Python virtual environment such as _venv_ or _pyenv_ to manage multible versions of Python. 
See https://github.com/pyenv/pyenv#basic-github-checkout[pyenv docs^] for details.

[{tabs}]
====
Debian and Ubuntu::
+
--
During first-time setup:

[source,console]
----
$ sudo apt-get install git-all python3-dev python3-pip python3-setuptools cmake build-essential
----

For TLS/SSL support (optional):

[source,console]
----
$ sudo apt-get install libssl-dev
----
--

RHEL and CentOS::
+
--
During first-time setup:

[source,console]
----
$ sudo yum install gcc gcc-c++ python3-devel python3-pip cmake
----

TIP: You may need to update your installed version of CMake.
For example, by following the steps https://idroot.us/install-cmake-centos-8[here^].

For TLS/SSL support (optional):

[source,console]
----
$ sudo yum install openssl-devel
----

NOTE: RHEL/CentOS distributions may not provide the `python3-pip` package in the base repositories.
It may be found in the https://fedoraproject.org/wiki/EPEL[EPEL^] repository.
--
====


=== Mac OS

Best practice is to use a Python virtual environment such as _venv_ or _pyenv_ to manage multible versions of Python, but in cases where this is not practicable follow the `brew` steps below, and also modify your `$PATH` as shown.

[NOTE]
====
There can be a problem when using the Python (3.8.2) that ships with Xcode on Catalina. 
It is advised to install Python via https://github.com/pyenv/pyenv#homebrew-on-macos[pyenv^]
(see the Python SDK https://github.com/couchbase/couchbase-python-client#mac-os-pyenv-install[Github README^] for further details on pyenv installation), http://brew.sh/[Homebrew^], or https://www.python.org/downloads[python.org^]
====

To install the library on Mac OS, first install http://brew.sh/[Homebrew^]. 

NOTE: Later versions of Mac OS can break the python3 homebrew installer. 
Simple mitigating steps may be found https://stackoverflow.com/questions/47255517/brew-install-python3-didnt-install-pip3[here^].

The following example uses the Python supplied by the _Homebrew_ package manager and not the vendor-supplied Python which ships with Mac OS. Once _Homebrew_ is configured:

.Get a list of the latest packages
[source,console]
----
$ brew update
----

.Install compatible Python 3
[source,console]
----
$ brew install python3
----

.For ZSH (MacOS 10.15 Catalina and newer)
[source,console]
----
$ echo 'export PATH="/usr/local/bin:"$PATH' >> ~/.zshrc
----

.For BASH (MacOS 10.14 Mojave and older)
[source,console]
----
$ echo 'export PATH="/usr/local/bin:"$PATH' >> ~/.bash_profile
----

.For TLS/SSL support - optional
[source,console]
----
$ brew install openssl
----


=== Microsoft Windows

Download and install Python from https://www.python.org/downloads[python.org^].  
Best practice is to use a Python virtual environment such as _venv_ or _pyenv_.

TIP: Checkout the https://github.com/pyenv-win/pyenv-win[pyenv-win^] project to manage multiple versions of Python.

Wheels are available on Windows for Python 3.7, 3.8 and 3.9.


== Installing on Linux

First, make sure the <<linux, requirements>> have been installed.

Install the latest Python SDK:

[source,console]
----
$ python3 -m pip install couchbase
----

== Installation on Mac OS

First, make sure the <<mac-os, requirements>> have been installed.

Install the latest Python SDK:

[source,console]
----
$ sudo -H python3 -m pip install couchbase
----


== Installing on Microsoft Windows

First, make sure the <<microsoft-windows, requirements>> have been installed.

NOTE: Commands assume user is working within a virtual environment.

Install the latest Python SDK (if using Python 3.7, 3.8 or 3.9):

[source,console]
----
python -m pip install couchbase
----

The standard Python distributions for Windows include OpenSSL DLLs, as PIP and the inbuilt `ssl` module require it for correct operation.
The binary wheels for Windows are packaged as a binary wheel built against the relevant version OpenSSL (which is fixed per Windows version of Python).

If you require a version without OpenSSL support, or that doesn't have a suitable binary wheel on PyPi, follow the https://github.com/couchbase/couchbase-python-client#alternative-installation-methods[build instructions] on the GitHub repo.

== Installing with Anaconda/Miniconda

To use the SDK within the Anaconda/Miniconda platform, make sure the prerequisites for the desired Operating System are met:

* <<linux, Linux>>
* <<mac-os, Mac OS>>
* <<microsoft-windows, Windows>>

In the _Anaconda Prompt_, create a new environment:
[source,console]
----
conda create -n test_env python=3.9
----

Activate the environment:
[source,console]
----
conda activate test_env
----

Install the SDK:
[source,console]
----
python -m pip install couchbase
----

NOTE: If using Windows, and no wheel is available, see the https://github.com/couchbase/couchbase-python-client#alternative-installation-methods[alternate installlation] methods on the Github README.  
The same process should work within the Anaconda/Miniconda platform.

// end::install[]


== Hello Couchbase

At this point we want to transition from the terminal to your code editor of choice.

Let's now create an empty file named `cb-test.py` and walk through adding code step-by-step:

* Connect to a cluster, bucket, and default collection;
* Add and retrieve a new document;
* Look up (SQL-type query) the new document by attribute value.

=== Prerequisites

As well as the Python SDK (see above), and a running instance of Couchbase Server, you will need to load up the Travel Sample Bucket
using either the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface]
or the xref:{version-server}@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].

=== Connection

The basic imports and connection string that you'll need are given below -- for more background information, refer to the xref:howtos:managing-connections.adoc#connection-strings[Managing Connections page].

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=connect]
----

Couchbase uses xref:{version-server}@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources.
For the sake of this example, we are connecting to Couchbase using the _Full Admin_ role created during the installation of our Couchbase Server.
The connection is being made to a single Couchbase node, running locally.

Couchbase RBAC is fully described in the section xref:{version-server}@server:manage:manage-security/manage-users-and-roles.adoc[Authorization].
An _authenticator_, containing username and password, should be defined, and then passed to the cluster.
Following successful authentication, the bucket can be opened:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=bucket]
----

NOTE: We are working with the link:https://docs.couchbase.com/server/current/manage/manage-settings/install-sample-buckets.html[travel-sample] data bucket. If you are not, substitute _travel-sample_ with your _bucket-name_.

If you are connecting to Couchbase Cloud rather than a local Couchbase Server, then also refer to the <<cloud-connections, Cloud section>>, below.

See xref:howtos:managing-connections.adoc[Managing Connections] for more connection options and details about the connection string.

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=collection]
----

The 3.2 SDK is ready for the introduction of xref:concept-docs:collections.adoc[Collections] in the xref:{version-server}@server:introduction:whats-new.adoc#whats-new-server-700[7.0 release] of the Couchbase Data Platform.
The latest release, Couchbase Server 7.0, brings Collections, allowing Documents to be grouped by purpose or theme, according to specified _Scope_.

NOTE: This feature was previously available as a _developer preview_ from Couchbase Server 6.6. _When connecting to a 6.6 cluster or earlier_, we must use the `DefaultCollection`, which covers the whole Bucket.

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=default-collection]
----

=== Document Addition and Retrieval

Let's create a dictionary object in our application that we can add to our `travel-sample` bucket that conforms to the structure of a document of type `airline`.

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=test-doc]
----

xref:howtos:kv-operations.adoc[Document operations], such as storing and retrieving documents, can be done using simple methods on the `Collection` class such as `Collection.get` and `Collection.upsert`.
Simply pass the key (and value, if applicable) to the relevant methods.

The following function will `upsert()` a document and print the returned link:https://docs.couchbase.com/python-sdk/3.2/howtos/concurrent-document-mutations.html[CAS] value:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=upsert-func]
----

Now, we can simply call the `upsert_document` function passing in our `airline` document:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=upsert-invoke]
----

Now let's retrieve that document using a key-value operation. The following function runs a `get()` for a document key and either logs out the result or error in our console:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=get-func]
----

Key-value Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].

Now, we can simply call the `get_airline_by_key` function passing in our valid document key `airline_8091`:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=get-invoke]
----


=== SQL++ Lookup

Couchbase N1QL queries are performed by invoking the `Cluster.query()` method.  The following function executes a lookup for documents of `type='airline'` by a provided `callsign`:

[source,python]
----
include::../examples/hello_world_t.py[tag=lookup-func]
----

We call the `lookup_by_callsign` function passing in our callsign `CBS`:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=lookup-invoke]
----

=== Execute!

Now we can run our code using the following command:

[source,console]
----
$ python3 cb-test.py
----

The results you should expect are as follows:

[source,console]
----
Upsert CAS:
1598469741559152640

Get Result:
{'type': 'airline', 'id': 8091, 'callsign': 'CBS', 'iata': None, 'icao': None, 'name': 'Couchbase Airways'}

Lookup Result:
Couchbase Airways
----

== Full Example

If you want to copy and paste to run the full example, here it is:

[{tabs}] 
==== 
Local Couchbase Server::
+ 
-- 
[source,python]
----
include::hello-world:example$hello_world_t.py[tag=connect]

include::hello-world:example$hello_world_t.py[tag=bucket]

include::hello-world:example$hello_world_t.py[tag=collection]

include::hello-world:example$hello_world_t.py[tag=upsert-func]

include::hello-world:example$hello_world_t.py[tag=get-func]

include::hello-world:example$hello_world_t.py[tag=lookup-func]

include::hello-world:example$hello_world_t.py[tag=test-doc]

include::hello-world:example$hello_world_t.py[tag=upsert-invoke]

include::hello-world:example$hello_world_t.py[tag=get-invoke]

include::hello-world:example$hello_world_t.py[tag=lookup-invoke]

----
--

Couchbase Cloud Sample::
+
--
If you are connecting to https://docs.couchbase.com/cloud/index.html[Couchbase Cloud], be sure to get the correct endpoint as well as user, password, certificate and `couchbasecloudbucket`  -- and see the <<cloud-connections, Cloud section>>, below.

[source,python]
----
include::hello-world:example$cloud.py[tag=cloud_connect]
----
--
====

== Cloud Connections

For developing on Couchbase Cloud, if you are not working from the same _Availability Zone_ as your Couchbase Cloud, refer to the following:

* Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
* xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
* If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].


== Additional Resources

The API reference is generated for each release and the latest can be found http://docs.couchbase.com/sdk-api/couchbase-python-client/[here].

Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Individual Release Notes].
Most of the API documentation can also be accessed via `pydoc`.

xref:project-docs:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Python SDK.
The Python SDK source code is available on link:https://github.com/couchbase/couchbase-python-client[GitHub].


=== PyPy support

Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.

Please link:https://issues.couchbase.com/projects/PYCBC/issues[create a Jira ticket] if you require a PyPy-compatible version of the SDK.
