= Install and Start Using the Python SDK with Couchbase Server
:page-aliases: ROOT:getting-started,ROOT:start-using,ROOT:hello-couchbase,ROOT:start-using-sdk
:navtitle: Start Using the SDK
:page-partial:

[abstract]
The Couchbase Python SDK allows Python applications to access a Couchbase cluster.
The Python SDK offers a traditional synchronous API as well as integration with _twisted_, _gevent_, and _asyncio_.
It depends on the C SDK, _libcouchbase_, (included automatically) which it uses for performance and reliability.

// tag::prep[]

The Couchbase Python SDK 3.0 is a complete rewrite of the API, reducing the number of overloads to present a simplified surface area, and adding support for future Couchbase Server features like Collections and Scopes (available in Couchbase Server 6.5 & 6.6 as a xref:concept-docs:collections.adoc[developer preview]).

The 3.0 Python SDK introduces comprehensive https://www.python.org/dev/peps/pep-0484/[PEP-484] style type annotations.


== Requirements


Couchbase Python SDK bundles libcouchbase automatically, so no need to install it separately.
You may need CMake to install, although the installer will attempt to download it from PyPI automatically.

The Python SDK 3.0 requires Python 3, with Python 3.5 and above supported.

// end::prep[]

// tag::install[]

[NOTE]
====
Currently the Python Client source distribution requires the OpenSSL headers and libraries that the Python client itself was built against to be installed prior to the client itself for TLS support to be provided.
Additionally the installer relies on PEP517 which older versions of PIP do not support.
If you experience issues installing it is advised to upgrade your PIP/setuptools installation as follows:
[source,console]
----
$ python3 -m pip install --upgrade pip setuptools wheel
----
====


== Installing on Linux


[{tabs}] 
==== 
Debian and Ubuntu::
+
--
During first-time setup:

[source,console]
----
$ sudo apt-get install git-all python3-dev python3-pip python3-setuptools cmake build-essential
----

For TLS/SSL support (optional):

[source,console]
----
$ sudo apt-get install libssl-dev
----

Now install the latest Python SDK:

[source,console]
----
$ python3 -m pip install couchbase
----
--

RHEL and CentOS::
+
--
During first-time setup:

[source,console]
----
$ sudo yum install gcc gcc-c++ python3-devel python3-pip cmake
----

TIP: You may need to update your installed version of CMake. 
For example, by following the steps https://idroot.us/install-cmake-centos-8[here^].

For TLS/SSL support (optional):

[source,console]
----
$ sudo yum install openssl-devel
----

Now install the latest Python SDK:

[source,console]
----
$ python3 -m pip install couchbase
----

NOTE: RHEL/CentOS distributions may not provide the `python3-pip` package in the base repositories.
It may be found in the https://fedoraproject.org/wiki/EPEL[EPEL^] repository.
--
====


== Installation on Mac OS X

The following example uses the Python supplied by the Homebrew package manager and not the vendor-supplied Python which ships with OS X.  

To install the library on Mac OS X, first install Homebrew: http://brew.sh/[Homebrew^]. 
Once _Homebrew_ is configured:

NOTE: Later versions of Mac OS X break the python3 homebrew installer. 
Simple mitigating steps may be found https://stackoverflow.com/questions/47255517/brew-install-python3-didnt-install-pip3[here^].

Best practice is to use a Python virtual environment such as _venv_ or _pyenv_ to manage multible versions of Python, but in cases where this is not practicable follow the `brew` steps below, and also modify your `$PATH` as shown.

====
.Get a list of the latest packages
[source,console]
----
$ brew update
----

.Install compatible Python 3
[source,console]
----
$ brew install python3
----

.For ZSH (MacOS 10.15 Catalina and newer)
[source,console]
----
$ echo 'export PATH="/usr/local/bin:"$PATH' >> ~/.zshrc
----

.For BASH (MacOS 10.14 Mojave and older)
[source,console]
----
$ echo 'export PATH="/usr/local/bin:"$PATH' >> ~/.bash_profile
----

.For TLS/SSL support - optional
[source,console]
----
$ brew install openssl
----

.Installing the SDK
[source,console]
----
$ sudo -H python3 -m pip install couchbase
----
====


== Installing on Microsoft Windows

[source,console]
----
$ python3 -m pip install couchbase
----

The standard Python distributions for Windows include OpenSSL DLLs, as PIP and the inbuilt `ssl` module require it for correct operation.
The binary wheels for Windows are packaged as a binary wheel built against the relevant version OpenSSL (which is fixed per Windows version of Python).

If you require a version without OpenSSL support, or that doesn't have a suitable binary wheel on PyPi, follow the build instructions on the GitHub repo.

// end::install[]


== Hello Couchbase

At this point we want to transition from the terminal to your code editor of choice.

Let's now create an empty file named `cb-test.py` and walk through adding code step-by-step: 

* Connect to a cluster, bucket, and default collection;
* Add and retrieve a new document;
* Look up (SQL-type query) the new document by attribute value.

=== Prerequisites

As well as the Python SDK (see above), and a running instance of Couchbase Server, you will need to load up the Travel Sample Bucket 
using either the xref:6.5@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-ui[Web interface] 
or the xref:6.5@server:manage:manage-settings/install-sample-buckets.adoc#install-sample-buckets-with-the-cli[command line].

=== Connection

The basic imports and connection string that you'll need are given below -- for more background information, refer to the xref:howtos:managing-connections.adoc#connection-strings[Managing Connections page].

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=connect]
----

Couchbase uses xref:6.5@server:learn:security/roles.adoc[Role Based Access Control (RBAC)] to control access to resources. 
For the sake of this example, we are connecting to Couchbase using the _Full Admin_ role created during the installation of our Couchbase Server. 
The connection is being made to a single Couchbase node, running locally.

Couchbase RBAC is fully described in the section xref:6.5@server:manage:manage-security/manage-users-and-roles.adoc[Authorization].
An _authenticator_, containing username and password, should be defined, and then passed to the cluster.
Following successful authentication, the bucket can be opened:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=bucket]
----

NOTE: We are working with the link:https://docs.couchbase.com/server/current/manage/manage-settings/install-sample-buckets.html[travel-sample] data bucket. If you are not, substitute _travel-sample_ with your _bucket-name_.

If you are connecting to Couchbase Cloud rather than a local Couchbase Server, then also refer to the <<cloud-connections, Cloud section>>, below.

See xref:howtos:managing-connections.adoc[Managing Connections] for more connection options and details about the connection string.

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=default-collection]
----

The latest Couchbase Server release (6.5), brings a limited _Developer Preview_ of Collections, allowing Documents to be grouped by purpose or theme, according to a specified _Collection_. 
For our "Hello Couchbase" example we will simply use `DefaultCollection`, rather than a specific collection, which includes all documents in a bucket, and is forwards and backwards compatible with all supported versions of Couchbase Server.
Once the _Collection_ feature is generally available, the best practice will be to group documents into collections by type.

=== Document Addition and Retrieval

Let's create a dictionary object in our application that we can add to our `travel-sample` bucket that conforms to the structure of a document of type `airline`.

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=test-doc]
----

xref:howtos:kv-operations.adoc[Document operations], such as storing and retrieving documents, can be done using simple methods on the `Bucket` class such as `Bucket.get` and `Bucket.upsert`.
Simply pass the key (and value, if applicable) to the relevant methods.

The following function will `upsert()` a document and print the returned link:https://docs.couchbase.com/python-sdk/3.0/howtos/concurrent-document-mutations.html[CAS] value:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=upsert-func]
----

Now, we can simply call the `upsert_document` function passing in our `airline` document:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=upsert-invoke]
----

Now let's retrieve that document using a key-value operation. The following function runs a `get()` for a document key and either logs out the result or error in our console:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=get-func]
----

Key-value Operations are described in detail on the xref:howtos:kv-operations.adoc[KV Operations page].

Now, we can simply call the `get_airline_by_key` function passing in our valid document key `airline_8091`:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=get-invoke]
----


=== SQL++ Lookup

Couchbase N1QL queries are performed by invoking the `Cluster.query()` method.  The following function executes a lookup for documents of `type='airline'` by a provided `callsign`:

[source,python]
----
include::../examples/hello_world_t.py[tag=lookup-func]
----

We call the `lookup_by_callsign` function passing in our callsign `CBS`:

[source,python,indent=0]
----
include::../examples/hello_world_t.py[tag=lookup-invoke]
----

=== Execute!

Now we can run our code using the following command:

[source,console]
----
$ python3 cb-test.py
----

The results you should expect are as follows:

[source,console]
----
Upsert CAS: 
1598469741559152640

Get Result: 
{'type': 'airline', 'id': 8091, 'callsign': 'CBS', 'iata': None, 'icao': None, 'name': 'Couchbase Airways'}

Lookup Result: 
Couchbase Airways
----


== Cloud Connections

For developing on Couchbase Cloud, try the https://github.com/couchbase/docs-sdk-python/blob/release/3.0/modules/devguide/examples/python/cloud.py[Cloud-based Hello World program].

If you are not working from the same _Availability Zone_ as your Couchbase Cloud, refer to the following:

* Notes on xref:ref:client-settings.adoc#constrained-network-environments[Constrained Network Environments].
* xref:project-docs:compatibility.adoc#network-requirements[Network Requirements].
* If you have a consumer-grade router which has problems with DNS-SRV records review our xref:howtos:troubleshooting-cloud-connections.adoc#troubleshooting-host-not-found[Troubleshooting Guide].


== Additional Resources

The API reference is generated for each release and the latest can be found http://docs.couchbase.com/sdk-api/couchbase-python-client/[here].

Older API references are linked from their respective sections in the xref:project-docs:sdk-release-notes.adoc[Individual Release Notes].
Most of the API documentation can also be accessed via `pydoc`.

xref:project-docs:migrating-sdk-code-to-3.n.adoc[The Migrating from SDK2 to 3 page] highlights the main differences to be aware of when migrating your code.

Couchbase welcomes community contributions to the Python SDK.
The Python SDK source code is available on link:https://github.com/couchbase/couchbase-python-client[GitHub].


=== PyPy support

Because the Python SDK is written primarily in C using the CPython API, the official SDK will not work on PyPy.

Please link:https://issues.couchbase.com/projects/PYCBC/issues[create a Jira ticket] if you require a PyPy-compatible version of the SDK.
